      // Piano voices share the live, transport and offline rendering path.
      const PIANO_DEFAULTS={engine:'piano',pianoTone:.55,pianoHammer:.22,pianoBody:.4,pianoDecay:5.5,pianoRelease:.24,width:.6};
      const PIANO_PRESETS=[
        {name:'Studio Grand',description:'Clear attack · resonant strings',pianoTone:.7,pianoHammer:.3,pianoBody:.5,pianoDecay:6.5,pianoRelease:.28},
        {name:'Felt Piano',description:'Soft hammers · intimate character',pianoTone:.2,pianoHammer:.09,pianoBody:.7,pianoDecay:4.5,pianoRelease:.42},
        {name:'Mellow Upright',description:'Warm body · gently imperfect',pianoTone:.42,pianoHammer:.2,pianoBody:.32,pianoDecay:3.8,pianoRelease:.19}
      ];
      PIANO_PRESETS.forEach(p=>SYNTH_PRESETS.unshift({name:p.name,category:'Keys',description:p.description,synth:{...DEFAULT_SYNTH,...PRO_SYNTH,...PIANO_DEFAULTS,...p}}));
      const pianoSynthBase=proSynth;
      proSynth=function(track){const s=pianoSynthBase(track);s.engine=s.engine==='piano'?'piano':'synth';for(const [key,min,max] of [['pianoTone',0,1],['pianoHammer',0,1],['pianoBody',0,1],['pianoDecay',1,10],['pianoRelease',.05,1.5]])s[key]=clamp(finiteNumber(s[key],PIANO_DEFAULTS[key]),min,max);return s;};
      function pianoVoice(ctx,output,track,note,time,duration,live){
        const s=proSynth(track),v=clamp(finiteNumber(note.velocity,.78),.01,1),freq=noteFrequency(note.pitch+s.octave*12),nodes=[],sources=[];
        const node=n=>(nodes.push(n),n),source=n=>{sources.push(n);if(live)studioTrackSource(n);return n;};
        const amp=node(ctx.createGain()),filter=node(ctx.createBiquadFilter()),pan=node(ctx.createStereoPanner());
        amp.gain.value=1;filter.type='lowpass';filter.frequency.value=Math.min(ctx.sampleRate*.44,1100+s.pianoTone*7800+v*4200);filter.Q.value=.45;pan.pan.value=clamp((note.pitch-60)/48*s.width,-.8,.8);filter.connect(amp);amp.connect(pan);pan.connect(output);
        const decay=s.pianoDecay*Math.pow(2,(60-note.pitch)/48),naturalEnd=time+Math.min(18,decay*2.2+1),peak=.26*Math.pow(v,1.6);
        for(let partial=1;partial<=8;partial++){
          const f=freq*partial*Math.sqrt(1+.00006*(1+s.pianoBody)*partial*partial);if(f>=ctx.sampleRate*.44)continue;
          const osc=source(ctx.createOscillator()),gain=node(ctx.createGain());osc.type='sine';osc.frequency.value=f;osc.detune.value=s.detune+(partial%2?1:-1)*s.pianoBody*2.5;
          const level=peak*Math.pow(.58+s.pianoTone*.18+v*.07,partial-1)/Math.pow(partial,.6),tail=Math.min(naturalEnd,time+decay/(1+(partial-1)*.32));
          gain.gain.setValueAtTime(.00001,time);gain.gain.exponentialRampToValueAtTime(Math.max(.00002,level),time+.003+(1-v)*.004);gain.gain.exponentialRampToValueAtTime(.00001,tail);osc.connect(gain);gain.connect(filter);
        }
        if(s.pianoHammer>0){const noise=source(ctx.createBufferSource()),gain=node(ctx.createGain()),hp=node(ctx.createBiquadFilter());noise.buffer=proNoise(ctx);hp.type='highpass';hp.frequency.value=700+v*1500;gain.gain.setValueAtTime(peak*s.pianoHammer*.35,time);gain.gain.exponentialRampToValueAtTime(.00001,time+.035);noise.connect(hp);hp.connect(gain);gain.connect(filter);}
        let ended=0,released=false;sources.forEach(src=>{src.addEventListener('ended',()=>{src.disconnect();if(++ended===sources.length)nodes.forEach(n=>n.disconnect());},{once:true});src.start(time);src.stop(naturalEnd+.02);});
        function release(at){if(released)return;released=true;const end=at+s.pianoRelease*(1+s.pianoBody*.5);amp.gain.setValueAtTime(1,at);amp.gain.exponentialRampToValueAtTime(.00001,end);sources.forEach(src=>{try{src.stop(Math.min(naturalEnd+.02,end+.03));}catch(_){}});}
        if(duration!==null)release(time+Math.max(.03,duration));
        return ()=>release(ctx.currentTime);
      }
      const pianoBaseVoice=proVoice;proVoice=function(ctx,output,track,note,time,duration,live=true){if(!ctx||!output)return null;return proSynth(track).engine==='piano'&&!track.sampleId?pianoVoice(ctx,output,track,note,time,duration,live):pianoBaseVoice(ctx,output,track,note,time,duration,live);};
      const pianoPerformance={range:25,velocity:.8,chord:'single',inversion:0,pedal:new Set(),deferred:new Set(),chords:new Map()};
      let pianoInputEditing=false;
      const pianoChords={single:[0],major:[0,4,7],minor:[0,3,7],seventh:[0,4,7,10],minor7:[0,3,7,10],sus2:[0,2,7],sus4:[0,5,7]};
      function pianoChordPitches(root,quality,inversion=0){const offsets=[...(pianoChords[quality]||[0])];for(let i=0;i<Math.min(inversion,offsets.length-1);i++)offsets[i]+=12;return offsets.map(o=>clamp(root+o,0,127));}
      function pianoPedal(source,down){down?pianoPerformance.pedal.add(source):pianoPerformance.pedal.delete(source);if(!pianoPerformance.pedal.size){for(const item of pianoPerformance.deferred)item.release();pianoPerformance.deferred.clear();}pianoSyncPerformance();}
      const pianoBaseHeld=startHeldNote;startHeldNote=function(track,note,velocity,time){const release=pianoBaseHeld(track,note,velocity,time);let done=false;return ()=>{if(done)return;done=true;if(pianoPerformance.pedal.size)pianoPerformance.deferred.add({release,pitch:note.pitch});else release();pianoSyncPerformance();};};
      const pianoBaseDown=(...args)=>{pianoInputEditing=true;try{return liveNoteDownOriginal(...args);}finally{pianoInputEditing=false;}},liveNoteDownOriginal=liveNoteDown;
      const pianoBaseUp=(...args)=>{pianoInputEditing=true;try{return liveNoteUpOriginal(...args);}finally{pianoInputEditing=false;}},liveNoteUpOriginal=liveNoteUp;
      liveNoteDown=function(source,pitch,velocity=.82,timestamp=performance.now()){if(activeLiveNotes.has(source)||pianoPerformance.chords.has(source))return;const assisted=editorTab==='perform'&&(source.startsWith('performance:')||source.startsWith('computer:'));const pitches=assisted?pianoChordPitches(pitch,pianoPerformance.chord,pianoPerformance.inversion):[pitch];for(const p of pitches){for(const item of pianoPerformance.deferred){if(item.pitch===p){item.release();pianoPerformance.deferred.delete(item);}}}if(pitches.length>1){const ids=pitches.map((_,i)=>`${source}:chord:${i}`);pianoPerformance.chords.set(source,ids);pitches.forEach((p,i)=>pianoBaseDown(ids[i],p,velocity,timestamp));}else pianoBaseDown(source,pitch,velocity,timestamp);pianoSyncPerformance();};
      liveNoteUp=function(source,timestamp){const ids=pianoPerformance.chords.get(source);if(ids){ids.forEach(id=>pianoBaseUp(id,timestamp));pianoPerformance.chords.delete(source);}else pianoBaseUp(source,timestamp);pianoSyncPerformance();};
      const pianoBaseRelease=releaseAllLiveNotes;releaseAllLiveNotes=function(){pianoPerformance.pedal.clear();for(const item of pianoPerformance.deferred)item.release();pianoPerformance.deferred.clear();pianoBaseRelease();pianoPerformance.chords.clear();pianoSyncPerformance();};
      const pianoBaseMidi=handleMidiMessage;handleMidiMessage=function(input,event){const [status,control,value]=event.data||[];if((status&0xf0)===0xb0&&control===64){pianoPedal(`midi:${input.id}:${status&15}`,value>=64);return;}pianoBaseMidi(input,event);};
      const pianoBaseConnect=connectMidiKeyboard;connectMidiKeyboard=async function(){await pianoBaseConnect();if(!midiAccess)return;const previous=midiAccess.onstatechange;midiAccess.onstatechange=event=>{if(event.port?.type==='input'&&event.port.state==='disconnected'){for(const source of [...pianoPerformance.pedal])if(source.startsWith(`midi:${event.port.id}:`))pianoPedal(source,false);}previous?.(event);};};
      function pianoSyncPerformance(){const pitches=new Set([...activeLiveNotes.values()].map(n=>n.pitch)),held=new Set([...pianoPerformance.deferred].map(n=>n.pitch));document.querySelectorAll('.performance-key').forEach(k=>{const pitch=Number(k.dataset.pitch);k.classList.toggle('pressed',pitches.has(pitch));k.classList.toggle('sustained',held.has(pitch));k.setAttribute('aria-pressed',String(pitches.has(pitch)));});const button=$('#pianoSustain');if(button){button.classList.toggle('active',!!pianoPerformance.pedal.size);button.setAttribute('aria-pressed',String(!!pianoPerformance.pedal.size));}const label=$('#performanceNow');if(label)label.textContent=pitches.size?[...pitches].sort((a,b)=>a-b).map(pitchName).join(' · '):held.size?'Sustain active':'No active notes';}
      function pianoLoad(track,name){const preset=SYNTH_PRESETS.find(p=>p.name===name);if(!preset)return;releaseAllLiveNotes();studioEdit(()=>{track.instrument=preset.name;track.synth=clone(preset.synth);track.waveform=preset.synth.waveform;delete track.sampleId;delete track.sampleRootPitch;});}
      function pianoSoundControls(parent,track){track.synth=proSynth(track);for(const [key,label,min,max,step] of [['pianoTone','Brightness',0,1,.01],['pianoHammer','Hammer',0,1,.01],['pianoBody','String character',0,1,.01],['pianoDecay','Decay',1,10,.1],['pianoRelease','Key release',.05,1.5,.01]])studioRange(parent,label,track.synth[key],min,max,step,v=>track.synth[key]=v,v=>key==='pianoDecay'||key==='pianoRelease'?`${v.toFixed(2)} s`:`${Math.round(v*100)}%`);}
      function pianoRenderPerformance(track){
        const root=document.createElement('div');root.className='performance';editorBodyEl.append(root);
        if(track.type!=='synth'){root.innerHTML='<h2>Choose an instrument track</h2><p>Open a keys, bass or pad track to play its sound here.</p>';return;}
        const top=document.createElement('div');top.className='performance-top';top.innerHTML='<div><small>SONORA / PERFORMANCE</small><h2></h2><p>Play using the on-screen keys, computer keyboard, or a MIDI controller.</p></div>';top.querySelector('h2').textContent=track.instrument;const controls=document.createElement('div');controls.className='performance-top-actions';
        const sounds=document.createElement('select');sounds.id='pianoSound';sounds.setAttribute('aria-label','Piano sound');const current=document.createElement('option');current.value='';current.textContent=`Current · ${track.instrument}`;sounds.append(current);PIANO_PRESETS.forEach(p=>{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;sounds.append(o);});sounds.addEventListener('change',()=>{if(sounds.value)pianoLoad(track,sounds.value);});
        controls.append(sounds,studioButton('Sound designer ↗',()=>{editorTab='instrument';renderEditor();}));top.append(controls);root.append(top);
        const tools=document.createElement('div');tools.className='performance-tools';
        const range=document.createElement('select');range.id='pianoRange';range.setAttribute('aria-label','Keyboard size');for(const count of [25,49,88]){const o=document.createElement('option');o.value=count;o.textContent=`${count} keys`;range.append(o);}range.value=pianoPerformance.range;range.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.range=Number(range.value);renderEditor();});
        const chord=document.createElement('select');chord.id='pianoChordMode';chord.setAttribute('aria-label','Performance chord mode');Object.entries({single:'Single notes',major:'Major triad',minor:'Minor triad',seventh:'Dominant 7',minor7:'Minor 7',sus2:'Sus 2',sus4:'Sus 4'}).forEach(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;chord.append(o);});chord.value=pianoPerformance.chord;chord.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.chord=chord.value;});
        const sustain=studioButton('◉ Sustain · Shift',()=>pianoPedal('button',!pianoPerformance.pedal.has('button')));sustain.id='pianoSustain';sustain.setAttribute('aria-pressed','false');
        const inversion=document.createElement('select');inversion.setAttribute('aria-label','Performance chord inversion');for(const [value,label] of [[0,'Root position'],[1,'1st inversion'],[2,'2nd inversion']]){const o=document.createElement('option');o.value=value;o.textContent=label;inversion.append(o);}inversion.value=pianoPerformance.inversion;inversion.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.inversion=Number(inversion.value);});
        const touch=document.createElement('label');touch.className='performance-touch';touch.textContent='Touch';const velocity=document.createElement('input');velocity.type='range';velocity.min=10;velocity.max=100;velocity.value=Math.round(pianoPerformance.velocity*100);velocity.setAttribute('aria-label','Computer keyboard velocity');velocity.addEventListener('input',()=>pianoPerformance.velocity=Number(velocity.value)/100);touch.append(velocity);
        const shift=delta=>{releaseAllLiveNotes();keyboardBasePitch=clamp(keyboardBasePitch+delta,24,84);renderEditor();};
        tools.append(range,studioButton('− Octave',()=>shift(-12)),studioButton('+ Octave',()=>shift(12)),chord,inversion,touch,sustain,studioButton('All notes off',releaseAllLiveNotes));root.append(tools);
        const strip=document.createElement('div');strip.className='performance-readout';strip.innerHTML='<span id="performanceNow" role="status"></span><span>TOP OF KEY = SOFT · BOTTOM = BRIGHT</span>';root.append(strip);
        const scroll=document.createElement('div');scroll.className='performance-scroll';const bed=document.createElement('div');bed.className='performance-bed';bed.setAttribute('aria-label','Playable piano keyboard');scroll.append(bed);root.append(scroll);
        const count=pianoPerformance.range,start=count===88?21:clamp(keyboardBasePitch-(count===49?12:0),0,127-count),whitePitches=[];
        for(let pitch=start;pitch<start+count;pitch++)if(![1,3,6,8,10].includes(pitch%12))whitePitches.push(pitch);
        bed.style.setProperty('--white-count',whitePitches.length);bed.style.minWidth=`${whitePitches.length*(count===88?34:42)}px`;
        const pointerSources=new Map();
        for(let pitch=start;pitch<start+count;pitch++){const black=[1,3,6,8,10].includes(pitch%12),key=document.createElement('button');key.type='button';key.className=`performance-key ${black?'black':'white'}`;key.dataset.pitch=pitch;key.setAttribute('aria-label',`Play ${pitchName(pitch)}`);key.setAttribute('aria-pressed','false');const wi=whitePitches.filter(p=>p<pitch).length;key.style.left=`${(black?wi-.31:wi)/whitePitches.length*100}%`;key.style.width=`${(black?.62:1)/whitePitches.length*100}%`;key.innerHTML='<span></span><small></small>';key.firstChild.textContent=black?pitchName(pitch).replace(/\d+/,''):pitchName(pitch);const code=Object.entries(LIVE_KEY_PITCHES).find(([,offset])=>keyboardBasePitch+offset===pitch)?.[0];key.lastChild.textContent=code?.replace('Key','').replace('Digit','')||'';if(proRoll.scale!=='off'&&proScales[proRoll.scale].includes((pitch-proRoll.root+120)%12))key.classList.add('scale-key');
          key.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const r=key.getBoundingClientRect(),velocity=clamp(.35+(e.clientY-r.top)/r.height*.6,.2,1),source=`performance:${e.pointerId}`;pointerSources.set(e.pointerId,source);key.setPointerCapture(e.pointerId);liveNoteDown(source,pitch,velocity);});
          const up=e=>{const source=pointerSources.get(e.pointerId);if(source){liveNoteUp(source);pointerSources.delete(e.pointerId);}};key.addEventListener('pointerup',up);key.addEventListener('pointercancel',up);key.addEventListener('lostpointercapture',up);
          key.addEventListener('keydown',e=>{if(e.code==='Space'||e.key==='Enter'){e.preventDefault();e.stopPropagation();if(!e.repeat)liveNoteDown(`performance:accessible:${pitch}`,pitch,pianoPerformance.velocity);}});key.addEventListener('keyup',e=>{if(e.code==='Space'||e.key==='Enter'){e.preventDefault();e.stopPropagation();liveNoteUp(`performance:accessible:${pitch}`);}});key.addEventListener('blur',()=>liveNoteUp(`performance:accessible:${pitch}`));bed.append(key);}
        const footer=document.createElement('div');footer.className='performance-footer';footer.innerHTML='<span>Computer keys Z–M & Q–U · hold Shift for pedal · Arm recording and start playback to record notes</span>';if(!selectedClipFor(track))footer.append(studioButton('+ Add recording clip',addClip));const midi=document.createElement('div');midi.className='performance-midi';const midiSelect=document.createElement('select');midiSelect.id='midiInputSelect';midiSelect.setAttribute('aria-label','Performance MIDI input');midiSelect.addEventListener('change',()=>{releaseAllLiveNotes();midiInputId=midiSelect.value;refreshMidiKeyboard();});const midiStatus=document.createElement('span');midiStatus.id='midiStatus';const midiButton=studioButton('Connect MIDI',connectMidiKeyboard);midiButton.id='midiConnectButton';midi.append(midiStatus,midiSelect,midiButton);footer.append(midi);root.append(footer);refreshMidiKeyboard();
        if(proSynth(track).engine==='piano'&&!track.sampleId){const params=document.createElement('div');params.className='piano-parameters';pianoSoundControls(params,track);root.append(params);}pianoSyncPerformance();
      }
      const pianoInstrumentBase=proRenderInstrument;proRenderInstrument=function(track){if(proSynth(track).engine!=='piano'||track.type!=='synth'||track.sampleId){pianoInstrumentBase(track);return;}const root=document.createElement('div');root.className='instrument-editor piano-designer';root.innerHTML='<div class="instrument-eyebrow">SONORA / PIANO DESIGN</div><h2></h2><p>Eight harmonic partials, velocity-sensitive hammers and string decay. Synthesized in your browser.</p>';root.querySelector('h2').textContent=track.instrument;const actions=document.createElement('div');actions.className='instrument-actions';actions.append(studioButton('▷ Audition',()=>proAudition(track,true),'text-button pro-primary'),studioButton('Save patch',()=>proOpenPatch(track)),studioButton('Play this piano →',()=>{editorTab='perform';renderEditor();}));root.append(actions);const params=document.createElement('div');params.className='piano-parameters';pianoSoundControls(params,track);root.append(params);editorBodyEl.append(root);};
      const pianoBaseEditor=renderEditor;renderEditor=function(){if(editorTab!=='perform'){pianoBaseEditor();return;}if(pianoInputEditing&&$('.performance')){pianoSyncPerformance();return;}editorBodyEl.replaceChildren();$('#noteToolbar').style.display='none';$('#noteLength').style.display='none';$('#clearPatternButton').style.display='none';$('#proRollControls').hidden=true;document.querySelectorAll('.editor-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='perform'));$('#editorTrackName').textContent=`${getTrack().name} · Performance`;pianoRenderPerformance(getTrack());studioRenderInspector();updateStatus();};
      const performTab=studioButton('Perform',()=>{releaseAllLiveNotes();editorTab='perform';renderEditor();},'editor-tab');performTab.dataset.tab='perform';$('.editor-tabs').insertBefore(performTab,$('.editor-tab[data-tab="instrument"]'));
      window.addEventListener('keydown',e=>{if(editorTab!=='perform'||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='ShiftLeft'||e.code==='ShiftRight'){pianoPedal(e.code,true);return;}if(Object.hasOwn(LIVE_KEY_PITCHES,e.code)){e.preventDefault();if(!e.repeat)liveNoteDown(`computer:${e.code}`,keyboardBasePitch+LIVE_KEY_PITCHES[e.code],pianoPerformance.velocity);}});
      window.addEventListener('keyup',e=>{if(e.code==='ShiftLeft'||e.code==='ShiftRight')pianoPedal(e.code,false);});
      document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAllLiveNotes();});
      const pianoTools=document.createElement('div');pianoTools.className='piano-compose-tools';pianoTools.id='pianoComposeTools';pianoTools.innerHTML='<span class="piano-tools-label">CHORD BUILDER</span><select id="pianoChordQuality" aria-label="Insert chord type"><option value="minor">Minor</option><option value="major">Major</option><option value="minor7">Minor 7</option><option value="seventh">Dominant 7</option><option value="sus2">Sus 2</option><option value="sus4">Sus 4</option></select><select id="pianoInversion" aria-label="Chord inversion"><option value="0">Root position</option><option value="1">1st inversion</option><option value="2">2nd inversion</option></select>';
      function pianoInsertChord(){const track=getTrack(),clip=selectedClipFor(track);if(!clip||track.type!=='synth')return;const chosen=selectedNoteList(),anchor=chosen[0],root=anchor?.pitch??60+proRoll.root,start=clamp(anchor?.start??pianoCursor,0,15.9375),duration=Math.min(anchor?.duration??(Number($('#noteLength').value)||1),16-start),before=JSON.stringify(project),notes=notesForClip(track,clip);selectedNotes.clear();pianoChordPitches(root,$('#pianoChordQuality').value,Number($('#pianoInversion').value)).forEach(pitch=>{let note=notes.find(n=>n.start===start&&n.pitch===pitch);if(!note){note={start,pitch,duration,velocity:anchor?.velocity??.78};notes.push(note);}selectedNotes.add(note);});audio.selectedNote=selectedNoteList()[0];commitNoteEdit(before);}
      function pianoArpeggiate(){const notes=selectedNoteList();if(notes.length<2){notify('Select two or more notes to arpeggiate');return;}const before=JSON.stringify(project),start=Math.min(...notes.map(n=>n.start)),step=Number($('#snapSelect').value)||.25;notes.sort((a,b)=>a.pitch-b.pitch).forEach((n,i)=>{n.start=Math.min(15.9375,start+i*step);n.duration=Math.min(step,16-n.start);});commitNoteEdit(before);}
      pianoTools.append(studioButton('+ Insert chord',pianoInsertChord),studioButton('Arpeggiate',pianoArpeggiate));
      const noteDetails=document.createElement('div');noteDetails.className='piano-note-details';noteDetails.id='pianoNoteDetails';noteDetails.innerHTML='<span id="pianoSelectionLabel">Select a note to fine-tune</span>';
      for(const [key,label,min,max,step] of [['pitch','Pitch',0,127,1],['start','Start · beats',0,15.95,.0625],['duration','Length · beats',.0625,16,.0625],['velocity','Velocity · %',1,100,1]]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.type='number';input.min=min;input.max=max;input.step=step;input.id=`pianoNote-${key}`;input.setAttribute('aria-label',`Selected note ${label}`);input.disabled=true;field.append(input);noteDetails.append(field);input.addEventListener('change',()=>{const notes=selectedNoteList();if(!notes.length||!Number.isFinite(input.valueAsNumber))return;const before=JSON.stringify(project),value=clamp(input.valueAsNumber,min,max);notes.forEach(n=>{n[key]=key==='velocity'?value/100:value;n.start=clamp(n.start,0,16-.0625);n.duration=clamp(n.duration,.0625,16-n.start);});commitNoteEdit(before);});}
      $('#noteToolbar').append(pianoTools,noteDetails);
      function pianoUpdateDetails(){const notes=selectedNoteList(),note=notes[0];$('#pianoSelectionLabel').textContent=notes.length===1?pitchName(note.pitch):notes.length?`${notes.length} notes selected`:'Select a note to fine-tune';for(const key of ['pitch','start','duration','velocity']){const input=$(`#pianoNote-${key}`);input.disabled=!note||(notes.length>1&&['pitch','start'].includes(key));if(document.activeElement!==input)input.value=note?Number((key==='velocity'?(note.velocity??.78)*100:note[key]).toFixed(3)):'';}}
      const pianoBaseControls=updateNoteControls;updateNoteControls=function(){pianoBaseControls();pianoUpdateDetails();};
      $('.studio-tag').textContent='STUDIO 4';studioRenderBrowser();
