      // Sonora 3 instruments and editor. All edits use the original project/history.
      const PRO_SYNTH = { waveform2:'sine', mix2:0, octave2:0, detune2:7, sub:0, noise:0, width:.45, fmAmount:0, fmRatio:2, filterEnv:0, filterDecay:.3, velocityFilter:.2, velocityCurve:1, keyTrack:.25, drive:0, lfoRate:1.5, lfoFilter:0, vibrato:0 };
      const PRO_SPECS = { octave2:[-2,2,1],mix2:[0,1,.01],detune2:[-100,100,1],sub:[0,.8,.01],noise:[0,.3,.005],width:[0,1,.01],fmAmount:[0,2,.01],fmRatio:[.5,8,.5],filterEnv:[-4,4,.1],filterDecay:[.02,2,.01],velocityFilter:[0,1,.01],velocityCurve:[.5,2,.05],keyTrack:[0,1,.01],drive:[0,1,.01],lfoRate:[.1,12,.1],lfoFilter:[0,2,.01],vibrato:[0,60,1] };
      const proNoiseBuffers = new WeakMap();
      const proPatchKey='sonora-user-patches-v1',proFavoriteKey='sonora-favorite-sounds-v1';
      let proPatches=[],proFavorites=new Set(),proLibraryMode='All';
      try { proPatches=JSON.parse(localStorage.getItem(proPatchKey)||'[]').filter(p=>p&&typeof p.name==='string'&&['synth','drums'].includes(p.kind)).slice(0,100);proFavorites=new Set(JSON.parse(localStorage.getItem(proFavoriteKey)||'[]')); } catch(_) {}
      const proRoll={zoom:1,root:0,scale:'minor',lock:false,ghosts:false,keyboard:false,scrollX:0,scrollY:null,clipId:null};
      const proScales={off:[],minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],pentatonic:[0,3,5,7,10],dorian:[0,2,3,5,7,9,10]};
      function proSynth(track) {
        const s={...DEFAULT_SYNTH,...PRO_SYNTH,...track.synth};
        for(const [key,[min,max]] of Object.entries(PRO_SPECS))s[key]=clamp(finiteNumber(s[key],PRO_SYNTH[key]),min,max);
        for(const key of ['waveform','waveform2'])if(!['sine','triangle','square','sawtooth'].includes(s[key]))s[key]='sine';
        s.octave=clamp(Math.round(finiteNumber(s.octave,0)),-2,2);s.octave2=Math.round(s.octave2);
        s.voices=clamp(Math.round(finiteNumber(s.voices,1)),1,5);s.detune=clamp(finiteNumber(s.detune,0),-100,100);s.spread=clamp(finiteNumber(s.spread,9),0,40);
        s.attack=clamp(finiteNumber(s.attack,.012),.002,2);s.decay=clamp(finiteNumber(s.decay,.16),.002,2);s.sustain=clamp(finiteNumber(s.sustain,.72),0,1);s.release=clamp(finiteNumber(s.release,.24),.01,3);
        s.cutoff=clamp(finiteNumber(s.cutoff,12000),120,18000);s.resonance=clamp(finiteNumber(s.resonance,.7),.1,12);
        if(!['lowpass','highpass','bandpass'].includes(s.filterType))s.filterType='lowpass';
        return s;
      }
      // Give the existing key presets distinct harmonic structures.
      const proPresetTone={ 'Glass Keys':{fmAmount:.28,fmRatio:2,velocityFilter:.4},'Warm EP':{fmAmount:.42,fmRatio:1,velocityFilter:.45},'Marimba':{fmAmount:.18,fmRatio:3},'Dream Bell':{fmAmount:.72,fmRatio:3.5},'Celesta':{fmAmount:.32,fmRatio:4},'Ensemble':{waveform2:'triangle',mix2:.22,width:.85},'Choir Pad':{waveform2:'sine',mix2:.32,lfoFilter:.18,lfoRate:.4},'Fat Saw':{sub:.16,width:.85},'Acid Bass':{filterEnv:2.8,filterDecay:.2,velocityFilter:.6},'Dark Drone':{noise:.045,lfoRate:.25,lfoFilter:.5},'Air Noise Lead':{noise:.09} };
      SYNTH_PRESETS.forEach(p=>p.synth={...PRO_SYNTH,...p.synth,...proPresetTone[p.name]});
      const proProductionPresets=[
        ['Electric Tines','Keys','Dynamic FM electric piano',{waveform:'sine',waveform2:'triangle',mix2:.15,fmAmount:.64,fmRatio:1,attack:.003,decay:.9,sustain:.1,release:.3,cutoff:7000,velocityFilter:.75,velocityCurve:1.25,width:.25}],
        ['Velvet Rhodes','Keys','Warm sustained electric keys',{waveform:'sine',waveform2:'sine',mix2:.22,octave2:1,detune2:0,fmAmount:.32,fmRatio:1,attack:.007,decay:.8,sustain:.26,release:.38,cutoff:3800,drive:.18,velocityFilter:.65}],
        ['Vibraphone','Keys','Clear mallet with gentle vibrato',{waveform:'sine',fmAmount:.18,fmRatio:4,attack:.002,decay:1.3,sustain:.03,release:.65,cutoff:10000,lfoRate:5.2,vibrato:4,velocityCurve:1.2}],
        ['Drawbar Organ','Organ','Layered fundamental and octave',{waveform:'sine',waveform2:'triangle',mix2:.55,octave2:1,detune2:0,sub:.16,attack:.005,decay:.08,sustain:1,release:.09,cutoff:6200,velocityCurve:.6,drive:.12}],
        ['Analog Strings','Pads','Wide strings with a warm moving filter',{waveform:'sawtooth',waveform2:'triangle',mix2:.3,voices:4,spread:15,width:.8,cutoff:2600,attack:.38,decay:.6,sustain:.68,release:1.35,lfoRate:.28,lfoFilter:.16}],
        ['Luminous Pad','Pads','Airy layered pad with slow motion',{waveform:'triangle',waveform2:'sine',mix2:.45,octave2:1,voices:3,spread:10,width:.9,noise:.012,cutoff:5600,attack:.65,decay:1,sustain:.7,release:2,lfoRate:.18,lfoFilter:.22}],
        ['Analog Pluck','Plucks','Rounded transient with a moving low-pass',{waveform:'sawtooth',waveform2:'triangle',mix2:.25,voices:2,spread:4,cutoff:1200,resonance:1.6,filterEnv:2.3,filterDecay:.3,attack:.002,decay:.34,sustain:.04,release:.18,velocityFilter:.7}],
        ['House Stab','Plucks','Bright, short polyphonic chord sound',{waveform:'sawtooth',waveform2:'square',mix2:.28,octave2:1,voices:3,spread:7,cutoff:3100,filterEnv:1.2,filterDecay:.18,attack:.003,decay:.26,sustain:.12,release:.16,drive:.12}],
        ['Reese Bass','Bass','Detuned low saws with weight and saturation',{waveform:'sawtooth',waveform2:'sawtooth',mix2:.5,detune2:13,octave:-1,voices:2,spread:7,sub:.28,width:.3,cutoff:1400,attack:.008,decay:.25,sustain:.7,release:.12,drive:.24}],
        ['Round Bass','Bass','Stable sine foundation and gentle harmonics',{waveform:'sine',waveform2:'triangle',mix2:.22,octave:-1,detune2:0,width:0,cutoff:1300,attack:.005,decay:.3,sustain:.65,release:.12,drive:.12,velocityFilter:.25}],
        ['Copper Lead','Leads','Focused pulse lead with expressive dynamics',{waveform:'square',waveform2:'sawtooth',mix2:.22,voices:2,spread:4,width:.25,cutoff:2700,filterEnv:1.6,filterDecay:.34,attack:.008,decay:.3,sustain:.62,release:.22,velocityFilter:.7,vibrato:4,lfoRate:5}],
        ['Airscape','Textures','Soft noise and slowly shifting harmonics',{waveform:'triangle',waveform2:'sine',mix2:.45,octave2:1,voices:3,spread:14,width:1,noise:.075,cutoff:3200,attack:1,decay:1,sustain:.7,release:2.5,lfoRate:.16,lfoFilter:.5}]
      ];
      proProductionPresets.forEach(([name,category,description,values])=>SYNTH_PRESETS.push({name,category,description,synth:{...DEFAULT_SYNTH,...PRO_SYNTH,...values}}));
      project.tracks.forEach(t=>{if(t.type==='synth')t.synth={...PRO_SYNTH,...proPresetTone[t.instrument],...t.synth};});
      function proNoise(ctx) { if(proNoiseBuffers.has(ctx))return proNoiseBuffers.get(ctx);const b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;proNoiseBuffers.set(ctx,b);return b; }
      const proDriveCurves=new Map();
      function proDriveCurve(amount){const key=Math.round(amount*100);if(proDriveCurves.has(key))return proDriveCurves.get(key);const curve=new Float32Array(1024),drive=1+key*.07,normal=Math.tanh(drive);for(let i=0;i<curve.length;i++)curve[i]=Math.tanh((i/(curve.length-1)*2-1)*drive)/normal;proDriveCurves.set(key,curve);return curve;}
      function proVoice(ctx,output,track,note,time,duration,live=true) {
        if(!ctx||!output)return null;
        const s=proSynth(track),held=duration===null,velocity=Math.pow(clamp(finiteNumber(note.velocity,.78),.01,1),s.velocityCurve),frequency=noteFrequency(note.pitch+s.octave*12),sources=[],nodes=[];
        const add=node=>{nodes.push(node);return node;},source=node=>{sources.push(node);if(live)studioTrackSource(node);return node;};
        const filter=add(ctx.createBiquadFilter()),amp=add(ctx.createGain()),mix=add(ctx.createGain());filter.type=s.filterType;filter.Q.setValueAtTime(s.resonance,time);mix.gain.value=1/(1+s.mix2*.5+s.sub+s.noise);let input=mix;if(s.drive>0){const drive=add(ctx.createWaveShaper());drive.curve=proDriveCurve(s.drive);drive.oversample='2x';mix.connect(drive);drive.connect(filter);}else mix.connect(filter);
        const ceiling=Math.min(18000,ctx.sampleRate*.45),cutoff=clamp(s.cutoff*Math.pow(2,(velocity-1)*s.velocityFilter*3+(note.pitch-60)*s.keyTrack/12),80,ceiling);
        filter.frequency.setValueAtTime(clamp(cutoff*Math.pow(2,s.filterEnv),80,ceiling),time);filter.frequency.exponentialRampToValueAtTime(cutoff,time+s.filterDecay);
        filter.connect(amp);amp.connect(output);
        let endTime;
        if(held){const peak=velocity*.22;amp.gain.setValueAtTime(.0001,time);amp.gain.exponentialRampToValueAtTime(Math.max(.0001,peak),time+s.attack);amp.gain.exponentialRampToValueAtTime(Math.max(.0001,peak*s.sustain),time+s.attack+s.decay);}
        else endTime=scheduleAmpEnvelope(amp.gain,time,Math.max(.04,duration),velocity,s);
        const oscillators=[];
        function osc(wave,freq,detune,level,pan=0){const o=source(ctx.createOscillator()),gain=add(ctx.createGain()),panner=add(ctx.createStereoPanner());o.type=wave;o.frequency.setValueAtTime(freq,time);o.detune.setValueAtTime(detune,time);gain.gain.value=level;panner.pan.value=pan;o.connect(gain);gain.connect(panner);panner.connect(input);oscillators.push(o);return o;}
        if(track.sampleId){const buffer=importedInstrumentBuffers.get(track.sampleId);if(!buffer){nodes.forEach(n=>n.disconnect());return null;}const sample=source(ctx.createBufferSource());sample.buffer=buffer;sample.loop=held;sample.playbackRate.value=frequency/noteFrequency(finiteNumber(track.sampleRootPitch,60))*Math.pow(2,s.detune/1200);sample.connect(input);}
        else {
          const count=s.voices,secondary=s.mix2;
          for(let i=0;i<count;i++){const center=count===1?0:i/(count-1)*2-1,detune=s.detune+(i-(count-1)/2)*s.spread;osc(s.waveform,frequency,detune,(1-secondary*.5)/count,center*s.width);if(secondary>0)osc(s.waveform2,frequency*Math.pow(2,s.octave2),detune+s.detune2,secondary/count,-center*s.width);}
          if(s.sub>0)osc('sine',frequency/2,s.detune,s.sub);
          if(s.noise>0){const noise=source(ctx.createBufferSource()),gain=add(ctx.createGain());noise.buffer=proNoise(ctx);noise.loop=true;gain.gain.value=s.noise;noise.connect(gain);gain.connect(input);}
          if(s.fmAmount>0){const fm=source(ctx.createOscillator()),depth=add(ctx.createGain());fm.frequency.value=frequency*s.fmRatio;depth.gain.setValueAtTime(frequency*s.fmAmount,time);depth.gain.exponentialRampToValueAtTime(Math.max(.001,frequency*s.fmAmount*.08),time+s.decay);fm.connect(depth);oscillators.forEach(o=>depth.connect(o.frequency));}
        }
        if(s.lfoFilter>0||s.vibrato>0){const lfo=source(ctx.createOscillator());lfo.frequency.value=s.lfoRate;if(s.lfoFilter>0){const g=add(ctx.createGain());g.gain.value=s.lfoFilter*1200;lfo.connect(g);g.connect(filter.detune);}if(s.vibrato>0){const g=add(ctx.createGain());g.gain.value=s.vibrato;lfo.connect(g);oscillators.forEach(o=>g.connect(o.detune));}}
        let ended=0,released=false;sources.forEach(src=>{src.addEventListener('ended',()=>{src.disconnect();if(++ended===sources.length)nodes.forEach(n=>{try{n.disconnect();}catch(_){}});},{once:true});src.start(time);if(!held)src.stop(endTime+.035);});
        return ()=>{if(released)return;released=true;const now=ctx.currentTime;try{if(amp.gain.cancelAndHoldAtTime)amp.gain.cancelAndHoldAtTime(now);else{amp.gain.cancelScheduledValues(now);amp.gain.setValueAtTime(Math.max(.0001,amp.gain.value),now);}amp.gain.exponentialRampToValueAtTime(.0001,now+s.release);sources.forEach(src=>{try{src.stop(now+s.release+.035);}catch(_){}});}catch(_){};};
      }
      playNote=function(track,note,time,duration){if(!audio.context)return;if(track.sampleId&&!importedInstrumentBuffers.has(track.sampleId)){ensureImportedInstrument(track).then(()=>{if(audio.context&&importedInstrumentBuffers.has(track.sampleId))proVoice(audio.context,audio.trackNodes.get(track.id),track,note,Math.max(time,audio.context.currentTime+.005),duration??note.duration*60/project.tempo);});return;}proVoice(audio.context,audio.trackNodes.get(track.id),track,note,time,duration??note.duration*60/project.tempo);};
      startHeldNote=function(track,note,velocity,time=audio.context?.currentTime||0){return proVoice(audio.context,audio.trackNodes.get(track.id)||audio.master,track,{...note,velocity},time,null)||(()=>{});};
      const proOpenHats=new WeakMap();
      function proDrumVoice(ctx,output,track,kind,time,velocity=.8,live=true){
        if(!ctx||!output)return;
        const kit=drumTimbreFor(track.drumKit||track.instrument),p=track.drumParams?.[kind]||{},tune=Math.pow(2,clamp(finiteNumber(p.tune,0),-12,12)/12),decay=clamp(finiteNumber(p.decay,1),.25,3),volume=clamp(finiteNumber(p.level,1),0,1.5),touch=Math.pow(clamp(velocity,.01,1),1.15),tone=clamp(finiteNumber(p.tone,.65),0,1),nodes=[],sources=[];
        const node=n=>(nodes.push(n),n),amp=node(ctx.createGain()),filter=node(ctx.createBiquadFilter()),pan=node(ctx.createStereoPanner());amp.gain.value=volume;filter.type='lowpass';filter.frequency.value=Math.min(ctx.sampleRate*.44,1100+Math.pow(tone,.65)*18000);filter.Q.value=.5;pan.pan.value=clamp(finiteNumber(p.pan,0),-1,1);amp.connect(filter);filter.connect(pan);pan.connect(output);
        let end=time+.1;
        function envelope(source,length,level,start=time,attack=.002){const gain=node(ctx.createGain());gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,level*touch),start+attack);gain.gain.exponentialRampToValueAtTime(.0001,start+Math.max(attack+.002,length));source.connect(gain);gain.connect(amp);sources.push({source,start,end:start+length+.02});end=Math.max(end,start+length+.02);return gain;}
        function oscillator(wave,frequency){const source=ctx.createOscillator();source.type=wave;source.frequency.value=Math.min(ctx.sampleRate*.4,frequency);return source;}
        function noise(frequency,type='highpass'){const source=ctx.createBufferSource(),f=node(ctx.createBiquadFilter());source.buffer=proNoise(ctx);source.loop=true;f.type=type;f.frequency.value=clamp(frequency,80,ctx.sampleRate*.42);f.Q.value=type==='bandpass'?.8:.6;source.connect(f);return {source,filter:f};}
        if(kind==='kick'||kind==='tom'){
          const kick=kind==='kick',tail=(kick?kit.kickDecay:.24)*decay,source=oscillator('sine',(kick?kit.kickStart:kit.tomStart)*tune);source.frequency.setValueAtTime((kick?kit.kickStart:kit.tomStart)*tune,time);source.frequency.exponentialRampToValueAtTime((kick?kit.kickEnd:kit.tomEnd)*tune,time+Math.min(.18,tail));envelope(source,tail+(kick?.15:.12)*decay,kick?kit.kickLevel:.45,time,.003);
          const transient=noise(kick?2600:1700);const gain=envelope(transient.source,(kick?.014:.028),kick?.045+tone*.08:.045);transient.source.disconnect();transient.source.connect(transient.filter);transient.filter.connect(gain);
        }else if(kind==='snare'){
          const body=oscillator('triangle',185*tune);body.frequency.setValueAtTime(220*tune,time);body.frequency.exponentialRampToValueAtTime(140*tune,time+.065*decay);envelope(body,.11*decay,kit.snareLevel*.52);
          const wire=noise(kit.snare*tune*.72),gain=envelope(wire.source,kit.snareLength*decay,kit.snareLevel*.88);wire.source.disconnect();wire.source.connect(wire.filter);wire.filter.connect(gain);
        }else if(kind==='hat'||kind==='openHat'){
          const open=kind==='openHat',length=(open?kit.openHatLength:kit.hatLength)*decay,frequency=(open?kit.openHat:kit.hat)*tune;
          const hiss=noise(frequency*.7),gain=envelope(hiss.source,length,kit.hatLevel*.7);hiss.source.disconnect();hiss.source.connect(hiss.filter);hiss.filter.connect(gain);
          for(const ratio of [1,1.342,1.731,2.217]){const source=oscillator('square',frequency*.47*ratio),g=envelope(source,length*.85,kit.hatLevel*.09),metalFilter=node(ctx.createBiquadFilter());metalFilter.type='highpass';metalFilter.frequency.value=Math.min(ctx.sampleRate*.4,frequency*.62);source.disconnect();source.connect(metalFilter);metalFilter.connect(g);}
          let hats=proOpenHats.get(ctx);if(!hats){hats=new Map();proOpenHats.set(ctx,hats);}const previous=hats.get(track.id);if(previous&&previous.end>time&&previous.time<=time){try{if(previous.amp.gain.cancelAndHoldAtTime)previous.amp.gain.cancelAndHoldAtTime(time);else{previous.amp.gain.cancelScheduledValues(time);previous.amp.gain.setValueAtTime(previous.amp.gain.value,time);}previous.amp.gain.linearRampToValueAtTime(.0001,time+.012);previous.sources.forEach(({source})=>source.stop(time+.018));}catch(_){}}
          if(open)hats.set(track.id,{amp,sources,time,end});else hats.delete(track.id);
        }else if(kind==='rim'){
          [780,1730,2840].forEach((frequency,index)=>envelope(oscillator(index?'sine':'triangle',frequency*tune),(.032+index*.009)*decay,kit.hatLevel*(index?.3:.65)));
        }else{
          const clap=noise(kit.clap*tune,'bandpass'),gain=node(ctx.createGain()),length=kit.clapLength*decay;clap.filter.connect(gain);gain.connect(amp);gain.gain.setValueAtTime(.0001,time);[0,.017,.034].forEach(offset=>{gain.gain.setValueAtTime(.0001,time+offset);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,kit.snareLevel*touch),time+offset+.002);gain.gain.exponentialRampToValueAtTime(.0001,time+offset+.012);});gain.gain.setValueAtTime(Math.max(.0001,kit.snareLevel*.55*touch),time+.052);gain.gain.exponentialRampToValueAtTime(.0001,time+.052+length);sources.push({source:clap.source,start:time,end:time+.06+length});end=time+.06+length;
        }
        let ended=0;sources.forEach(({source,start,end})=>{if(live)studioTrackSource(source);source.addEventListener('ended',()=>{source.disconnect();if(++ended===sources.length){nodes.forEach(n=>n.disconnect());const hat=proOpenHats.get(ctx)?.get(track.id);if(hat?.amp===amp)proOpenHats.get(ctx).delete(track.id);}},{once:true});source.start(start);source.stop(end);});
      }
      playDrum=function(kind,time,velocity=.8,track=getTrack()){proDrumVoice(audio.context,audio.trackNodes.get(track.id)||audio.master,track,kind,time,velocity);};
      function proFormat(key,value){if(['cutoff'].includes(key))return value>=1000?`${(value/1000).toFixed(1)} kHz`:`${Math.round(value)} Hz`;if(['attack','decay','release','filterDecay'].includes(key))return value<1?`${Math.round(value*1000)} ms`:`${value.toFixed(2)} s`;if(key==='lfoRate')return `${value.toFixed(1)} Hz`;if(['mix2','sub','noise','width','sustain','velocityFilter','keyTrack','drive','tone','level'].includes(key))return `${Math.round(value*100)}%`;if(key==='pan')return Math.abs(value)<.01?'C':`${Math.round(Math.abs(value)*100)}${value<0?'L':'R'}`;if(key==='velocityCurve')return `${value.toFixed(2)}×`;if(['detune','detune2','spread','vibrato'].includes(key))return `${Math.round(value)} ct`;if(['octave','octave2','filterEnv','tune'].includes(key))return `${value>0?'+':''}${Number(value.toFixed(1))}`;return Number(value.toFixed(2)).toString();}
      function proModule(parent,number,title){const module=document.createElement('section');module.className='instrument-module';const heading=document.createElement('h3'),num=document.createElement('small');num.textContent=number;heading.append(num,document.createTextNode(title));module.append(heading);parent.append(module);return module;}
      function proSelect(parent,label,value,options,change){const select=document.createElement('select');select.setAttribute('aria-label',label);for(const [key,name] of options){const o=document.createElement('option');o.value=key;o.textContent=name;select.append(o);}select.value=value;select.addEventListener('change',()=>studioEdit(()=>change(select.value)));studioField(parent,label,select);return select;}
      function proSynthRange(parent,track,key,label,min,max,step){const s=track.synth;return studioRange(parent,label,s[key],min,max,step,v=>{s[key]=v;proUpdateScopes(track);},v=>proFormat(key,v));}
      function proScope(parent,kind){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('instrument-scope');svg.dataset.scope=kind;svg.setAttribute('viewBox','0 0 280 60');svg.setAttribute('aria-label',kind==='wave'?'Oscillator waveform':'Amplitude envelope');svg.innerHTML='<path class="scope-grid" d="M0 30H280 M70 0V60 M140 0V60 M210 0V60"/><path class="scope-line"/>';parent.append(svg);}
      function proUpdateScopes(track){const s=proSynth(track);document.querySelectorAll('[data-scope]').forEach(svg=>{let path='';if(svg.dataset.scope==='wave'){for(let x=0;x<=280;x++){const phase=x/280*4*Math.PI,wave=(w,p)=>w==='sine'?Math.sin(p):w==='triangle'?2/Math.PI*Math.asin(Math.sin(p)):w==='square'?(Math.sin(p)>=0?1:-1):2*((p/(Math.PI*2))%1)-1,y=wave(s.waveform,phase)*(1-s.mix2*.5)+s.mix2*wave(s.waveform2,phase*Math.pow(2,s.octave2));path+=`${x?'L':'M'}${x},${30-clamp(y,-1.5,1.5)*17} `;}}else{const total=s.attack+s.decay+.6+s.release,x1=10+s.attack/total*260,x2=x1+s.decay/total*260,x3=x2+.6/total*260,y=54-s.sustain*45;path=`M10 54 L${x1} 9 L${x2} ${y} L${x3} ${y} L270 54`;}svg.querySelector('.scope-line').setAttribute('d',path);});}
      async function proAudition(track=getTrack(),chord=false){await audioReady();if(track.type==='drums'){['kick','snare','hat'].forEach((kind,i)=>playDrum(kind,audio.context.currentTime+.01+i*.17,.8,track));return;}if(track.type==='audio')return;await ensureImportedInstrument(track);const root=track.instrument.toLowerCase().includes('bass')?48:60;(chord?[0,3,7]:[0]).forEach(p=>playNote(track,{pitch:root+p,velocity:.78,duration:1},audio.context.currentTime+.01,chord?.65:.4));}
      function proRenderInstrument(track){
        const root=document.createElement('div');root.className='instrument-editor';const top=document.createElement('div');top.className='instrument-top';const title=document.createElement('div');title.innerHTML='<div class="instrument-eyebrow">SONORA / SOUND DESIGN</div><h2></h2><p></p>';title.querySelector('h2').textContent=track.instrument;title.querySelector('p').textContent=track.type==='drums'?'Tune every voice. Make the groove your own.':track.sampleId?'Your imported sample, shaped with envelopes and modulation.':'Layer, shape, and animate your sound. Saved with your project.';const actions=document.createElement('div');actions.className='instrument-actions';actions.append(studioButton('▷ Audition',()=>proAudition(track),'text-button pro-primary'),studioButton('Save patch',()=>proOpenPatch(track)),studioButton('Browse sounds',openSoundBrowser));top.append(title,actions);root.append(top);editorBodyEl.append(root);
        if(track.type==='audio'){const p=document.createElement('p');p.className='studio-note';p.textContent='Select an instrument or drum track to design a sound. Use Effects to process this audio track.';root.append(p);return;}
        const modules=document.createElement('div');modules.className='instrument-modules';root.append(modules);
        if(track.type==='drums'){modules.classList.add('pro-drum-modules');const kit=proModule(modules,'00','Drum kit');proSelect(kit,'Kit',track.drumKit||track.instrument,DRUM_KITS.map(p=>[p.name,p.name]),v=>{track.drumKit=v;track.instrument=v;});const reset=studioButton('Reset drum controls',()=>studioEdit(()=>delete track.drumParams));kit.append(reset);const names=['Kick','Snare','Closed hat','Open hat','Clap','Tom','Rim'];DRUM_LANES.forEach((kind,i)=>{const m=proModule(modules,String(i+1).padStart(2,'0'),names[i]);m.append(studioButton('▷ Hit',async()=>{await audioReady();playDrum(kind,audio.context.currentTime+.01,.85,track);},'text-button pro-drum-hit'));track.drumParams||={};track.drumParams[kind]={tune:0,decay:1,level:1,tone:.65,pan:0,...track.drumParams[kind]};const p=track.drumParams[kind];for(const [key,label,min,max,step] of [['tune',`${names[i]} tune`,-12,12,1],['decay',`${names[i]} decay`,.25,3,.05],['tone',`${names[i]} tone`,0,1,.01],['pan',`${names[i]} pan`,-1,1,.01],['level',`${names[i]} level`,0,1.5,.01]])studioRange(m,label,p[key],min,max,step,v=>p[key]=v,v=>key==='decay'?`${v.toFixed(2)}×`:proFormat(key,v));});const help=document.createElement('p');help.className='pro-module-help';help.textContent='Layered kick and snare voices, metallic hats, and a closed-hat choke. Tone and pan are saved for each drum.';kit.append(help);return;}
        track.synth=proSynth(track);const s=track.synth,waves=[['sine','Sine'],['triangle','Triangle'],['square','Pulse'],['sawtooth','Saw']];
        const a=proModule(modules,'01',track.sampleId?'Sample / pitch':'Oscillator / layers');proScope(a,'wave');
        if(track.sampleId)studioRange(a,'Sample root key',finiteNumber(track.sampleRootPitch,60),24,96,1,v=>track.sampleRootPitch=v,pitchName);else{proSelect(a,'Main waveform',s.waveform,waves,v=>{s.waveform=v;track.waveform=v;});proSelect(a,'Layer waveform',s.waveform2,waves,v=>s.waveform2=v);proSynthRange(a,track,'mix2','Layer mix',0,1,.01);proSynthRange(a,track,'octave2','Layer octave',-2,2,1);proSynthRange(a,track,'detune2','Layer detune',-100,100,1);proSynthRange(a,track,'sub','Sub oscillator',0,.8,.01);proSynthRange(a,track,'noise','Air / noise',0,.3,.005);}
        const b=proModule(modules,'02','Tone / filter');proSelect(b,'Filter mode',s.filterType,[['lowpass','Low pass'],['highpass','High pass'],['bandpass','Band pass']],v=>s.filterType=v);proSynthRange(b,track,'cutoff','Cutoff',120,18000,10);proSynthRange(b,track,'resonance','Resonance',.1,12,.1);proSynthRange(b,track,'filterEnv','Envelope depth',-4,4,.1);proSynthRange(b,track,'filterDecay','Filter decay',.02,2,.01);proSynthRange(b,track,'velocityFilter','Velocity → tone',0,1,.01);proSynthRange(b,track,'keyTrack','Keyboard → tone',0,1,.01);proSynthRange(b,track,'drive','Saturation',0,1,.01);
        const c=proModule(modules,'03','Amplitude envelope');proScope(c,'envelope');for(const [key,label,min,max,step] of [['attack','Attack',.002,2,.002],['decay','Decay',.002,2,.002],['sustain','Sustain',0,1,.01],['release','Release',.01,3,.01],['velocityCurve','Dynamic response',.5,2,.05]])proSynthRange(c,track,key,label,min,max,step);
        const d=proModule(modules,'04','Pitch / stereo');proSynthRange(d,track,'octave','Main octave',-2,2,1);proSynthRange(d,track,'detune','Fine tune',-100,100,1);if(!track.sampleId){proSynthRange(d,track,'voices','Unison voices',1,5,1);proSynthRange(d,track,'spread','Unison detune',0,40,1);proSynthRange(d,track,'width','Stereo width',0,1,.01);}
        const e=proModule(modules,'05','Motion / modulation');proSynthRange(e,track,'lfoRate','LFO rate',.1,12,.1);proSynthRange(e,track,'lfoFilter','Filter motion',0,2,.01);if(!track.sampleId){proSynthRange(e,track,'vibrato','Vibrato',0,60,1);proSynthRange(e,track,'fmAmount','FM amount',0,2,.01);proSynthRange(e,track,'fmRatio','FM ratio',.5,8,.5);}const help=document.createElement('p');help.className='pro-module-help';help.textContent='FM adds bell-like harmonics. LFO moves the filter over time. Audition after an edit to hear it.';e.append(help);
        const f=proModule(modules,'06','Make it yours');f.append(studioButton('▷ Play minor chord',()=>proAudition(track,true)),studioButton('Reset to preset',()=>{const preset=SYNTH_PRESETS.find(p=>p.name===track.instrument)||proPatches.find(p=>p.name===track.instrument&&p.kind==='synth');if(preset)studioEdit(()=>{track.synth=proSynth({synth:preset.synth});track.waveform=track.synth.waveform;});else notify('Choose a factory or saved patch first');}),studioButton('Open effects →',()=>{editorTab='fx';renderEditor();}));const hint=document.createElement('p');hint.className='pro-module-help';hint.textContent='Save your own patches to My sounds in the library. Instrument settings travel with downloaded projects.';f.append(hint);proUpdateScopes(track);
      }
      function proOpenPatch(track){if(track.sampleId){notify('Sample instruments are saved inside your project. Download the project to keep the audio.');return;}if(track.type==='audio')return;const dialog=$('#proPatchDialog');dialog.dataset.track=track.id;$('#proPatchName').value=`${track.instrument} variation`;dialog.showModal();$('#proPatchName').select();}
      function proSaveLibrary(){try{localStorage.setItem(proPatchKey,JSON.stringify(proPatches));localStorage.setItem(proFavoriteKey,JSON.stringify([...proFavorites]));}catch(_){notify('Device storage is full. Download your project to preserve the sound.');}}
      function proPresetList(){return [...SYNTH_PRESETS.map(p=>({...p,kind:'synth',key:`factory:${p.name}`})),...DRUM_KITS.map(p=>({...p,category:'Drums',kind:'drums',key:`factory:${p.name}`})),...proPatches.map(p=>({...p,category:p.kind==='drums'?'Drums':'Custom',description:'Your saved patch',key:p.id}))];}
      studioRenderBrowser=function(){const list=$('#studioPresetList');if(!list)return;list.replaceChildren();const query=$('#studioPresetSearch').value.toLowerCase(),track=getTrack(),colors={Keys:'#a6c9f9',Bass:'#bd9eff',Leads:'#c1f280',Pads:'#76d3c6',Plucks:'#f0bd87',Drums:'#f7958e',Textures:'#b1a4dd',Organ:'#e7c991',Custom:'#c1f280'};
        const matched=proPresetList().filter(p=>(studioPresetCategory==='All'||p.category===studioPresetCategory)&&(proLibraryMode!=='Favorites'||proFavorites.has(p.key))&&(proLibraryMode!=='My sounds'||p.id)&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query));
        for(const preset of matched){const row=document.createElement('div');row.className=`pro-preset-row${track.instrument===preset.name?' is-loaded':''}`;row.style.setProperty('--sound-color',colors[preset.category]||'#9bbaff');const button=studioButton('',()=>{let t=getTrack();if(preset.kind==='drums'&&t.type!=='drums'){addDrumTrack();t=getTrack();}if(preset.kind==='synth'&&t.type!=='synth'){addTrack();t=getTrack();}studioEdit(()=>{t.instrument=preset.name;if(preset.kind==='synth'){t.synth=proSynth({synth:preset.synth});t.waveform=t.synth.waveform;delete t.sampleId;}else{t.drumKit=preset.drumKit||preset.name;t.drumParams=clone(preset.drumParams||{});}});studioRenderBrowser();notify(`${preset.name} loaded`);},'preset-card');const symbol=document.createElement('span');symbol.className='preset-symbol';symbol.textContent=preset.kind==='drums'?'▦':preset.category==='Bass'?'≈':preset.category==='Pads'?'≋':'♮';const copy=document.createElement('span'),name=document.createElement('strong'),category=document.createElement('small');name.textContent=preset.name;category.textContent=preset.category;copy.append(name,category);button.append(symbol,copy);
          const preview=studioButton('▷',async()=>{const temporary={...getTrack(),type:preset.kind,instrument:preset.name,drumKit:preset.drumKit||preset.name,synth:preset.synth,drumParams:preset.drumParams,sampleId:undefined};preview.disabled=true;try{await proAudition(temporary);}finally{preview.disabled=false;}},'pro-preset-action');preview.setAttribute('aria-label',`Preview ${preset.name}`);preview.title=`Preview ${preset.name} without loading it`;
          const star=studioButton(proFavorites.has(preset.key)?'★':'☆',()=>{proFavorites.has(preset.key)?proFavorites.delete(preset.key):proFavorites.add(preset.key);proSaveLibrary();studioRenderBrowser();},`pro-preset-action${proFavorites.has(preset.key)?' is-favorite':''}`);star.title='Favorite sound';star.setAttribute('aria-label',`Favorite ${preset.name}`);star.setAttribute('aria-pressed',String(proFavorites.has(preset.key)));row.append(button,preview,star);list.append(row);}
        if(!matched.length){const empty=document.createElement('p');empty.className='studio-note';empty.textContent=proLibraryMode==='My sounds'?'Save a patch in the Instrument tab to build your collection.':proLibraryMode==='Favorites'?'Star a sound to keep it close.':'No sounds match your search.';list.append(empty);}
      };
      function proSnapPitch(pitch){if(!proRoll.lock||proRoll.scale==='off')return pitch;const scale=proScales[proRoll.scale];let best=pitch,distance=128;for(let p=Math.max(0,pitch-6);p<=Math.min(127,pitch+6);p++)if(scale.includes((p-proRoll.root+120)%12)&&Math.abs(p-pitch)<distance){best=p;distance=Math.abs(p-pitch);}return best;}
      function proVelocityBars(track,notes){const lane=$('#proVelocityLane');if(!lane)return;lane.replaceChildren();notes.forEach((note,index)=>{const bar=document.createElement('button');bar.type='button';bar.className=`pro-velocity-bar${selectedNotes.has(note)?' selected':''}`;bar.dataset.index=index;bar.style.left=`${note.start/16*100}%`;bar.style.height=`${Math.max(3,(note.velocity??.78)*49)}px`;bar.style.setProperty('--note-color',track.color);bar.title=`${pitchName(note.pitch)} · velocity ${Math.round(note.velocity*100)}%`;bar.setAttribute('aria-label',`${pitchName(note.pitch)} velocity`);bar.setAttribute('role','slider');bar.setAttribute('aria-valuemin','1');bar.setAttribute('aria-valuemax','100');bar.setAttribute('aria-valuenow',Math.round((note.velocity??.78)*100));
          let drag=null;bar.addEventListener('pointerdown',e=>{e.preventDefault();editFocus='notes';if(!selectedNotes.has(note)){if(!e.shiftKey)selectedNotes.clear();selectedNotes.add(note);audio.selectedNote=note;}drag={before:JSON.stringify(project),items:selectedNoteList().map(n=>({note:n,value:n.velocity??.78})),y:e.clientY,start:note.velocity??.78};bar.setPointerCapture(e.pointerId);renderNotes(track,notes,pianoBase(track),$('#noteLayer'),true);updateNoteControls();});
          bar.addEventListener('pointermove',e=>{if(!drag)return;const delta=(drag.y-e.clientY)/49;drag.items.forEach(i=>i.note.velocity=clamp(i.value+delta,.01,1));for(const b of lane.children){const n=notes[Number(b.dataset.index)];b.style.height=`${Math.max(3,n.velocity*49)}px`;b.setAttribute('aria-valuenow',Math.round(n.velocity*100));}renderNotes(track,notes,pianoBase(track),$('#noteLayer'),true);updateNoteControls();});
          function finish(cancel){if(!drag)return;const before=drag.before;if(cancel)drag.items.forEach(i=>i.note.velocity=i.value);drag=null;commitNoteEdit(before);}
          bar.addEventListener('pointerup',()=>finish(false));bar.addEventListener('pointercancel',()=>finish(true));bar.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const before=JSON.stringify(project);note.velocity=clamp((note.velocity??.78)+(e.key==='ArrowUp'?1:-1)*(e.shiftKey?.1:.01),.01,1);commitNoteEdit(before);});lane.append(bar);});}
      proRoll.rowHeight=20;
      function proRollReadout(track,notes){const readout=$('.pro-roll-readout');if(!readout)return;const selected=notes.filter(n=>selectedNotes.has(n));readout.textContent=selected.length===1?`${pitchName(selected[0].pitch)} · ${Number(selected[0].start.toFixed(3))} beats · length ${Number(selected[0].duration.toFixed(3))} · velocity ${Math.round((selected[0].velocity??.78)*100)}%`:selected.length?`${selected.length} notes selected · Shift + arrows: octave / beat`:`${notes.length} notes · C−1–G9 · 4-bar pattern`;
      }
      renderNotes=function(track,notes,base,layer,skipVelocity=false){if(!layer?.isConnected)return;layer.replaceChildren();if(proRoll.ghosts){project.tracks.filter(t=>t.id!==track.id&&t.type==='synth').forEach(t=>{const c=t.clips.find(c=>selectedClipFor(track)&&c.start<=selectedClipFor(track).start&&c.start+c.length>selectedClipFor(track).start);if(!c)return;(c.notes||[]).forEach(n=>{const ghost=document.createElement('div');ghost.className='pro-ghost-note';ghost.style.cssText=`left:${n.start/16*100}%;width:${n.duration/16*100}%;top:${(127-n.pitch)/128*100}%`;layer.append(ghost);});});}
        notes.forEach((note,index)=>{const element=document.createElement('div');element.className=`note${selectedNotes.has(note)?' selected':''}`;element.dataset.index=index;element.style.setProperty('--note-color',track.color);element.style.setProperty('--note-opacity',.55+(note.velocity??.78)*.45);element.style.left=`${note.start/16*100}%`;element.style.width=`${Math.max(note.duration/16*100,.15)}%`;element.style.top=`${(127-note.pitch)/128*100}%`;element.title=`${pitchName(note.pitch)} · ${Number(note.duration.toFixed(3))} beats · velocity ${Math.round((note.velocity??.78)*100)}%`;const name=document.createElement('span');name.textContent=pitchName(note.pitch);const leftHandle=document.createElement('span');leftHandle.className='note-handle-left';leftHandle.title='Drag to trim the note start';const handle=document.createElement('span');handle.className='note-handle';handle.title='Drag to change note length';element.append(leftHandle,name,handle);layer.append(element);});if(!skipVelocity)proVelocityBars(track,notes);proRollReadout(track,notes);
      };
      function proHumanize(){const chosen=selectedNoteList(),notes=chosen.length?chosen:notesForClip(getTrack());if(!notes.length)return;const before=JSON.stringify(project);notes.forEach(n=>{n.velocity=clamp((n.velocity??.78)+(Math.random()-.5)*.16,.12,1);n.start=clamp(n.start+(Math.random()-.5)*.035,0,16-n.duration);});commitNoteEdit(before);notify('Timing and velocity humanized · undo to restore');}
      function proLegato(){const chosen=selectedNoteList(),notes=chosen.length?chosen:notesForClip(getTrack());if(!notes.length)return;const before=JSON.stringify(project),starts=[...new Set(notes.map(n=>n.start))].sort((a,b)=>a-b);notes.forEach(n=>n.duration=Math.max(.05,(starts.find(s=>s>n.start+.001)??16)-n.start));commitNoteEdit(before);}
      function proRevealNote(note){const workspace=$('.piano-workspace'),roll=$('#pianoRoll');if(!workspace||!roll||!note)return;const top=(127-note.pitch)*proRoll.rowHeight,left=note.start/16*roll.clientWidth,right=(note.start+note.duration)/16*roll.clientWidth;if(top<workspace.scrollTop+20)workspace.scrollTop=Math.max(0,top-20);else if(top+proRoll.rowHeight>workspace.scrollTop+workspace.clientHeight-20)workspace.scrollTop=top+proRoll.rowHeight-workspace.clientHeight+20;if(left<workspace.scrollLeft)workspace.scrollLeft=left;else if(right>workspace.scrollLeft+workspace.clientWidth-58)workspace.scrollLeft=Math.max(0,right-workspace.clientWidth+58);proRoll.scrollY=workspace.scrollTop;proRoll.scrollX=workspace.scrollLeft;}
      nudgeNotes=function(beats,pitches){const chosen=selectedNoteList();if(!chosen.length)return;const before=JSON.stringify(project),dx=clamp(beats,-Math.min(...chosen.map(n=>n.start)),16-Math.max(...chosen.map(n=>n.start+n.duration))),dy=clamp(pitches,-Math.min(...chosen.map(n=>n.pitch)),127-Math.max(...chosen.map(n=>n.pitch)));chosen.forEach(note=>{note.start=Number((note.start+dx).toFixed(3));note.pitch=proSnapPitch(note.pitch+dy);});commitNoteEdit(before);const anchor=audio.selectedNote||chosen[0];proRevealNote(anchor);if(pitches)previewMovedNote(getTrack(),anchor);};
      renderPiano=function(track,clip=selectedClipFor(track)){
        const notes=notesForClip(track,clip);ensureNoteSelection(clip);let base=pianoBase(track),drag=null,scrollFrame=0,lastPointer=null;
        if(proRoll.clipId!==clip?.id){proRoll.clipId=clip?.id;proRoll.scrollX=0;proRoll.scrollY=null;}
        const piano=document.createElement('div');piano.className=`piano-editor${proRoll.keyboard?' show-keyboard':''}`;piano.style.setProperty('--row-height',`${proRoll.rowHeight}px`);
        const ruler=document.createElement('div');ruler.className='pro-roll-ruler';ruler.setAttribute('role','group');ruler.setAttribute('aria-label','Piano roll timeline · drag to move the playhead');const rulerInner=document.createElement('div');rulerInner.className='pro-roll-ruler-inner';for(let beat=0;beat<16;beat++){const span=document.createElement('span');span.textContent=beat%4===0?String(beat/4+1).padStart(2,'0'):`· ${beat%4+1}`;rulerInner.append(span);}ruler.append(rulerInner);
        const workspace=document.createElement('div');workspace.className='piano-workspace';workspace.setAttribute('aria-label','Scrollable piano roll. All 128 MIDI pitches.');const content=document.createElement('div');content.className='pro-roll-content';const labels=document.createElement('div');labels.className='piano-labels';const roll=document.createElement('div');roll.id='pianoRoll';roll.className=`piano-roll ${noteTool}-mode`;roll.tabIndex=0;roll.setAttribute('aria-label','Piano roll. Draw and drag for note length. Drag notes to move. Drag either edge to resize. Alt drag to copy.');const grid=document.createElement('div');grid.className='piano-grid';for(let row=0;row<128;row++){const pitch=127-row,label=document.createElement('div');label.className='piano-label';label.dataset.pitch=pitch;label.title=`Audition ${pitchName(pitch)} · MIDI ${pitch}`;label.addEventListener('pointerdown',e=>{e.preventDefault();previewMovedNote(track,{pitch,velocity:.8,duration:.3});});labels.append(label);const cell=document.createElement('div');cell.className='piano-cell pro-pitch-row';cell.dataset.pitch=pitch;grid.append(cell);}
        const layer=document.createElement('div');layer.id='noteLayer';layer.style.cssText='position:absolute;inset:0';const playhead=document.createElement('div');playhead.className='pro-roll-playhead';playhead.setAttribute('aria-hidden','true');const playheadGrip=document.createElement('button');playheadGrip.type='button';playheadGrip.className='pro-roll-playhead-grip';playheadGrip.setAttribute('role','slider');playheadGrip.setAttribute('aria-label','Piano roll playhead');playheadGrip.setAttribute('aria-valuemin','0');playheadGrip.setAttribute('aria-valuemax','16');playheadGrip.setAttribute('aria-valuenow','0');playheadGrip.title='Drag to move the playhead · use arrow keys to step';ruler.append(playheadGrip);roll.append(grid,layer,playhead);content.append(labels,roll);workspace.append(content);
        const velocity=document.createElement('div');velocity.className='pro-velocity';velocity.innerHTML='<div class="pro-velocity-label">VELOCITY</div><div class="pro-velocity-scroll"><div class="pro-velocity-lane" id="proVelocityLane"></div></div>';const velocityScroll=velocity.querySelector('.pro-velocity-scroll');
        const footer=document.createElement('div');footer.className='pro-roll-footer';footer.innerHTML='<span class="pro-roll-readout"></span><span>Drag to draw · Alt drag to copy · Scroll pitches · Ctrl/Cmd + wheel to zoom</span>';footer.firstChild.textContent=clip?'4-bar pattern · repeats across longer clips':'Add a clip to start writing';
        piano.append(ruler,workspace,velocity,createPianoKeyboard(track,clip),footer);editorBodyEl.append(piano);
        function sync(){ruler.scrollLeft=workspace.scrollLeft;velocityScroll.scrollLeft=workspace.scrollLeft;proRoll.scrollX=workspace.scrollLeft;proRoll.scrollY=workspace.scrollTop;base=clamp(Math.round(127-(workspace.scrollTop+workspace.clientHeight/2)/proRoll.rowHeight)-12,0,104);track.rollBase=base;}
        function size(){const width=Math.max(640,workspace.clientWidth-58)*proRoll.zoom;piano.style.setProperty('--roll-width',`${width}px`);workspace.scrollLeft=proRoll.scrollX;sync();}
        function movePlayhead(clientX){const width=Math.max(640,workspace.clientWidth-58)*proRoll.zoom,rect=ruler.getBoundingClientRect(),visibleX=clientX-(rect.left+58-ruler.scrollLeft),snap=Number($('#snapSelect').value)||.0625,beat=clamp(Math.round(clamp(visibleX/width*16,0,16)/snap)*snap,0,16-snap),absolute=seekToBeat((clip?.start||0)+beat);playhead.style.left=`${beat/16*100}%`;playhead.hidden=false;playheadGrip.style.left=`${58+beat/16*width}px`;playheadGrip.setAttribute('aria-valuenow',String(beat));playheadGrip.setAttribute('aria-valuetext',`${Math.floor(beat/4)+1}:${Math.floor(beat%4)+1}`);return absolute;}
        function refresh(){for(let row=0;row<128;row++){const pitch=127-row,isBlack=[1,3,6,8,10].includes(pitch%12),root=pitch%12===proRoll.root;labels.children[row].className=`piano-label${isBlack?' black':''}${root?' root':''}${pitch%12===0?' octave':''}`;labels.children[row].textContent=pitchName(pitch);const cell=grid.children[row];cell.classList.toggle('black-key',isBlack);cell.classList.toggle('root-line',root);cell.classList.toggle('in-scale',proRoll.scale!=='off'&&proScales[proRoll.scale].includes((pitch-proRoll.root+120)%12));}renderNotes(track,notes,base,layer);updateNoteControls();}
        const initialScrollY=proRoll.scrollY,initialBase=base;workspace.addEventListener('scroll',sync);const observer=new ResizeObserver(size);observer.observe(workspace);const removal=new MutationObserver(()=>{if(!piano.isConnected){observer.disconnect();removal.disconnect();cancelAnimationFrame(scrollFrame);if(drag){finish(true);}}});removal.observe(editorBodyEl,{childList:true});size();refresh();
        const startingBeat=audio.playheadBeat-(clip?.start||0),startingPosition=((startingBeat%16)+16)%16;playhead.style.left=`${startingPosition/16*100}%`;playheadGrip.style.left=`${58+startingPosition/16*Math.max(640,workspace.clientWidth-58)*proRoll.zoom}px`;playhead.hidden=!clip||startingBeat<0||startingBeat>=clip.length;
        ruler.addEventListener('pointerdown',event=>{if(event.button!==0||!clip||event.target===playheadGrip)return;event.preventDefault();movePlayhead(event.clientX);ruler.setPointerCapture(event.pointerId);});
        ruler.addEventListener('pointermove',event=>{if(ruler.hasPointerCapture(event.pointerId))movePlayhead(event.clientX);});
        ruler.addEventListener('pointerup',event=>{if(ruler.hasPointerCapture(event.pointerId))ruler.releasePointerCapture(event.pointerId);});
        playheadGrip.addEventListener('pointerdown',event=>{if(event.button!==0||!clip)return;event.preventDefault();event.stopPropagation();movePlayhead(event.clientX);playheadGrip.setPointerCapture(event.pointerId);});
        playheadGrip.addEventListener('pointermove',event=>{if(playheadGrip.hasPointerCapture(event.pointerId))movePlayhead(event.clientX);});
        for(const target of [ruler,playheadGrip])target.addEventListener('pointerup',event=>{if(target.hasPointerCapture(event.pointerId))target.releasePointerCapture(event.pointerId);});
        playheadGrip.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)||!clip)return;event.preventDefault();event.stopPropagation();const step=Number($('#snapSelect').value)||.0625,current=Number(playheadGrip.getAttribute('aria-valuenow')),beat=clamp(event.key==='Home'?0:event.key==='End'?16-step:current+(event.key==='ArrowLeft'?-step:step),0,16-step),absolute=seekToBeat((clip.start||0)+beat),position=clamp(absolute-(clip.start||0),0,16-step);playhead.style.left=`${position/16*100}%`;playheadGrip.style.left=`${58+position/16*Math.max(640,workspace.clientWidth-58)*proRoll.zoom}px`;playhead.hidden=false;playheadGrip.setAttribute('aria-valuenow',String(position));playheadGrip.setAttribute('aria-valuetext',`${Math.floor(position/4)+1}:${Math.floor(position%4)+1}`);});
        workspace.scrollTop=initialScrollY===null?Math.max(0,(127-(initialBase+12))*proRoll.rowHeight-workspace.clientHeight/2):initialScrollY;sync();
        workspace.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();const previous=proRoll.zoom,position=(workspace.scrollLeft+e.clientX-workspace.getBoundingClientRect().left-58)/Math.max(640,workspace.clientWidth-58)/previous;proRoll.zoom=clamp(previous*(e.deltaY>0?.8:1.25),1,8);size();workspace.scrollLeft=Math.max(0,position*Math.max(640,workspace.clientWidth-58)*proRoll.zoom-(e.clientX-workspace.getBoundingClientRect().left-58));sync();$('#proRollZoom').textContent=`${Math.round(proRoll.zoom*100)}%`;}else if(e.altKey){e.preventDefault();workspace.scrollTop+=Math.sign(e.deltaY)*12*proRoll.rowHeight;sync();}},{passive:false});
        roll.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.pro-roll-playhead-grip'))return;e.preventDefault();editFocus='notes';roll.focus({preventScroll:true});if(!clip){notify('Add a clip before drawing notes');return;}const rect=roll.getBoundingClientRect(),snap=Number($('#snapSelect').value)||.0625,x=clamp((e.clientX-rect.left)/rect.width,0,.9999),y=clamp((e.clientY-rect.top)/rect.height,0,.9999);pianoCursor=clamp(Math.floor(x*16/snap)*snap,0,16-snap);const el=e.target.closest('.note');
          if(!el){if(noteTool==='erase')return;if(noteTool==='select'||e.shiftKey){const marquee=document.createElement('div');marquee.className='note-marquee';roll.append(marquee);const initial=e.shiftKey?new Set(selectedNotes):new Set();if(!e.shiftKey)selectedNotes.clear();drag={mode:'marquee',x:e.clientX,y:e.clientY,rect,initial,marquee};}else{const pitch=proSnapPitch(127-Math.floor(y*128)),existing=notes.find(n=>n.pitch===pitch&&n.start<=pianoCursor&&n.start+n.duration>pianoCursor);selectedNotes.clear();if(existing){selectedNotes.add(existing);audio.selectedNote=existing;redrawNotes();return;}const before=JSON.stringify(project),note={start:pianoCursor,pitch,duration:Math.min(Number($('#noteLength').value)||1,16-pianoCursor),velocity:Number($('#noteVelocity').value)/100||.78};notes.push(note);selectedNotes.add(note);audio.selectedNote=note;previewMovedNote(track,note);drag={mode:'draw',note,x:e.clientX,y:e.clientY,rect,before,anchor:pianoCursor,added:[note],changed:true,items:[{note,start:note.start,duration:note.duration,pitch:note.pitch}]};}}
          else{let note=notes[Number(el.dataset.index)];if(!note)return;if(noteTool==='erase'){const before=JSON.stringify(project);notes.splice(notes.indexOf(note),1);selectedNotes.delete(note);audio.selectedNote=null;commitNoteEdit(before);return;}if(e.shiftKey){selectedNotes.has(note)?selectedNotes.delete(note):selectedNotes.add(note);audio.selectedNote=selectedNoteList()[0]||null;redrawNotes();return;}if(!selectedNotes.has(note)){selectedNotes.clear();selectedNotes.add(note);}const before=JSON.stringify(project),originalSelection=new Set(selectedNotes),added=[];const edge=e.target.closest('.note-handle')?'resize':e.target.closest('.note-handle-left')?'resize-left':'move';if(e.altKey&&edge==='move'){selectedNotes.clear();for(const original of originalSelection){const copy=clone(original);notes.push(copy);added.push(copy);selectedNotes.add(copy);if(original===note)note=copy;}}audio.selectedNote=note;drag={mode:edge,note,x:e.clientX,y:e.clientY,rect,before,added,originalSelection,items:selectedNoteList().map(n=>({note:n,start:n.start,duration:n.duration,pitch:n.pitch})),changed:added.length>0};}
          Object.assign(drag,{scrollX:workspace.scrollLeft,scrollY:workspace.scrollTop});audio.drag=drag;roll.setPointerCapture(e.pointerId);redrawNotes();lastPointer={clientX:e.clientX,clientY:e.clientY};});
        function updateGesture(e){if(!drag)return;const rect=roll.getBoundingClientRect(),scrollX=workspace.scrollLeft-drag.scrollX,scrollY=workspace.scrollTop-drag.scrollY;if(drag.mode==='marquee'){const x=drag.x-drag.rect.left,y=drag.y-drag.rect.top,currentX=e.clientX-rect.left,currentY=e.clientY-rect.top,left=Math.min(x,currentX),right=Math.max(x,currentX),top=Math.min(y,currentY),bottom=Math.max(y,currentY);Object.assign(drag.marquee.style,{left:`${left}px`,top:`${top}px`,width:`${right-left}px`,height:`${bottom-top}px`});selectedNotes.clear();drag.initial.forEach(n=>selectedNotes.add(n));notes.forEach(n=>{const y=(127-n.pitch)*proRoll.rowHeight;if(n.start/16*rect.width<right&&(n.start+n.duration)/16*rect.width>left&&y<bottom&&y+proRoll.rowHeight>top)selectedNotes.add(n);});audio.selectedNote=selectedNoteList()[0]||null;redrawNotes();return;}const snap=Number($('#snapSelect').value),raw=(e.clientX-drag.x+scrollX)/drag.rect.width*16,dx=snap?Math.round(raw/snap)*snap:raw,items=drag.items;
          if(drag.mode==='draw'){if(Math.abs(e.clientX-drag.x+scrollX)>4){const quantum=snap||.0625,point=clamp((e.clientX-rect.left)/rect.width*16,0,16),start=point<drag.anchor?Math.floor(point/quantum)*quantum:drag.anchor,end=point<drag.anchor?drag.anchor+quantum:Math.max(drag.anchor+quantum,Math.ceil(point/quantum)*quantum);drag.note.start=start;drag.note.duration=clamp(end-start,quantum,16-start);}}
          else if(drag.mode==='resize'){const delta=clamp(dx,Math.max(...items.map(i=>(snap||.05)-i.duration)),16-Math.max(...items.map(i=>i.start+i.duration)));items.forEach(i=>i.note.duration=Number((i.duration+delta).toFixed(3)));}
          else if(drag.mode==='resize-left'){const delta=clamp(dx,-Math.min(...items.map(i=>i.start)),Math.min(...items.map(i=>i.duration-(snap||.05))));items.forEach(i=>{i.note.start=Number((i.start+delta).toFixed(3));i.note.duration=Number((i.duration-delta).toFixed(3));});}
          else{const delta=clamp(dx,-Math.min(...items.map(i=>i.start)),16-Math.max(...items.map(i=>i.start+i.duration))),rawPitch=-Math.round((e.clientY-drag.y+scrollY)/proRoll.rowHeight),dy=clamp(rawPitch,-Math.min(...items.map(i=>i.pitch)),127-Math.max(...items.map(i=>i.pitch)));items.forEach(i=>{i.note.start=Number((i.start+delta).toFixed(3));i.note.pitch=proSnapPitch(i.pitch+dy);});if(drag.lastPitch!==drag.note.pitch){previewMovedNote(track,drag.note);drag.lastPitch=drag.note.pitch;}}
          drag.changed=Boolean(drag.added?.length)||items.some(i=>i.note.start!==i.start||i.note.duration!==i.duration||i.note.pitch!==i.pitch);redrawNotes();refreshClipPreviews(track);
        }
        function autoScroll(){scrollFrame=0;if(!drag||!lastPointer||!piano.isConnected)return;const r=workspace.getBoundingClientRect(),margin=26,dx=lastPointer.clientX<r.left+58+margin?-12:lastPointer.clientX>r.right-margin?12:0,dy=lastPointer.clientY<r.top+margin?-12:lastPointer.clientY>r.bottom-margin?12:0;if(dx||dy){workspace.scrollLeft+=dx;workspace.scrollTop+=dy;sync();updateGesture(lastPointer);}scrollFrame=requestAnimationFrame(autoScroll);}
        roll.addEventListener('pointermove',e=>{if(!drag)return;lastPointer={clientX:e.clientX,clientY:e.clientY};updateGesture(e);if(!scrollFrame)scrollFrame=requestAnimationFrame(autoScroll);});
        function finish(cancel){cancelAnimationFrame(scrollFrame);scrollFrame=0;lastPointer=null;if(!drag)return;const done=drag;drag=null;if(audio.drag===done)audio.drag=null;if(done.mode==='marquee'){done.marquee.remove();redrawNotes();return;}if(cancel){done.items.forEach(i=>Object.assign(i.note,{start:i.start,duration:i.duration,pitch:i.pitch}));for(const note of done.added||[]){const index=notes.indexOf(note);if(index>=0)notes.splice(index,1);selectedNotes.delete(note);}if(done.originalSelection){selectedNotes.clear();done.originalSelection.forEach(n=>selectedNotes.add(n));}audio.selectedNote=selectedNoteList()[0]||null;redrawNotes();refreshClipPreviews(track);}else if(done.changed)commitNoteEdit(done.before);}
        roll.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){e.preventDefault();e.stopPropagation();finish(true);}else if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)&&selectedNotes.size){e.preventDefault();e.stopPropagation();const before=JSON.stringify(project),step=Number($('#snapSelect').value)||.25;selectedNoteList().forEach(n=>n.duration=clamp(n.duration+(e.key==='ArrowRight'?step:-step),.0625,16-n.start));commitNoteEdit(before);}});
        roll.addEventListener('pointerup',()=>finish(false));roll.addEventListener('pointercancel',()=>finish(true));roll.addEventListener('lostpointercapture',()=>finish(false));roll.addEventListener('contextmenu',e=>{e.preventDefault();const el=e.target.closest('.note');if(!el)return;const note=notes[Number(el.dataset.index)];if(!selectedNotes.has(note)){selectedNotes.clear();selectedNotes.add(note);}audio.selectedNote=note;editFocus='notes';redrawNotes();showContextMenu(e.clientX,e.clientY,[['Copy notes',copySelection],['Duplicate notes',duplicateSelectedNotes],['Quantize',quantizeNotes],['Humanize',proHumanize],['Legato',proLegato],['Delete notes',deleteSelectedNotes]]);});
      };
      const proBaseInspector=studioRenderInspector;studioRenderInspector=function(){proBaseInspector();const panel=$('#studioInspector'),track=getTrack();if(!panel||track.type==='audio')return;const card=document.createElement('div');card.className='pro-instrument-shortcut';const text=document.createElement('small');text.textContent=track.type==='drums'?'PER-VOICE TUNING · ENVELOPES':'LAYERS · FILTER · ENVELOPES · MOTION';card.append(text,studioButton('Open instrument designer →',()=>{editorTab='instrument';studioPrefs.editor=true;studioApplyPreferences();renderEditor();}));panel.insertBefore(card,panel.querySelector('.studio-field'));};
      const proBaseEditor=renderEditor;renderEditor=function(){if(editorTab!=='instrument'){proBaseEditor();}else{editorBodyEl.replaceChildren();$('#noteToolbar').style.display='none';$('#noteLength').style.display='none';$('#clearPatternButton').style.display='none';document.querySelectorAll('.editor-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===editorTab));$('#editorTrackName').textContent=getTrack().name;proRenderInstrument(getTrack());studioRenderInspector();updateStatus();}const rollControls=$('#proRollControls');if(rollControls)rollControls.hidden=editorTab!=='piano'||getTrack().type!=='synth';studioRenderBrowser();};
      const proBaseMeter=renderMixerMeters;renderMixerMeters=function(){proBaseMeter();const line=$('.pro-roll-playhead'),grip=$('.pro-roll-playhead-grip'),clip=selectedClipFor();if(!line||!grip)return;const relative=audio.playheadBeat-(clip?.start||0),position=((relative%16)+16)%16,visible=Boolean(clip)&&relative>=0&&relative<clip.length;line.hidden=!visible;if(visible)line.style.left=`${position/16*100}%`;const workspace=$('.piano-workspace');if(workspace)grip.style.left=`${58+position/16*Math.max(640,workspace.clientWidth-58)*proRoll.zoom}px`;grip.setAttribute('aria-valuenow',String(position));grip.setAttribute('aria-valuetext',`${Math.floor(position/4)+1}:${Math.floor(position%4)+1}`);};
      const proBaseNormalize=normalizeProjectFile;normalizeProjectFile=function(raw){const next=proBaseNormalize(raw);next.tracks.forEach(t=>{if(t.type==='synth')t.synth=proSynth(t);if(t.type==='drums'){const params={};for(const kind of DRUM_LANES){const p=t.drumParams?.[kind];if(p)params[kind]={tune:clamp(finiteNumber(p.tune,0),-12,12),decay:clamp(finiteNumber(p.decay,1),.25,3),level:clamp(finiteNumber(p.level,1),0,1.5),tone:clamp(finiteNumber(p.tone,.65),0,1),pan:clamp(finiteNumber(p.pan,0),-1,1)};}t.drumParams=params;}});return next;};
      function proBuildUI(){
        const brand=$('.brand'),home=document.createElement('a');home.className=brand.className;home.href='../';home.setAttribute('aria-label','Sonora introduction');home.title='Back to Sonora';while(brand.firstChild)home.append(brand.firstChild);brand.replaceWith(home);home.querySelector('.brand-mark').innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.8" stroke-linecap="round" aria-hidden="true"><path d="M4 10v4M9 6v12M14 3v18M19 8v8"/></svg>';
        $('.studio-tag').textContent='STUDIO 3';$('.browser-title small').textContent='SOUND BANK';
        const modes=document.createElement('div');modes.className='browser-categories';modes.id='proLibraryModes';for(const name of ['All','Favorites','My sounds']){const b=studioButton(name,()=>{proLibraryMode=name;modes.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.textContent===name));studioRenderBrowser();},name==='All'?'active':'');modes.append(b);}$('#studioCategories').before(modes);
        const instrument=studioButton('Instrument',()=>{editorTab='instrument';renderEditor();},'editor-tab');instrument.dataset.tab='instrument';$('.editor-tabs').insertBefore(instrument,$('.editor-tab[data-tab="mixer"]'));
        const focus=studioButton('⤢',()=>{$('.app').classList.toggle('pro-focus');focus.setAttribute('aria-pressed',String($('.app').classList.contains('pro-focus')));focus.title=$('.app').classList.contains('pro-focus')?'Restore split workspace':'Expand editor';},'icon-button pro-focus-button');focus.setAttribute('aria-label','Expand editor');focus.setAttribute('aria-pressed','false');$('.editor-tools').append(focus);
        const extra=studioButton('Humanize',proHumanize);extra.id='proHumanize';$('#quantizeNotesButton').after(extra);const legato=studioButton('Legato',proLegato);extra.after(legato);
        const controls=document.createElement('div');controls.className='pro-roll-controls';controls.id='proRollControls';const root=document.createElement('select');root.setAttribute('aria-label','Scale root');['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'].forEach((n,i)=>{const o=document.createElement('option');o.value=i;o.textContent=n;root.append(o);});root.addEventListener('change',()=>{proRoll.root=Number(root.value);renderEditor();});
        const scale=document.createElement('select');scale.setAttribute('aria-label','Scale guide');for(const [v,n] of [['off','Chromatic'],['minor','Minor'],['major','Major'],['pentatonic','Pentatonic'],['dorian','Dorian']]){const o=document.createElement('option');o.value=v;o.textContent=n;scale.append(o);}scale.value=proRoll.scale;scale.addEventListener('change',()=>{proRoll.scale=scale.value;renderEditor();});controls.append(root,scale);
        for(const [key,label] of [['lock','Snap to scale'],['ghosts','Ghost notes']]){const l=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',label);check.addEventListener('change',()=>{proRoll[key]=check.checked;renderEditor();});l.append(check,document.createTextNode(key==='lock'?'Lock':'Ghosts'));controls.append(l);}
        const zoom=studioButton('100%',()=>{proRoll.zoom=proRoll.zoom>=8?1:proRoll.zoom*2;zoom.textContent=`${proRoll.zoom*100}%`;renderEditor();});zoom.id='proRollZoom';zoom.setAttribute('aria-label','Piano roll time zoom');zoom.title='Cycle time zoom · Ctrl/Cmd + wheel for smooth zoom';controls.append(zoom);
        const pitchSize=document.createElement('select');pitchSize.id='proPitchZoom';pitchSize.setAttribute('aria-label','Piano roll pitch size');for(const value of [12,16,20,26]){const option=document.createElement('option');option.value=value;option.textContent=`${value}px`;pitchSize.append(option);}pitchSize.value=proRoll.rowHeight;pitchSize.title='Pitch row height';pitchSize.addEventListener('change',()=>{const workspace=$('.piano-workspace'),height=workspace?.clientHeight||200,center=((workspace?.scrollTop||0)+height/2)/proRoll.rowHeight;proRoll.rowHeight=Number(pitchSize.value);proRoll.scrollY=Math.max(0,center*proRoll.rowHeight-height/2);renderEditor();});controls.append(pitchSize);
        controls.append(studioButton('Fit notes',()=>{const notes=notesForClip(getTrack()),workspace=$('.piano-workspace');if(notes.length){const low=Math.min(...notes.map(n=>n.pitch)),high=Math.max(...notes.map(n=>n.pitch)),available=workspace?.clientHeight||200;proRoll.rowHeight=[26,20,16,12].find(size=>(high-low+3)*size<=available)||12;pitchSize.value=proRoll.rowHeight;getTrack().rollBase=clamp(Math.round((low+high)/2)-12,0,104);proRoll.scrollY=Math.max(0,(127-(low+high)/2)*proRoll.rowHeight-available/2);}renderEditor();}),studioButton('Keyboard',()=>{proRoll.keyboard=!proRoll.keyboard;renderEditor();}));$('#noteToolbar').append(controls);
        for(const selector of ['#octaveDownButton','#octaveUpButton'])$(selector).addEventListener('click',()=>{proRoll.scrollY=null;},{capture:true});
        const patch=document.createElement('dialog');patch.id='proPatchDialog';patch.className='studio-dialog';patch.innerHTML='<h2>Keep this sound.</h2><p>Name your patch. It will appear in My sounds on this device.</p><form id="proPatchForm"><label class="studio-field">Patch name<input id="proPatchName" maxlength="48" required aria-label="Patch name" style="padding:10px;background:#111925;border:1px solid #475366;border-radius:6px;color:#e1e9f5;width:65%"></label><button type="submit" class="text-button pro-primary">Save patch</button></form>';patch.append(studioButton('×',()=>patch.close(),'icon-button dialog-close'));document.body.append(patch);
        $('#proPatchForm').addEventListener('submit',e=>{e.preventDefault();const track=project.tracks.find(t=>t.id===patch.dataset.track),name=$('#proPatchName').value.trim();if(!track||!name)return;if(proPatches.length>=100){notify('Your library supports up to 100 patches');return;}const p={id:`user:${Date.now()}`,name,kind:track.type,synth:track.type==='synth'?proSynth(track):undefined,drumKit:track.drumKit,drumParams:clone(track.drumParams||{})};proPatches.push(p);proSaveLibrary();studioEdit(()=>track.instrument=name);patch.close();studioRenderBrowser();notify(`${name} saved to My sounds`);});
        const help=$('#studioHelp');const p=document.createElement('p');p.textContent='Piano roll: scroll through all 128 MIDI pitches. Ctrl / Cmd + wheel zooms time, Alt + wheel scrolls an octave. Draw and drag for note length; either note edge trims its length; Alt + drag copies a selection. Shift selects multiple notes. Arrow keys move notes, Shift + arrows moves an octave or beat, and Alt + left/right changes length. Escape cancels an active drag. Drag velocity bars to edit dynamics. Scale Lock guides pitches. Use Fit notes or ⤢ to expand the editor.';help.append(p);
        $('#noteVelocity').addEventListener('input',()=>redrawNotes());studioRenderBrowser();
      }
      proBuildUI();
