      // Sonora 3 instruments and editor. All edits use the original project/history.
      const PRO_SYNTH = { waveform2:'sine', mix2:0, octave2:0, detune2:7, sub:0, noise:0, width:.45, fmAmount:0, fmRatio:2, filterEnv:0, filterDecay:.3, velocityFilter:.2, lfoRate:1.5, lfoFilter:0, vibrato:0 };
      const PRO_SPECS = { octave2:[-2,2,1],mix2:[0,1,.01],detune2:[-100,100,1],sub:[0,.8,.01],noise:[0,.3,.005],width:[0,1,.01],fmAmount:[0,2,.01],fmRatio:[.5,8,.5],filterEnv:[-4,4,.1],filterDecay:[.02,2,.01],velocityFilter:[0,1,.01],lfoRate:[.1,12,.1],lfoFilter:[0,2,.01],vibrato:[0,60,1] };
      const proNoiseBuffers = new WeakMap();
      const proPatchKey='sonora-user-patches-v1',proFavoriteKey='sonora-favorite-sounds-v1';
      let proPatches=[],proFavorites=new Set(),proLibraryMode='All';
      try { proPatches=JSON.parse(localStorage.getItem(proPatchKey)||'[]').filter(p=>p&&typeof p.name==='string'&&['synth','drums'].includes(p.kind)).slice(0,100);proFavorites=new Set(JSON.parse(localStorage.getItem(proFavoriteKey)||'[]')); } catch(_) {}
      const proRoll={zoom:1,root:0,scale:'minor',lock:false,ghosts:false,keyboard:false,scrollX:0,scrollY:null,clipId:null};
      const proScales={off:[],minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],pentatonic:[0,3,5,7,10],dorian:[0,2,3,5,7,9,10]};
      function proSynth(track) {
        const s={...DEFAULT_SYNTH,...PRO_SYNTH,...track.synth};
        for(const [key,[min,max]] of Object.entries(PRO_SPECS))s[key]=clamp(finiteNumber(s[key],PRO_SYNTH[key]),min,max);
        for(const key of ['waveform','waveform2'])if(!['sine','triangle','square','sawtooth'].includes(s[key]))s[key]='sine';
        s.octave=clamp(Math.round(finiteNumber(s.octave,0)),-2,2);s.octave2=Math.round(s.octave2);
        s.voices=clamp(Math.round(finiteNumber(s.voices,1)),1,5);s.detune=clamp(finiteNumber(s.detune,0),-100,100);s.spread=clamp(finiteNumber(s.spread,9),0,40);
        s.attack=clamp(finiteNumber(s.attack,.012),.002,2);s.decay=clamp(finiteNumber(s.decay,.16),.002,2);s.sustain=clamp(finiteNumber(s.sustain,.72),0,1);s.release=clamp(finiteNumber(s.release,.24),.01,3);
        s.cutoff=clamp(finiteNumber(s.cutoff,12000),120,18000);s.resonance=clamp(finiteNumber(s.resonance,.7),.1,12);
        if(!['lowpass','highpass','bandpass'].includes(s.filterType))s.filterType='lowpass';
        return s;
      }
      // Give the existing key presets distinct harmonic structures.
      const proPresetTone={ 'Glass Keys':{fmAmount:.28,fmRatio:2,velocityFilter:.4},'Warm EP':{fmAmount:.42,fmRatio:1,velocityFilter:.45},'Marimba':{fmAmount:.18,fmRatio:3},'Dream Bell':{fmAmount:.72,fmRatio:3.5},'Celesta':{fmAmount:.32,fmRatio:4},'Ensemble':{waveform2:'triangle',mix2:.22,width:.85},'Choir Pad':{waveform2:'sine',mix2:.32,lfoFilter:.18,lfoRate:.4},'Fat Saw':{sub:.16,width:.85},'Acid Bass':{filterEnv:2.8,filterDecay:.2,velocityFilter:.6},'Dark Drone':{noise:.045,lfoRate:.25,lfoFilter:.5},'Air Noise Lead':{noise:.09} };
      SYNTH_PRESETS.forEach(p=>p.synth={...PRO_SYNTH,...p.synth,...proPresetTone[p.name]});
      project.tracks.forEach(t=>{if(t.type==='synth')t.synth={...PRO_SYNTH,...proPresetTone[t.instrument],...t.synth};});
      function proNoise(ctx) { if(proNoiseBuffers.has(ctx))return proNoiseBuffers.get(ctx);const b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;proNoiseBuffers.set(ctx,b);return b; }
      function proVoice(ctx,output,track,note,time,duration,live=true) {
        if(!ctx||!output)return null;
        const s=proSynth(track),held=duration===null,velocity=clamp(finiteNumber(note.velocity,.78),.01,1),frequency=noteFrequency(note.pitch+s.octave*12),sources=[],nodes=[];
        const add=node=>{nodes.push(node);return node;},source=node=>{sources.push(node);if(live)studioTrackSource(node);return node;};
        const filter=add(ctx.createBiquadFilter()),amp=add(ctx.createGain());filter.type=s.filterType;filter.Q.setValueAtTime(s.resonance,time);
        const ceiling=Math.min(18000,ctx.sampleRate*.45),cutoff=clamp(s.cutoff*Math.pow(2,(velocity-1)*s.velocityFilter*3),80,ceiling);
        filter.frequency.setValueAtTime(clamp(cutoff*Math.pow(2,s.filterEnv),80,ceiling),time);filter.frequency.exponentialRampToValueAtTime(cutoff,time+s.filterDecay);
        filter.connect(amp);amp.connect(output);
        let endTime;
        if(held){const peak=velocity*.22;amp.gain.setValueAtTime(.0001,time);amp.gain.exponentialRampToValueAtTime(Math.max(.0001,peak),time+s.attack);amp.gain.exponentialRampToValueAtTime(Math.max(.0001,peak*s.sustain),time+s.attack+s.decay);}
        else endTime=scheduleAmpEnvelope(amp.gain,time,Math.max(.04,duration),velocity,s);
        const oscillators=[];
        function osc(wave,freq,detune,level,pan=0){const o=source(ctx.createOscillator()),gain=add(ctx.createGain()),panner=add(ctx.createStereoPanner());o.type=wave;o.frequency.setValueAtTime(freq,time);o.detune.setValueAtTime(detune,time);gain.gain.value=level;panner.pan.value=pan;o.connect(gain);gain.connect(panner);panner.connect(filter);oscillators.push(o);return o;}
        if(track.sampleId){const buffer=importedInstrumentBuffers.get(track.sampleId);if(!buffer){nodes.forEach(n=>n.disconnect());return null;}const sample=source(ctx.createBufferSource());sample.buffer=buffer;sample.loop=held;sample.playbackRate.value=frequency/noteFrequency(finiteNumber(track.sampleRootPitch,60))*Math.pow(2,s.detune/1200);sample.connect(filter);}
        else {
          const count=s.voices,secondary=s.mix2;
          for(let i=0;i<count;i++){const center=count===1?0:i/(count-1)*2-1,detune=s.detune+(i-(count-1)/2)*s.spread;osc(s.waveform,frequency,detune,(1-secondary*.5)/count,center*s.width);if(secondary>0)osc(s.waveform2,frequency*Math.pow(2,s.octave2),detune+s.detune2,secondary/count,-center*s.width);}
          if(s.sub>0)osc('sine',frequency/2,s.detune,s.sub);
          if(s.noise>0){const noise=source(ctx.createBufferSource()),gain=add(ctx.createGain());noise.buffer=proNoise(ctx);noise.loop=true;gain.gain.value=s.noise;noise.connect(gain);gain.connect(filter);}
          if(s.fmAmount>0){const fm=source(ctx.createOscillator()),depth=add(ctx.createGain());fm.frequency.value=frequency*s.fmRatio;depth.gain.setValueAtTime(frequency*s.fmAmount,time);depth.gain.exponentialRampToValueAtTime(Math.max(.001,frequency*s.fmAmount*.08),time+s.decay);fm.connect(depth);oscillators.forEach(o=>depth.connect(o.frequency));}
        }
        if(s.lfoFilter>0||s.vibrato>0){const lfo=source(ctx.createOscillator());lfo.frequency.value=s.lfoRate;if(s.lfoFilter>0){const g=add(ctx.createGain());g.gain.value=s.lfoFilter*1200;lfo.connect(g);g.connect(filter.detune);}if(s.vibrato>0){const g=add(ctx.createGain());g.gain.value=s.vibrato;lfo.connect(g);oscillators.forEach(o=>g.connect(o.detune));}}
        let ended=0,released=false;sources.forEach(src=>{src.addEventListener('ended',()=>{src.disconnect();if(++ended===sources.length)nodes.forEach(n=>{try{n.disconnect();}catch(_){}});},{once:true});src.start(time);if(!held)src.stop(endTime+.035);});
        return ()=>{if(released)return;released=true;const now=ctx.currentTime;try{if(amp.gain.cancelAndHoldAtTime)amp.gain.cancelAndHoldAtTime(now);else{amp.gain.cancelScheduledValues(now);amp.gain.setValueAtTime(Math.max(.0001,amp.gain.value),now);}amp.gain.exponentialRampToValueAtTime(.0001,now+s.release);sources.forEach(src=>{try{src.stop(now+s.release+.035);}catch(_){}});}catch(_){};};
      }
      playNote=function(track,note,time,duration){if(!audio.context)return;if(track.sampleId&&!importedInstrumentBuffers.has(track.sampleId)){ensureImportedInstrument(track).then(()=>{if(audio.context&&importedInstrumentBuffers.has(track.sampleId))proVoice(audio.context,audio.trackNodes.get(track.id),track,note,Math.max(time,audio.context.currentTime+.005),duration??note.duration*60/project.tempo);});return;}proVoice(audio.context,audio.trackNodes.get(track.id),track,note,time,duration??note.duration*60/project.tempo);};
      startHeldNote=function(track,note,velocity,time=audio.context?.currentTime||0){return proVoice(audio.context,audio.trackNodes.get(track.id)||audio.master,track,{...note,velocity},time,null)||(()=>{});};
      function proDrumVoice(ctx,output,track,kind,time,velocity=.8,live=true){
        if(!ctx||!output)return;
        const kit=drumTimbreFor(track.drumKit||track.instrument),p=track.drumParams?.[kind]||{},tune=Math.pow(2,clamp(finiteNumber(p.tune,0),-12,12)/12),decay=clamp(finiteNumber(p.decay,1),.25,3),volume=clamp(finiteNumber(p.level,1),0,1.5),gain=ctx.createGain();
        let src,filter,end;
        if(kind==='kick'||kind==='tom'){src=ctx.createOscillator();src.type='sine';const start=(kind==='kick'?kit.kickStart:kit.tomStart)*tune,tail=(kind==='kick'?kit.kickDecay:.18)*decay;src.frequency.setValueAtTime(start,time);src.frequency.exponentialRampToValueAtTime((kind==='kick'?kit.kickEnd:kit.tomEnd)*tune,time+tail);const level=(kind==='kick'?kit.kickLevel:.38)*velocity*volume;gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,level),time+.004);gain.gain.exponentialRampToValueAtTime(.0001,time+tail+.18*decay);end=time+tail+.2*decay;src.connect(gain);}
        else{src=ctx.createBufferSource();src.buffer=proNoise(ctx);filter=ctx.createBiquadFilter();filter.type=kind==='clap'?'bandpass':'highpass';filter.frequency.value=clamp((kit[kind]||kit.snare)*tune,120,ctx.sampleRate*.45);const length=(kind==='hat'?kit.hatLength:kind==='openHat'?kit.openHatLength:kind==='clap'?kit.clapLength:kind==='rim'?.045:kit.snareLength)*decay,level=(kind==='hat'||kind==='openHat'||kind==='rim'?kit.hatLevel:kit.snareLevel)*velocity*volume;
          gain.gain.setValueAtTime(.0001,time);if(kind==='clap'){[0,.018,.036].forEach(offset=>{gain.gain.setValueAtTime(.0001,time+offset);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,level),time+offset+.002);gain.gain.exponentialRampToValueAtTime(.0001,time+offset+.014);});gain.gain.setValueAtTime(Math.max(.0001,level*.5),time+.055);gain.gain.exponentialRampToValueAtTime(.0001,time+.055+length);}else{gain.gain.exponentialRampToValueAtTime(Math.max(.0001,level),time+.003);gain.gain.exponentialRampToValueAtTime(.0001,time+Math.max(.004,length));}end=time+length+.08;src.connect(filter);filter.connect(gain);}
        gain.connect(output);if(live)studioTrackSource(src);src.addEventListener('ended',()=>{src.disconnect();filter?.disconnect();gain.disconnect();},{once:true});src.start(time);src.stop(end);
      }
      playDrum=function(kind,time,velocity=.8,track=getTrack()){proDrumVoice(audio.context,audio.trackNodes.get(track.id)||audio.master,track,kind,time,velocity);};
      function proFormat(key,value){if(['cutoff'].includes(key))return value>=1000?`${(value/1000).toFixed(1)} kHz`:`${Math.round(value)} Hz`;if(['attack','decay','release','filterDecay'].includes(key))return value<1?`${Math.round(value*1000)} ms`:`${value.toFixed(2)} s`;if(key==='lfoRate')return `${value.toFixed(1)} Hz`;if(['mix2','sub','noise','width','sustain','velocityFilter','level'].includes(key))return `${Math.round(value*100)}%`;if(['detune','detune2','spread','vibrato'].includes(key))return `${Math.round(value)} ct`;if(['octave','octave2','filterEnv','tune'].includes(key))return `${value>0?'+':''}${Number(value.toFixed(1))}`;return Number(value.toFixed(2)).toString();}
      function proModule(parent,number,title){const module=document.createElement('section');module.className='instrument-module';const heading=document.createElement('h3'),num=document.createElement('small');num.textContent=number;heading.append(num,document.createTextNode(title));module.append(heading);parent.append(module);return module;}
      function proSelect(parent,label,value,options,change){const select=document.createElement('select');select.setAttribute('aria-label',label);for(const [key,name] of options){const o=document.createElement('option');o.value=key;o.textContent=name;select.append(o);}select.value=value;select.addEventListener('change',()=>studioEdit(()=>change(select.value)));studioField(parent,label,select);return select;}
      function proSynthRange(parent,track,key,label,min,max,step){const s=track.synth;return studioRange(parent,label,s[key],min,max,step,v=>{s[key]=v;proUpdateScopes(track);},v=>proFormat(key,v));}
      function proScope(parent,kind){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.classList.add('instrument-scope');svg.dataset.scope=kind;svg.setAttribute('viewBox','0 0 280 60');svg.setAttribute('aria-label',kind==='wave'?'Oscillator waveform':'Amplitude envelope');svg.innerHTML='<path class="scope-grid" d="M0 30H280 M70 0V60 M140 0V60 M210 0V60"/><path class="scope-line"/>';parent.append(svg);}
      function proUpdateScopes(track){const s=proSynth(track);document.querySelectorAll('[data-scope]').forEach(svg=>{let path='';if(svg.dataset.scope==='wave'){for(let x=0;x<=280;x++){const phase=x/280*4*Math.PI,wave=(w,p)=>w==='sine'?Math.sin(p):w==='triangle'?2/Math.PI*Math.asin(Math.sin(p)):w==='square'?(Math.sin(p)>=0?1:-1):2*((p/(Math.PI*2))%1)-1,y=wave(s.waveform,phase)*(1-s.mix2*.5)+s.mix2*wave(s.waveform2,phase*Math.pow(2,s.octave2));path+=`${x?'L':'M'}${x},${30-clamp(y,-1.5,1.5)*17} `;}}else{const total=s.attack+s.decay+.6+s.release,x1=10+s.attack/total*260,x2=x1+s.decay/total*260,x3=x2+.6/total*260,y=54-s.sustain*45;path=`M10 54 L${x1} 9 L${x2} ${y} L${x3} ${y} L270 54`;}svg.querySelector('.scope-line').setAttribute('d',path);});}
      async function proAudition(track=getTrack(),chord=false){await audioReady();if(track.type==='drums'){['kick','snare','hat'].forEach((kind,i)=>playDrum(kind,audio.context.currentTime+.01+i*.17,.8,track));return;}if(track.type==='audio')return;await ensureImportedInstrument(track);const root=track.instrument.toLowerCase().includes('bass')?48:60;(chord?[0,3,7]:[0]).forEach(p=>playNote(track,{pitch:root+p,velocity:.78,duration:1},audio.context.currentTime+.01,chord?.65:.4));}
      function proRenderInstrument(track){
        const root=document.createElement('div');root.className='instrument-editor';const top=document.createElement('div');top.className='instrument-top';const title=document.createElement('div');title.innerHTML='<div class="instrument-eyebrow">SONORA / SOUND DESIGN</div><h2></h2><p></p>';title.querySelector('h2').textContent=track.instrument;title.querySelector('p').textContent=track.type==='drums'?'Tune every voice. Make the groove your own.':track.sampleId?'Your imported sample, shaped with envelopes and modulation.':'Layer, shape, and animate your sound. Saved with your project.';const actions=document.createElement('div');actions.className='instrument-actions';actions.append(studioButton('▷ Audition',()=>proAudition(track),'text-button pro-primary'),studioButton('Save patch',()=>proOpenPatch(track)),studioButton('Browse sounds',openSoundBrowser));top.append(title,actions);root.append(top);editorBodyEl.append(root);
        if(track.type==='audio'){const p=document.createElement('p');p.className='studio-note';p.textContent='Select an instrument or drum track to design a sound. Use Effects to process this audio track.';root.append(p);return;}
        const modules=document.createElement('div');modules.className='instrument-modules';root.append(modules);
        if(track.type==='drums'){modules.classList.add('pro-drum-modules');const kit=proModule(modules,'00','Drum kit');proSelect(kit,'Kit',track.drumKit||track.instrument,DRUM_KITS.map(p=>[p.name,p.name]),v=>{track.drumKit=v;track.instrument=v;});const reset=studioButton('Reset drum controls',()=>studioEdit(()=>delete track.drumParams));kit.append(reset);const names=['Kick','Snare','Closed hat','Open hat','Clap','Tom','Rim'];DRUM_LANES.forEach((kind,i)=>{const m=proModule(modules,String(i+1).padStart(2,'0'),names[i]);m.append(studioButton('▷ Hit',async()=>{await audioReady();playDrum(kind,audio.context.currentTime+.01,.85,track);},'text-button pro-drum-hit'));track.drumParams||={};track.drumParams[kind]||={tune:0,decay:1,level:1};const p=track.drumParams[kind];for(const [key,label,min,max,step] of [['tune',`${names[i]} tune`,-12,12,1],['decay',`${names[i]} decay`,.25,3,.05],['level',`${names[i]} level`,0,1.5,.01]])studioRange(m,label,p[key],min,max,step,v=>p[key]=v,v=>key==='decay'?`${v.toFixed(2)}×`:proFormat(key,v));});return;}
        track.synth=proSynth(track);const s=track.synth,waves=[['sine','Sine'],['triangle','Triangle'],['square','Pulse'],['sawtooth','Saw']];
        const a=proModule(modules,'01',track.sampleId?'Sample / pitch':'Oscillator / layers');proScope(a,'wave');
        if(track.sampleId)studioRange(a,'Sample root key',finiteNumber(track.sampleRootPitch,60),24,96,1,v=>track.sampleRootPitch=v,pitchName);else{proSelect(a,'Main waveform',s.waveform,waves,v=>{s.waveform=v;track.waveform=v;});proSelect(a,'Layer waveform',s.waveform2,waves,v=>s.waveform2=v);proSynthRange(a,track,'mix2','Layer mix',0,1,.01);proSynthRange(a,track,'octave2','Layer octave',-2,2,1);proSynthRange(a,track,'detune2','Layer detune',-100,100,1);proSynthRange(a,track,'sub','Sub oscillator',0,.8,.01);proSynthRange(a,track,'noise','Air / noise',0,.3,.005);}
        const b=proModule(modules,'02','Tone / filter');proSelect(b,'Filter mode',s.filterType,[['lowpass','Low pass'],['highpass','High pass'],['bandpass','Band pass']],v=>s.filterType=v);proSynthRange(b,track,'cutoff','Cutoff',120,18000,10);proSynthRange(b,track,'resonance','Resonance',.1,12,.1);proSynthRange(b,track,'filterEnv','Envelope depth',-4,4,.1);proSynthRange(b,track,'filterDecay','Filter decay',.02,2,.01);proSynthRange(b,track,'velocityFilter','Velocity → tone',0,1,.01);
        const c=proModule(modules,'03','Amplitude envelope');proScope(c,'envelope');for(const [key,label,min,max,step] of [['attack','Attack',.002,2,.002],['decay','Decay',.002,2,.002],['sustain','Sustain',0,1,.01],['release','Release',.01,3,.01]])proSynthRange(c,track,key,label,min,max,step);
        const d=proModule(modules,'04','Pitch / stereo');proSynthRange(d,track,'octave','Main octave',-2,2,1);proSynthRange(d,track,'detune','Fine tune',-100,100,1);if(!track.sampleId){proSynthRange(d,track,'voices','Unison voices',1,5,1);proSynthRange(d,track,'spread','Unison detune',0,40,1);proSynthRange(d,track,'width','Stereo width',0,1,.01);}
        const e=proModule(modules,'05','Motion / modulation');proSynthRange(e,track,'lfoRate','LFO rate',.1,12,.1);proSynthRange(e,track,'lfoFilter','Filter motion',0,2,.01);if(!track.sampleId){proSynthRange(e,track,'vibrato','Vibrato',0,60,1);proSynthRange(e,track,'fmAmount','FM amount',0,2,.01);proSynthRange(e,track,'fmRatio','FM ratio',.5,8,.5);}const help=document.createElement('p');help.className='pro-module-help';help.textContent='FM adds bell-like harmonics. LFO moves the filter over time. Audition after an edit to hear it.';e.append(help);
        const f=proModule(modules,'06','Make it yours');f.append(studioButton('▷ Play minor chord',()=>proAudition(track,true)),studioButton('Reset to preset',()=>{const preset=SYNTH_PRESETS.find(p=>p.name===track.instrument)||proPatches.find(p=>p.name===track.instrument&&p.kind==='synth');if(preset)studioEdit(()=>{track.synth=proSynth({synth:preset.synth});track.waveform=track.synth.waveform;});else notify('Choose a factory or saved patch first');}),studioButton('Open effects →',()=>{editorTab='fx';renderEditor();}));const hint=document.createElement('p');hint.className='pro-module-help';hint.textContent='Save your own patches to My sounds in the library. Instrument settings travel with downloaded projects.';f.append(hint);proUpdateScopes(track);
      }
      function proOpenPatch(track){if(track.sampleId){notify('Sample instruments are saved inside your project. Download the project to keep the audio.');return;}if(track.type==='audio')return;const dialog=$('#proPatchDialog');dialog.dataset.track=track.id;$('#proPatchName').value=`${track.instrument} variation`;dialog.showModal();$('#proPatchName').select();}
      function proSaveLibrary(){try{localStorage.setItem(proPatchKey,JSON.stringify(proPatches));localStorage.setItem(proFavoriteKey,JSON.stringify([...proFavorites]));}catch(_){notify('Device storage is full. Download your project to preserve the sound.');}}
      function proPresetList(){return [...SYNTH_PRESETS.map(p=>({...p,kind:'synth',key:`factory:${p.name}`})),...DRUM_KITS.map(p=>({...p,category:'Drums',kind:'drums',key:`factory:${p.name}`})),...proPatches.map(p=>({...p,category:p.kind==='drums'?'Drums':'Custom',description:'Your saved patch',key:p.id}))];}
      studioRenderBrowser=function(){const list=$('#studioPresetList');if(!list)return;list.replaceChildren();const query=$('#studioPresetSearch').value.toLowerCase(),track=getTrack(),colors={Keys:'#a6c9f9',Bass:'#bd9eff',Leads:'#c1f280',Pads:'#76d3c6',Plucks:'#f0bd87',Drums:'#f7958e',Textures:'#b1a4dd',Organ:'#e7c991',Custom:'#c1f280'};
        const matched=proPresetList().filter(p=>(studioPresetCategory==='All'||p.category===studioPresetCategory)&&(proLibraryMode!=='Favorites'||proFavorites.has(p.key))&&(proLibraryMode!=='My sounds'||p.id)&&`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query));
        for(const preset of matched){const row=document.createElement('div');row.className=`pro-preset-row${track.instrument===preset.name?' is-loaded':''}`;row.style.setProperty('--sound-color',colors[preset.category]||'#9bbaff');const button=studioButton('',()=>{let t=getTrack();if(preset.kind==='drums'&&t.type!=='drums'){addDrumTrack();t=getTrack();}if(preset.kind==='synth'&&t.type!=='synth'){addTrack();t=getTrack();}studioEdit(()=>{t.instrument=preset.name;if(preset.kind==='synth'){t.synth=proSynth({synth:preset.synth});t.waveform=t.synth.waveform;delete t.sampleId;}else{t.drumKit=preset.drumKit||preset.name;t.drumParams=clone(preset.drumParams||{});}});studioRenderBrowser();notify(`${preset.name} loaded`);},'preset-card');const symbol=document.createElement('span');symbol.className='preset-symbol';symbol.textContent=preset.kind==='drums'?'▦':preset.category==='Bass'?'≈':preset.category==='Pads'?'≋':'♮';const copy=document.createElement('span'),name=document.createElement('strong'),category=document.createElement('small');name.textContent=preset.name;category.textContent=preset.category;copy.append(name,category);button.append(symbol,copy);
          const preview=studioButton('▷',async()=>{const temporary={...getTrack(),type:preset.kind,instrument:preset.name,drumKit:preset.drumKit||preset.name,synth:preset.synth,drumParams:preset.drumParams,sampleId:undefined};preview.disabled=true;try{await proAudition(temporary);}finally{preview.disabled=false;}},'pro-preset-action');preview.setAttribute('aria-label',`Preview ${preset.name}`);preview.title=`Preview ${preset.name} without loading it`;
          const star=studioButton(proFavorites.has(preset.key)?'★':'☆',()=>{proFavorites.has(preset.key)?proFavorites.delete(preset.key):proFavorites.add(preset.key);proSaveLibrary();studioRenderBrowser();},`pro-preset-action${proFavorites.has(preset.key)?' is-favorite':''}`);star.title='Favorite sound';star.setAttribute('aria-label',`Favorite ${preset.name}`);star.setAttribute('aria-pressed',String(proFavorites.has(preset.key)));row.append(button,preview,star);list.append(row);}
        if(!matched.length){const empty=document.createElement('p');empty.className='studio-note';empty.textContent=proLibraryMode==='My sounds'?'Save a patch in the Instrument tab to build your collection.':proLibraryMode==='Favorites'?'Star a sound to keep it close.':'No sounds match your search.';list.append(empty);}
      };
      function proSnapPitch(pitch){if(!proRoll.lock||proRoll.scale==='off')return pitch;const scale=proScales[proRoll.scale];let best=pitch,distance=128;for(let p=Math.max(0,pitch-6);p<=Math.min(127,pitch+6);p++)if(scale.includes((p-proRoll.root+120)%12)&&Math.abs(p-pitch)<distance){best=p;distance=Math.abs(p-pitch);}return best;}
      function proVelocityBars(track,notes){const lane=$('#proVelocityLane');if(!lane)return;lane.replaceChildren();notes.forEach((note,index)=>{const bar=document.createElement('button');bar.type='button';bar.className=`pro-velocity-bar${selectedNotes.has(note)?' selected':''}`;bar.dataset.index=index;bar.style.left=`${note.start/16*100}%`;bar.style.height=`${Math.max(3,(note.velocity??.78)*49)}px`;bar.style.setProperty('--note-color',track.color);bar.title=`${pitchName(note.pitch)} · velocity ${Math.round(note.velocity*100)}%`;bar.setAttribute('aria-label',`${pitchName(note.pitch)} velocity`);bar.setAttribute('role','slider');bar.setAttribute('aria-valuemin','1');bar.setAttribute('aria-valuemax','100');bar.setAttribute('aria-valuenow',Math.round((note.velocity??.78)*100));
          let drag=null;bar.addEventListener('pointerdown',e=>{e.preventDefault();editFocus='notes';if(!selectedNotes.has(note)){if(!e.shiftKey)selectedNotes.clear();selectedNotes.add(note);audio.selectedNote=note;}drag={before:JSON.stringify(project),items:selectedNoteList().map(n=>({note:n,value:n.velocity??.78})),y:e.clientY,start:note.velocity??.78};bar.setPointerCapture(e.pointerId);renderNotes(track,notes,pianoBase(track),$('#noteLayer'),true);updateNoteControls();});
          bar.addEventListener('pointermove',e=>{if(!drag)return;const delta=(drag.y-e.clientY)/49;drag.items.forEach(i=>i.note.velocity=clamp(i.value+delta,.01,1));for(const b of lane.children){const n=notes[Number(b.dataset.index)];b.style.height=`${Math.max(3,n.velocity*49)}px`;b.setAttribute('aria-valuenow',Math.round(n.velocity*100));}renderNotes(track,notes,pianoBase(track),$('#noteLayer'),true);updateNoteControls();});
          function finish(cancel){if(!drag)return;const before=drag.before;if(cancel)drag.items.forEach(i=>i.note.velocity=i.value);drag=null;commitNoteEdit(before);}
          bar.addEventListener('pointerup',()=>finish(false));bar.addEventListener('pointercancel',()=>finish(true));bar.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const before=JSON.stringify(project);note.velocity=clamp((note.velocity??.78)+(e.key==='ArrowUp'?1:-1)*(e.shiftKey?.1:.01),.01,1);commitNoteEdit(before);});lane.append(bar);});}
      renderNotes=function(track,notes,base,layer,skipVelocity=false){if(!layer?.isConnected)return;layer.replaceChildren();if(proRoll.ghosts){project.tracks.filter(t=>t.id!==track.id&&t.type==='synth').forEach(t=>{const c=t.clips.find(c=>selectedClipFor(track)&&c.start<=selectedClipFor(track).start&&c.start+c.length>selectedClipFor(track).start);if(!c)return;(c.notes||[]).forEach(n=>{if(n.pitch<base||n.pitch>=base+24)return;const ghost=document.createElement('div');ghost.className='pro-ghost-note';ghost.style.cssText=`left:${n.start/16*100}%;width:${n.duration/16*100}%;top:${(base+23-n.pitch)/24*100}%`;layer.append(ghost);});});}
        notes.forEach((note,index)=>{if(note.pitch<base||note.pitch>=base+24)return;const element=document.createElement('div');element.className=`note${selectedNotes.has(note)?' selected':''}`;element.dataset.index=index;element.style.setProperty('--note-color',track.color);element.style.setProperty('--note-opacity',.55+(note.velocity??.78)*.45);element.style.left=`${note.start/16*100}%`;element.style.width=`${Math.max(note.duration/16*100,.15)}%`;element.style.top=`${(base+23-note.pitch)/24*100}%`;element.title=`${pitchName(note.pitch)} · ${note.duration} beats · velocity ${Math.round((note.velocity??.78)*100)}%`;const name=document.createElement('span');name.textContent=pitchName(note.pitch);const handle=document.createElement('span');handle.className='note-handle';element.append(name,handle);layer.append(element);});if(!skipVelocity)proVelocityBars(track,notes);
      };
      function proHumanize(){const chosen=selectedNoteList(),notes=chosen.length?chosen:notesForClip(getTrack());if(!notes.length)return;const before=JSON.stringify(project);notes.forEach(n=>{n.velocity=clamp((n.velocity??.78)+(Math.random()-.5)*.16,.12,1);n.start=clamp(n.start+(Math.random()-.5)*.035,0,16-n.duration);});commitNoteEdit(before);notify('Timing and velocity humanized · undo to restore');}
      function proLegato(){const chosen=selectedNoteList(),notes=chosen.length?chosen:notesForClip(getTrack());if(!notes.length)return;const before=JSON.stringify(project),starts=[...new Set(notes.map(n=>n.start))].sort((a,b)=>a-b);notes.forEach(n=>n.duration=Math.max(.05,(starts.find(s=>s>n.start+.001)??16)-n.start));commitNoteEdit(before);}
      renderPiano=function(track,clip=selectedClipFor(track)){
        const notes=notesForClip(track,clip);ensureNoteSelection(clip);let base=pianoBase(track),drag=null;
        if(proRoll.clipId!==clip?.id){proRoll.clipId=clip?.id;proRoll.scrollX=0;proRoll.scrollY=null;}
        const piano=document.createElement('div');piano.className=`piano-editor${proRoll.keyboard?' show-keyboard':''}`;piano.style.setProperty('--row-height','20px');
        const ruler=document.createElement('div');ruler.className='pro-roll-ruler';const rulerInner=document.createElement('div');rulerInner.className='pro-roll-ruler-inner';for(let beat=0;beat<16;beat++){const span=document.createElement('span');span.textContent=beat%4===0?String(beat/4+1).padStart(2,'0'):`· ${beat%4+1}`;rulerInner.append(span);}ruler.append(rulerInner);
        const workspace=document.createElement('div');workspace.className='piano-workspace';const content=document.createElement('div');content.className='pro-roll-content';const labels=document.createElement('div');labels.className='piano-labels';const roll=document.createElement('div');roll.id='pianoRoll';roll.className=`piano-roll ${noteTool}-mode`;roll.tabIndex=0;roll.setAttribute('aria-label','Piano roll. Draw notes, drag to move, drag right edge to resize.');const grid=document.createElement('div');grid.className='piano-grid';for(let row=0;row<24;row++){const label=document.createElement('div');label.className='piano-label';label.addEventListener('pointerdown',e=>{e.preventDefault();previewMovedNote(track,{pitch:base+23-row,velocity:.8,duration:.3});});labels.append(label);for(let col=0;col<64;col++){const cell=document.createElement('div');cell.className=`piano-cell${col%16===0?' bar-line':col%4===0?' beat-line':''}`;grid.append(cell);}}
        const layer=document.createElement('div');layer.id='noteLayer';layer.style.cssText='position:absolute;inset:0';const playhead=document.createElement('div');playhead.className='pro-roll-playhead';roll.append(grid,layer,playhead);content.append(labels,roll);workspace.append(content);
        const velocity=document.createElement('div');velocity.className='pro-velocity';velocity.innerHTML='<div class="pro-velocity-label">VELOCITY</div><div class="pro-velocity-scroll"><div class="pro-velocity-lane" id="proVelocityLane"></div></div>';const velocityScroll=velocity.querySelector('.pro-velocity-scroll');
        const footer=document.createElement('div');footer.className='pro-roll-footer';footer.innerHTML='<span></span><span>Drag velocity bars · Shift to select · Ctrl + wheel to zoom</span>';footer.firstChild.textContent=clip?'4-bar pattern · repeats across longer clips':'Add a clip to start writing';
        piano.append(ruler,workspace,velocity,createPianoKeyboard(track,clip),footer);editorBodyEl.append(piano);
        function sync(){ruler.scrollLeft=workspace.scrollLeft;velocityScroll.scrollLeft=workspace.scrollLeft;proRoll.scrollX=workspace.scrollLeft;proRoll.scrollY=workspace.scrollTop;}
        function size(){const width=Math.max(640,workspace.clientWidth-58)*proRoll.zoom;piano.style.setProperty('--roll-width',`${width}px`);workspace.scrollLeft=proRoll.scrollX;sync();}
        function refresh(){track.rollBase=base;for(let row=0;row<24;row++){const pitch=base+23-row,isBlack=[1,3,6,8,10].includes(pitch%12),root=pitch%12===proRoll.root;labels.children[row].className=`piano-label${isBlack?' black':''}${root?' root':''}`;labels.children[row].textContent=pitchName(pitch);for(let col=0;col<64;col++){const cell=grid.children[row*64+col];cell.classList.toggle('black-key',isBlack);cell.classList.toggle('root-line',root);cell.classList.toggle('in-scale',proRoll.scale!=='off'&&proScales[proRoll.scale].includes((pitch-proRoll.root+120)%12));}}renderNotes(track,notes,base,layer);updateNoteControls();}
        const initialScrollY=proRoll.scrollY;workspace.addEventListener('scroll',sync);const observer=new ResizeObserver(size);observer.observe(workspace);const removal=new MutationObserver(()=>{if(!piano.isConnected){observer.disconnect();removal.disconnect();}});removal.observe(editorBodyEl,{childList:true});size();refresh();
        if(initialScrollY===null){const visible=notes.filter(n=>n.pitch>=base&&n.pitch<base+24),avg=visible.length?visible.reduce((s,n)=>s+n.pitch,0)/visible.length:base+12;workspace.scrollTop=Math.max(0,(base+23-avg)*20-workspace.clientHeight/2);}else workspace.scrollTop=initialScrollY;sync();
        roll.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();proRoll.zoom=clamp(proRoll.zoom*(e.deltaY>0?.8:1.25),1,4);size();$('#proRollZoom').textContent=`${Math.round(proRoll.zoom*100)}%`;}else if(e.altKey){e.preventDefault();base=clamp(base+(e.deltaY>0?-12:12),0,104);refresh();setDirty();}},{passive:false});
        roll.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();editFocus='notes';roll.focus({preventScroll:true});if(!clip){notify('Add a clip before drawing notes');return;}const rect=roll.getBoundingClientRect(),snap=Number($('#snapSelect').value)||.0625,x=clamp((e.clientX-rect.left)/rect.width,0,.9999),y=clamp((e.clientY-rect.top)/rect.height,0,.9999);pianoCursor=clamp(Math.floor(x*16/snap)*snap,0,16-snap);const el=e.target.closest('.note');
          if(!el){if(noteTool==='erase')return;if(noteTool==='select'||e.shiftKey){const marquee=document.createElement('div');marquee.className='note-marquee';roll.append(marquee);const initial=e.shiftKey?new Set(selectedNotes):new Set();if(!e.shiftKey)selectedNotes.clear();drag={mode:'marquee',x:e.clientX,y:e.clientY,rect,initial,marquee};}else{const pitch=proSnapPitch(base+23-Math.floor(y*24)),existing=notes.find(n=>n.pitch===pitch&&n.start<=pianoCursor&&n.start+n.duration>pianoCursor);selectedNotes.clear();if(existing){selectedNotes.add(existing);audio.selectedNote=existing;redrawNotes();return;}const before=JSON.stringify(project),note={start:pianoCursor,pitch,duration:Math.min(Number($('#noteLength').value)||1,16-pianoCursor),velocity:.78};notes.push(note);selectedNotes.add(note);audio.selectedNote=note;previewMovedNote(track,note);commitNoteEdit(before);return;}}
          else{const note=notes[Number(el.dataset.index)];if(noteTool==='erase'){const before=JSON.stringify(project);notes.splice(notes.indexOf(note),1);selectedNotes.delete(note);commitNoteEdit(before);return;}if(e.shiftKey){selectedNotes.has(note)?selectedNotes.delete(note):selectedNotes.add(note);audio.selectedNote=selectedNoteList()[0]||null;redrawNotes();return;}if(!selectedNotes.has(note)){selectedNotes.clear();selectedNotes.add(note);}audio.selectedNote=note;drag={mode:e.target.closest('.note-handle')?'resize':'move',note,x:e.clientX,y:e.clientY,rect,before:JSON.stringify(project),items:selectedNoteList().map(n=>({note:n,start:n.start,duration:n.duration,pitch:n.pitch})),changed:false};}
          audio.drag=drag;roll.setPointerCapture(e.pointerId);redrawNotes();});
        roll.addEventListener('pointermove',e=>{if(!drag)return;if(drag.mode==='marquee'){const left=Math.min(drag.x,e.clientX)-drag.rect.left,right=Math.max(drag.x,e.clientX)-drag.rect.left,top=Math.min(drag.y,e.clientY)-drag.rect.top,bottom=Math.max(drag.y,e.clientY)-drag.rect.top;Object.assign(drag.marquee.style,{left:`${left}px`,top:`${top}px`,width:`${right-left}px`,height:`${bottom-top}px`});selectedNotes.clear();drag.initial.forEach(n=>selectedNotes.add(n));notes.forEach(n=>{const y=(base+23-n.pitch)*20;if(n.start/16*drag.rect.width<right&&(n.start+n.duration)/16*drag.rect.width>left&&y<bottom&&y+20>top)selectedNotes.add(n);});audio.selectedNote=selectedNoteList()[0]||null;redrawNotes();return;}const snap=Number($('#snapSelect').value),raw=(e.clientX-drag.x)/drag.rect.width*16,dx=snap?Math.round(raw/snap)*snap:raw,items=drag.items;
          if(drag.mode==='resize'){const delta=clamp(dx,Math.max(...items.map(i=>(snap||.05)-i.duration)),16-Math.max(...items.map(i=>i.start+i.duration)));items.forEach(i=>i.note.duration=Number((i.duration+delta).toFixed(3)));}
          else{const delta=clamp(dx,-Math.min(...items.map(i=>i.start)),16-Math.max(...items.map(i=>i.start+i.duration))),rawPitch=-Math.round((e.clientY-drag.y)/20),dy=clamp(rawPitch,-Math.min(...items.map(i=>i.pitch)),127-Math.max(...items.map(i=>i.pitch)));items.forEach(i=>{i.note.start=Number((i.start+delta).toFixed(3));i.note.pitch=proSnapPitch(i.pitch+dy);});if(drag.lastPitch!==drag.note.pitch){previewMovedNote(track,drag.note);drag.lastPitch=drag.note.pitch;}}
          drag.changed=items.some(i=>i.note.start!==i.start||i.note.duration!==i.duration||i.note.pitch!==i.pitch);redrawNotes();refreshClipPreviews(track);});
        function finish(cancel){if(!drag)return;const done=drag;drag=null;audio.drag=null;if(done.mode==='marquee'){done.marquee.remove();redrawNotes();return;}if(cancel){done.items.forEach(i=>Object.assign(i.note,{start:i.start,duration:i.duration,pitch:i.pitch}));redrawNotes();}else if(done.changed)commitNoteEdit(done.before);}
        roll.addEventListener('pointerup',()=>finish(false));roll.addEventListener('pointercancel',()=>finish(true));roll.addEventListener('lostpointercapture',()=>finish(false));roll.addEventListener('contextmenu',e=>{e.preventDefault();const el=e.target.closest('.note');if(!el)return;const note=notes[Number(el.dataset.index)];if(!selectedNotes.has(note)){selectedNotes.clear();selectedNotes.add(note);}audio.selectedNote=note;editFocus='notes';redrawNotes();showContextMenu(e.clientX,e.clientY,[['Copy notes',copySelection],['Duplicate notes',duplicateSelectedNotes],['Quantize',quantizeNotes],['Humanize',proHumanize],['Legato',proLegato],['Delete notes',deleteSelectedNotes]]);});
      };
      const proBaseInspector=studioRenderInspector;studioRenderInspector=function(){proBaseInspector();const panel=$('#studioInspector'),track=getTrack();if(!panel||track.type==='audio')return;const card=document.createElement('div');card.className='pro-instrument-shortcut';const text=document.createElement('small');text.textContent=track.type==='drums'?'PER-VOICE TUNING · ENVELOPES':'LAYERS · FILTER · ENVELOPES · MOTION';card.append(text,studioButton('Open instrument designer →',()=>{editorTab='instrument';studioPrefs.editor=true;studioApplyPreferences();renderEditor();}));panel.insertBefore(card,panel.querySelector('.studio-field'));};
      const proBaseEditor=renderEditor;renderEditor=function(){if(editorTab!=='instrument'){proBaseEditor();}else{editorBodyEl.replaceChildren();$('#noteToolbar').style.display='none';$('#noteLength').style.display='none';$('#clearPatternButton').style.display='none';document.querySelectorAll('.editor-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===editorTab));$('#editorTrackName').textContent=getTrack().name;proRenderInstrument(getTrack());studioRenderInspector();updateStatus();}const rollControls=$('#proRollControls');if(rollControls)rollControls.hidden=editorTab!=='piano'||getTrack().type!=='synth';studioRenderBrowser();};
      const proBaseMeter=renderMixerMeters;renderMixerMeters=function(){proBaseMeter();const line=$('.pro-roll-playhead'),clip=selectedClipFor();if(!line)return;line.hidden=!audio.playing||!clip||audio.playheadBeat<clip.start||audio.playheadBeat>clip.start+clip.length;if(!line.hidden)line.style.left=`${((audio.playheadBeat-clip.start)%16)/16*100}%`;};
      const proBaseNormalize=normalizeProjectFile;normalizeProjectFile=function(raw){const next=proBaseNormalize(raw);next.tracks.forEach(t=>{if(t.type==='synth')t.synth=proSynth(t);if(t.type==='drums'){const params={};for(const kind of DRUM_LANES){const p=t.drumParams?.[kind];if(p)params[kind]={tune:clamp(finiteNumber(p.tune,0),-12,12),decay:clamp(finiteNumber(p.decay,1),.25,3),level:clamp(finiteNumber(p.level,1),0,1.5)};}t.drumParams=params;}});return next;};
      function proBuildUI(){
        const brand=$('.brand'),home=document.createElement('a');home.className=brand.className;home.href='../';home.setAttribute('aria-label','Sonora introduction');home.title='Back to Sonora';while(brand.firstChild)home.append(brand.firstChild);brand.replaceWith(home);home.querySelector('.brand-mark').innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.8" stroke-linecap="round" aria-hidden="true"><path d="M4 10v4M9 6v12M14 3v18M19 8v8"/></svg>';
        $('.studio-tag').textContent='STUDIO 3';$('.browser-title small').textContent='SOUND BANK';
        const modes=document.createElement('div');modes.className='browser-categories';modes.id='proLibraryModes';for(const name of ['All','Favorites','My sounds']){const b=studioButton(name,()=>{proLibraryMode=name;modes.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.textContent===name));studioRenderBrowser();},name==='All'?'active':'');modes.append(b);}$('#studioCategories').before(modes);
        const instrument=studioButton('Instrument',()=>{editorTab='instrument';renderEditor();},'editor-tab');instrument.dataset.tab='instrument';$('.editor-tabs').insertBefore(instrument,$('.editor-tab[data-tab="mixer"]'));
        const focus=studioButton('⤢',()=>{$('.app').classList.toggle('pro-focus');focus.setAttribute('aria-pressed',String($('.app').classList.contains('pro-focus')));focus.title=$('.app').classList.contains('pro-focus')?'Restore split workspace':'Expand editor';},'icon-button pro-focus-button');focus.setAttribute('aria-label','Expand editor');focus.setAttribute('aria-pressed','false');$('.editor-tools').append(focus);
        const extra=studioButton('Humanize',proHumanize);extra.id='proHumanize';$('#quantizeNotesButton').after(extra);const legato=studioButton('Legato',proLegato);extra.after(legato);
        const controls=document.createElement('div');controls.className='pro-roll-controls';controls.id='proRollControls';const root=document.createElement('select');root.setAttribute('aria-label','Scale root');['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'].forEach((n,i)=>{const o=document.createElement('option');o.value=i;o.textContent=n;root.append(o);});root.addEventListener('change',()=>{proRoll.root=Number(root.value);renderEditor();});
        const scale=document.createElement('select');scale.setAttribute('aria-label','Scale guide');for(const [v,n] of [['off','Chromatic'],['minor','Minor'],['major','Major'],['pentatonic','Pentatonic'],['dorian','Dorian']]){const o=document.createElement('option');o.value=v;o.textContent=n;scale.append(o);}scale.value=proRoll.scale;scale.addEventListener('change',()=>{proRoll.scale=scale.value;renderEditor();});controls.append(root,scale);
        for(const [key,label] of [['lock','Snap to scale'],['ghosts','Ghost notes']]){const l=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',label);check.addEventListener('change',()=>{proRoll[key]=check.checked;renderEditor();});l.append(check,document.createTextNode(key==='lock'?'Lock':'Ghosts'));controls.append(l);}
        const zoom=studioButton('100%',()=>{proRoll.zoom=proRoll.zoom>=4?1:proRoll.zoom*2;zoom.textContent=`${proRoll.zoom*100}%`;renderEditor();});zoom.id='proRollZoom';zoom.setAttribute('aria-label','Piano roll zoom');controls.append(zoom);
        controls.append(studioButton('Fit notes',()=>{const notes=notesForClip(getTrack());if(notes.length){const low=Math.min(...notes.map(n=>n.pitch)),high=Math.max(...notes.map(n=>n.pitch));getTrack().rollBase=clamp(Math.round((low+high)/2)-12,0,104);}proRoll.scrollY=null;renderEditor();}),studioButton('Keyboard',()=>{proRoll.keyboard=!proRoll.keyboard;renderEditor();}));$('#noteToolbar').append(controls);
        const patch=document.createElement('dialog');patch.id='proPatchDialog';patch.className='studio-dialog';patch.innerHTML='<h2>Keep this sound.</h2><p>Name your patch. It will appear in My sounds on this device.</p><form id="proPatchForm"><label class="studio-field">Patch name<input id="proPatchName" maxlength="48" required aria-label="Patch name" style="padding:10px;background:#111925;border:1px solid #475366;border-radius:6px;color:#e1e9f5;width:65%"></label><button type="submit" class="text-button pro-primary">Save patch</button></form>';patch.append(studioButton('×',()=>patch.close(),'icon-button dialog-close'));document.body.append(patch);
        $('#proPatchForm').addEventListener('submit',e=>{e.preventDefault();const track=project.tracks.find(t=>t.id===patch.dataset.track),name=$('#proPatchName').value.trim();if(!track||!name)return;if(proPatches.length>=100){notify('Your library supports up to 100 patches');return;}const p={id:`user:${Date.now()}`,name,kind:track.type,synth:track.type==='synth'?proSynth(track):undefined,drumKit:track.drumKit,drumParams:clone(track.drumParams||{})};proPatches.push(p);proSaveLibrary();studioEdit(()=>track.instrument=name);patch.close();studioRenderBrowser();notify(`${name} saved to My sounds`);});
        const help=$('#studioHelp');const p=document.createElement('p');p.textContent='Piano roll: Ctrl / Cmd + wheel to zoom; Alt + wheel to shift the pitch range. Drag velocity bars to adjust dynamics. Turn on Lock to draw and move notes in the chosen scale. Use ⤢ to expand the editor.';help.append(p);
        $('#noteVelocity').addEventListener('input',()=>redrawNotes());studioRenderBrowser();
      }
      proBuildUI();
