      // Piano voices share the live, transport and offline rendering path.
      const PIANO_DEFAULTS={engine:'piano',pianoTone:.55,pianoHammer:.22,pianoBody:.4,pianoDecay:5.5,pianoRelease:.24,pianoDynamics:1,pianoAttack:.004,width:.6};
      const PIANO_PRESETS=[
        {name:'Studio Grand',description:'Recorded grand · full dynamics and clear attack',pianoTone:.92,pianoHammer:.68,pianoBody:.56,pianoDecay:8,pianoRelease:.24,pianoDynamics:1.15,pianoAttack:.002,pianoModel:'grand'},
        {name:'Felt Piano',description:'Recorded grand · muted attack and intimate tone',pianoTone:.14,pianoHammer:.06,pianoBody:.68,pianoDecay:3.6,pianoRelease:.32,pianoDynamics:.78,pianoAttack:.014,pianoModel:'felt'},
        {name:'Mellow Upright',description:'Warm synthesized piano · rounded and compact',pianoTone:.42,pianoHammer:.2,pianoBody:.32,pianoDecay:3.8,pianoRelease:.19,pianoDynamics:1,pianoAttack:.004,pianoModel:'website-preview'}
      ];
      PIANO_PRESETS.forEach(p=>SYNTH_PRESETS.unshift({name:p.name,category:'Keys',description:p.description,synth:{...DEFAULT_SYNTH,...PRO_SYNTH,...PIANO_DEFAULTS,...p}}));
      const pianoSynthBase=proSynth;
      proSynth=function(track){let s=pianoSynthBase(track);if(track.instrument==='Mellow Upright'&&s.pianoModel!=='website-preview'){track.synth||={};Object.assign(track.synth,{pianoTone:.42,pianoHammer:.2,pianoBody:.32,pianoDecay:3.8,pianoRelease:.19,pianoModel:'website-preview'});s={...s,...track.synth};}s.engine=s.engine==='piano'?'piano':'synth';for(const [key,min,max] of [['pianoTone',0,1],['pianoHammer',0,1],['pianoBody',0,1],['pianoDecay',1,10],['pianoRelease',.05,1.5],['pianoDynamics',.5,2],['pianoAttack',.002,.04]])s[key]=clamp(finiteNumber(s[key],PIANO_DEFAULTS[key]),min,max);return s;};
      function pianoVoice(ctx,output,track,note,time,duration,live){
        const s=proSynth(track),v=Math.pow(clamp(finiteNumber(note.velocity,.78),.01,1),s.pianoDynamics),freq=noteFrequency(note.pitch+s.octave*12),nodes=[],sources=[];
        const node=n=>(nodes.push(n),n),source=n=>{sources.push(n);if(live)studioTrackSource(n);return n;};
        const amp=node(ctx.createGain()),filter=node(ctx.createBiquadFilter()),pan=node(ctx.createStereoPanner());
        amp.gain.value=1;filter.type='lowpass';filter.frequency.value=Math.min(ctx.sampleRate*.44,1100+s.pianoTone*7800+v*4200);filter.Q.value=.45;pan.pan.value=clamp((note.pitch-60)/48*s.width,-.8,.8);filter.connect(amp);amp.connect(pan);pan.connect(output);
        const decay=s.pianoDecay*Math.pow(2,(60-note.pitch)/48),naturalEnd=time+Math.min(18,decay*2.2+1),peak=.26*Math.pow(v,1.6);
        for(let partial=1;partial<=8;partial++){
          const f=freq*partial*Math.sqrt(1+.00006*(1+s.pianoBody)*partial*partial);if(f>=ctx.sampleRate*.44)continue;
          const osc=source(ctx.createOscillator()),gain=node(ctx.createGain());osc.type='sine';osc.frequency.value=f;osc.detune.value=s.detune+(partial%2?1:-1)*s.pianoBody*2.5;
          const level=peak*Math.pow(.58+s.pianoTone*.18+v*.07,partial-1)/Math.pow(partial,.6),tail=Math.min(naturalEnd,time+decay/(1+(partial-1)*.32));
          gain.gain.setValueAtTime(.00001,time);gain.gain.exponentialRampToValueAtTime(Math.max(.00002,level),time+s.pianoAttack+(1-v)*.004);gain.gain.exponentialRampToValueAtTime(.00001,tail);osc.connect(gain);gain.connect(filter);
        }
        if(s.pianoHammer>0){const noise=source(ctx.createBufferSource()),gain=node(ctx.createGain()),hp=node(ctx.createBiquadFilter());noise.buffer=proNoise(ctx);hp.type='highpass';hp.frequency.value=700+v*1500;gain.gain.setValueAtTime(peak*s.pianoHammer*.35,time);gain.gain.exponentialRampToValueAtTime(.00001,time+.035);noise.connect(hp);hp.connect(gain);gain.connect(filter);}
        let ended=0,released=false;sources.forEach(src=>{src.addEventListener('ended',()=>{src.disconnect();if(++ended===sources.length)nodes.forEach(n=>n.disconnect());},{once:true});src.start(time);src.stop(naturalEnd+.02);});
        function release(at){if(released)return;released=true;const end=at+s.pianoRelease*(1+s.pianoBody*.5);amp.gain.setValueAtTime(1,at);amp.gain.exponentialRampToValueAtTime(.00001,end);sources.forEach(src=>{try{src.stop(Math.min(naturalEnd+.02,end+.03));}catch(_){}});}
        if(duration!==null)release(time+Math.max(.03,duration));
        return ()=>release(ctx.currentTime);
      }
      // Same-origin recordings with overlapping velocity layers. A cold note waits for
      // its recordings; it never changes from an unrelated synth into a sampled piano.
      const pianoBanks=new WeakMap(),pianoDecodedSamples=new Map();let pianoManifestPromise,pianoManifest=null;
      function pianoBank(ctx){let bank=pianoBanks.get(ctx);if(bank){bank.manifest||=pianoManifest;return bank;}bank={buffers:pianoDecodedSamples,pending:new Map(),manifest:pianoManifest};pianoBanks.set(ctx,bank);return bank;}
      async function pianoFetch(path,format='bytes'){let error;for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(new URL(`../assets/piano/${path}`,location.href),{signal:controller.signal});if(!response.ok)throw new Error(`Piano recording unavailable: ${path}`);return await (format==='json'?response.json():response.arrayBuffer());}catch(caught){error=caught;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,150*(attempt+1)));}finally{clearTimeout(timeout);}}throw error;}
      function pianoLoadManifest(){if(!pianoManifestPromise)pianoManifestPromise=pianoFetch('index.json','json').then(manifest=>(pianoManifest=manifest)).catch(error=>{pianoManifestPromise=null;throw error;});return pianoManifestPromise;}
      async function pianoLoadBuffer(ctx,file){const bank=pianoBank(ctx);if(bank.buffers.has(file))return bank.buffers.get(file);if(pianoDecodedSamples.has(file)){const buffer=pianoDecodedSamples.get(file);bank.buffers.set(file,buffer);return buffer;}if(bank.pending.has(file))return bank.pending.get(file);const task=(async()=>{bank.manifest||=await pianoLoadManifest();const buffer=await ctx.decodeAudioData(await pianoFetch(file));pianoDecodedSamples.set(file,buffer);bank.buffers.set(file,buffer);return buffer;})().finally(()=>bank.pending.delete(file));bank.pending.set(file,task);return task;}
      function pianoVelocityLayer(velocity){return velocity<=67/127?'pp':velocity<=84/127?'mp':velocity<=100/127?'mf':'ff';}
      function pianoVelocityMix(velocity){const layers=[['pp',.3],['mp',.58],['mf',.76],['ff',.94]],v=clamp(velocity,.01,1);if(v<=layers[0][1])return [{key:'pp',weight:1}];for(let i=1;i<layers.length;i++){if(v>layers[i][1])continue;const blend=(v-layers[i-1][1])/(layers[i][1]-layers[i-1][1]);return [{key:layers[i-1][0],weight:Math.cos(blend*Math.PI/2)},{key:layers[i][0],weight:Math.sin(blend*Math.PI/2)}].filter(layer=>layer.weight>.0001);}return [{key:'ff',weight:1}];}
      function pianoSamplesFor(ctx,pitch,velocity){const manifest=pianoBank(ctx).manifest;if(!manifest)return [];const target=clamp(Math.round(pitch),21,96);return pianoVelocityMix(velocity).flatMap(mix=>{const samples=manifest.layers.find(layer=>layer.key===mix.key)?.samples;if(!samples?.length)return [];const sample=samples.reduce((best,item)=>Math.abs(item.root-target)<Math.abs(best.root-target)?item:best,samples[0]);return [{...sample,weight:mix.weight}];});}
      function pianoSampleFor(ctx,pitch,velocity){return pianoSamplesFor(ctx,pitch,velocity).sort((a,b)=>b.weight-a.weight)[0]||null;}
      function pianoTouch(track,note){const s=proSynth(track),velocity=Math.pow(clamp(finiteNumber(note.velocity,.78),.01,1),s.pianoDynamics);return {pitch:note.pitch+s.octave*12,velocity:clamp(velocity*(s.pianoModel==='felt'?.8:1),.01,1),amplitude:velocity};}
      function pianoSamplesReady(ctx,pitch,velocity){const samples=pianoSamplesFor(ctx,pitch,velocity);return samples.length>0&&samples.every(sample=>pianoBank(ctx).buffers.has(sample.file));}
      async function pianoEnsureSample(ctx,pitch,velocity){const bank=pianoBank(ctx);bank.manifest||=await pianoLoadManifest();const samples=pianoSamplesFor(ctx,pitch,velocity);if(!samples.length)throw new Error('No piano recording mapped for this note');await Promise.all(samples.map(sample=>pianoLoadBuffer(ctx,sample.file)));return samples;}
      async function pianoWarmNotes(ctx,notes){if(!ctx||!notes?.length)return;const bank=pianoBank(ctx);bank.manifest||=await pianoLoadManifest();const files=new Set();for(const entry of notes){if(typeof entry==='number'){for(const velocity of [.3,.58,.76,.94])pianoSamplesFor(ctx,entry,velocity).forEach(sample=>files.add(sample.file));}else pianoSamplesFor(ctx,entry.pitch,entry.velocity??.78).forEach(sample=>files.add(sample.file));}await Promise.all([...files].map(file=>pianoLoadBuffer(ctx,file)));}
      function pianoSampleVoice(ctx,output,track,note,time,duration,live){const s=proSynth(track),touch=pianoTouch(track,note),samples=pianoSamplesFor(ctx,touch.pitch,touch.velocity);if(!samples.length||!pianoSamplesReady(ctx,touch.pitch,touch.velocity))return null;const bank=pianoBank(ctx),nodes=[],sources=[];
        const node=n=>(nodes.push(n),n),tone=node(ctx.createBiquadFilter()),body=node(ctx.createBiquadFilter()),hammer=node(ctx.createBiquadFilter()),amp=node(ctx.createGain()),pan=node(ctx.createStereoPanner());tone.type='lowpass';tone.frequency.value=Math.min(ctx.sampleRate*.44,950+Math.pow(s.pianoTone,1.85)*17700+touch.velocity*1600);tone.Q.value=.55;body.type='lowshelf';body.frequency.value=230;body.gain.value=(s.pianoBody-.5)*8;hammer.type='highshelf';hammer.frequency.value=2400;hammer.gain.value=(s.pianoHammer-.35)*12;pan.pan.value=clamp((touch.pitch-60)/54*s.width,-.75,.75);tone.connect(body);body.connect(hammer);hammer.connect(amp);amp.connect(pan);pan.connect(output);
        const peak=.5*Math.pow(touch.amplitude,.8),attack=s.pianoAttack,decay=s.pianoDecay*Math.pow(2,(60-touch.pitch)/72);let available=0;
        for(const sample of samples){const source=ctx.createBufferSource(),mix=node(ctx.createGain()),buffer=bank.buffers.get(sample.file),rate=Math.pow(2,(touch.pitch-sample.root+s.detune/100)/12);source.buffer=buffer;source.playbackRate.value=rate;mix.gain.value=sample.weight;source.connect(mix);mix.connect(tone);sources.push(source);available=Math.max(available,buffer.duration/rate);if(live)studioTrackSource(source);}
        const naturalEnd=time+Math.min(available,Math.max(.15,decay*2.4)),decayPoint=Math.min(naturalEnd,time+attack+decay),floor=.00001;let ended=0,released=false;
        amp.gain.setValueAtTime(floor,time);amp.gain.linearRampToValueAtTime(peak,time+attack);amp.gain.exponentialRampToValueAtTime(Math.max(floor,peak*.35),decayPoint);if(naturalEnd>decayPoint)amp.gain.exponentialRampToValueAtTime(floor,naturalEnd);
        sources.forEach(source=>{source.addEventListener('ended',()=>{source.disconnect();if(++ended===sources.length)nodes.forEach(n=>n.disconnect());},{once:true});source.start(time);source.stop(naturalEnd+.01);});
        function release(at){if(released||at>=naturalEnd)return;released=true;const tail=Math.min(naturalEnd,at+s.pianoRelease);try{if(amp.gain.cancelAndHoldAtTime)amp.gain.cancelAndHoldAtTime(at);else{amp.gain.cancelScheduledValues(at);amp.gain.setValueAtTime(Math.max(floor,peak*Math.pow(.35,Math.max(0,at-time-attack)/decay)),at);}amp.gain.exponentialRampToValueAtTime(floor,Math.max(at+.005,tail));sources.forEach(source=>source.stop(Math.min(naturalEnd+.01,tail+.015)));}catch(_){}}
        if(duration!==null)release(time+Math.max(.03,duration));return ()=>release(Math.max(ctx.currentTime,time));
      }
      const pianoBaseVoice=proVoice;proVoice=function(ctx,output,track,note,time,duration,live=true){if(!ctx||!output)return null;const s=proSynth(track);if(s.engine==='piano'&&!track.sampleId){if(s.pianoModel==='website-preview')return pianoVoice(ctx,output,track,note,time,duration,live);return pianoSampleVoice(ctx,output,track,note,time,duration,live);}return pianoBaseVoice(ctx,output,track,note,time,duration,live);};
      function pianoNeedsSamples(track){const s=proSynth(track);return s.engine==='piano'&&!track.sampleId&&s.pianoModel!=='website-preview';}
      const pianoBaseAudition=proAudition;proAudition=async function(track=getTrack(),chord=false){const request=audio.startRequest;if(pianoNeedsSamples(track)){await audioReady();const root=60;try{await pianoWarmNotes(audio.context,(chord?[0,3,7]:[0]).map(offset=>pianoTouch(track,{pitch:root+offset,velocity:.78})));}catch(_){notify('Piano recordings could not load. Retry the preview.');return;}if(request!==audio.startRequest)return;}return pianoBaseAudition(track,chord);};
      function pianoWarmPerformance(ctx,track=getTrack()){if(!ctx||!pianoNeedsSamples(track))return Promise.resolve();const start=pianoPerformance.range===88?48:clamp(keyboardBasePitch-(pianoPerformance.range===49?12:0),0,127-pianoPerformance.range),count=Math.min(25,pianoPerformance.range),octave=proSynth(track).octave*12;return pianoWarmNotes(ctx,Array.from({length:count},(_,i)=>start+i+octave)).catch(()=>notify('Piano recordings are loading. Your first note will wait for its sound.'));}
      const pianoBasePlayNote=playNote;playNote=function(track,note,time,duration){if(!audio.context||!pianoNeedsSamples(track))return pianoBasePlayNote(track,note,time,duration);const ctx=audio.context,transport=audio.playing,request=audio.startRequest,touch=pianoTouch(track,note);if(pianoSamplesReady(ctx,touch.pitch,touch.velocity))return pianoBasePlayNote(track,note,time,duration);pianoEnsureSample(ctx,touch.pitch,touch.velocity).then(()=>{if(audio.context===ctx&&request===audio.startRequest&&(!transport||audio.playing))pianoBasePlayNote(track,note,Math.max(time,ctx.currentTime+.005),duration);}).catch(()=>notify('Piano recordings could not load. Check your connection and retry.'));};
      function pianoProjectNotes(){return project.tracks.filter(pianoNeedsSamples).flatMap(track=>(track.clips||[]).flatMap(clip=>notesForClip(track,clip).map(note=>pianoTouch(track,note))));}
      const pianoBaseLoadProject=loadProjectInstruments;loadProjectInstruments=async function(){await pianoBaseLoadProject();if(audio.context)await pianoWarmNotes(audio.context,pianoProjectNotes());};
      const pianoBaseStartPlayback=startPlayback;startPlayback=async function(...args){await audioReady();if(audio.context){const notes=pianoProjectNotes();if(notes.length)try{await pianoWarmNotes(audio.context,notes);}catch(_){notify('Piano recordings could not load. Playback has been held so no notes are skipped.');return;}}return pianoBaseStartPlayback.apply(this,args);};
      const pianoBaseExportWav=exportWav;exportWav=async function(){const notes=pianoProjectNotes();if(notes.length)try{await audioReady();await pianoWarmNotes(audio.context,notes);}catch(_){notify('Piano recordings could not load. Retry before exporting.');return;}return pianoBaseExportWav.apply(this,arguments);};
      const pianoPerformance={range:25,velocity:.8,chord:'single',inversion:0,pedal:new Set(),deferred:new Set(),chords:new Map()};
      let pianoInputEditing=false;
      const pianoChords={single:[0],major:[0,4,7],minor:[0,3,7],seventh:[0,4,7,10],minor7:[0,3,7,10],sus2:[0,2,7],sus4:[0,5,7]};
      function pianoChordPitches(root,quality,inversion=0){const offsets=[...(pianoChords[quality]||[0])];for(let i=0;i<Math.min(inversion,offsets.length-1);i++)offsets[i]+=12;return offsets.map(o=>clamp(root+o,0,127));}
      function pianoPedal(source,down){down?pianoPerformance.pedal.add(source):pianoPerformance.pedal.delete(source);if(!pianoPerformance.pedal.size){for(const item of pianoPerformance.deferred)item.release();pianoPerformance.deferred.clear();}pianoSyncPerformance();}
      const pianoBaseHeld=startHeldNote;startHeldNote=function(track,note,velocity,time=audio.context?.currentTime||0){let release;if(pianoNeedsSamples(track)&&audio.context){const ctx=audio.context,touch=pianoTouch(track,{...note,velocity});if(pianoSamplesReady(ctx,touch.pitch,touch.velocity))release=pianoBaseHeld(track,note,velocity,time);else{let requested=false,actualRelease=null;pianoEnsureSample(ctx,touch.pitch,touch.velocity).then(()=>{if(audio.context!==ctx||requested)return;actualRelease=pianoBaseHeld(track,note,velocity,Math.max(time,ctx.currentTime+.005));}).catch(()=>notify('Piano recordings could not load. Check your connection and retry.'));release=()=>{requested=true;actualRelease?.();};}}else release=pianoBaseHeld(track,note,velocity,time);let done=false;return ()=>{if(done)return;done=true;if(pianoPerformance.pedal.size)pianoPerformance.deferred.add({release,pitch:note.pitch});else release();pianoSyncPerformance();};};
      const pianoBaseDown=(...args)=>{pianoInputEditing=true;try{return liveNoteDownOriginal(...args);}finally{pianoInputEditing=false;}},liveNoteDownOriginal=liveNoteDown;
      const pianoBaseUp=(...args)=>{pianoInputEditing=true;try{return liveNoteUpOriginal(...args);}finally{pianoInputEditing=false;}},liveNoteUpOriginal=liveNoteUp;
      liveNoteDown=function(source,pitch,velocity=.82,timestamp=performance.now()){if(activeLiveNotes.has(source)||pianoPerformance.chords.has(source))return;const assisted=editorTab==='perform'&&(source.startsWith('performance:')||source.startsWith('computer:'));const pitches=assisted?pianoChordPitches(pitch,pianoPerformance.chord,pianoPerformance.inversion):[pitch];for(const p of pitches){for(const item of pianoPerformance.deferred){if(item.pitch===p){item.release();pianoPerformance.deferred.delete(item);}}}if(pitches.length>1){const ids=pitches.map((_,i)=>`${source}:chord:${i}`);pianoPerformance.chords.set(source,ids);pitches.forEach((p,i)=>pianoBaseDown(ids[i],p,velocity,timestamp));}else pianoBaseDown(source,pitch,velocity,timestamp);pianoSyncPerformance();};
      liveNoteUp=function(source,timestamp){const ids=pianoPerformance.chords.get(source);if(ids){ids.forEach(id=>pianoBaseUp(id,timestamp));pianoPerformance.chords.delete(source);}else pianoBaseUp(source,timestamp);pianoSyncPerformance();};
      const pianoBaseRelease=releaseAllLiveNotes;releaseAllLiveNotes=function(){pianoPerformance.pedal.clear();for(const item of pianoPerformance.deferred)item.release();pianoPerformance.deferred.clear();pianoBaseRelease();pianoPerformance.chords.clear();pianoSyncPerformance();};
      const pianoBaseMidi=handleMidiMessage;handleMidiMessage=function(input,event){const [status,control,value]=event.data||[];if((status&0xf0)===0xb0&&control===64){pianoPedal(`midi:${input.id}:${status&15}`,value>=64);return;}pianoBaseMidi(input,event);};
      const pianoBaseConnect=connectMidiKeyboard;connectMidiKeyboard=async function(){await pianoBaseConnect();if(!midiAccess)return;pianoWarmPerformance(audio.context);const previous=midiAccess.onstatechange;midiAccess.onstatechange=event=>{if(event.port?.type==='input'&&event.port.state==='disconnected'){for(const source of [...pianoPerformance.pedal])if(source.startsWith(`midi:${event.port.id}:`))pianoPedal(source,false);}previous?.(event);};};
      function pianoSyncPerformance(){const pitches=new Set([...activeLiveNotes.values()].map(n=>n.pitch)),held=new Set([...pianoPerformance.deferred].map(n=>n.pitch));document.querySelectorAll('.performance-key').forEach(k=>{const pitch=Number(k.dataset.pitch);k.classList.toggle('pressed',pitches.has(pitch));k.classList.toggle('sustained',held.has(pitch));k.setAttribute('aria-pressed',String(pitches.has(pitch)));});const button=$('#pianoSustain');if(button){button.classList.toggle('active',!!pianoPerformance.pedal.size);button.setAttribute('aria-pressed',String(!!pianoPerformance.pedal.size));}const label=$('#performanceNow');if(label)label.textContent=pitches.size?[...pitches].sort((a,b)=>a-b).map(pitchName).join(' · '):held.size?'Sustain active':'No active notes';}
      function pianoLoad(track,name){const preset=SYNTH_PRESETS.find(p=>p.name===name);if(!preset)return;releaseAllLiveNotes();studioEdit(()=>{track.instrument=preset.name;track.synth=clone(preset.synth);track.waveform=preset.synth.waveform;delete track.sampleId;delete track.sampleRootPitch;});if(audio.context)pianoWarmPerformance(audio.context,track);}
      function pianoSoundControls(parent,track){track.synth=proSynth(track);for(const [key,label,min,max,step] of [['pianoTone','Brightness',0,1,.01],['pianoHammer','Attack tone',0,1,.01],['pianoBody','Body',0,1,.01],['pianoAttack','Attack softness',.002,.04,.001],['pianoDecay','Decay',1,10,.1],['pianoRelease','Key release',.05,1.5,.01],['pianoDynamics','Dynamic response',.5,2,.05],['width','Key spread',0,1,.01],['detune','Fine tuning',-100,100,1]])studioRange(parent,label,track.synth[key],min,max,step,v=>track.synth[key]=v,v=>key==='pianoDecay'||key==='pianoRelease'?`${v.toFixed(2)} s`:key==='pianoAttack'?`${Math.round(v*1000)} ms`:key==='pianoDynamics'?`${v.toFixed(2)}×`:key==='detune'?`${v>0?'+':''}${v} ct`:`${Math.round(v*100)}%`);}
      function pianoRenderPerformance(track){
        const root=document.createElement('div');root.className='performance';editorBodyEl.append(root);
        if(track.type!=='synth'){root.innerHTML='<h2>Choose an instrument track</h2><p>Open a keys, bass or pad track to play its sound here.</p>';return;}
        const top=document.createElement('div');top.className='performance-top';top.innerHTML='<div><small>SONORA / PERFORMANCE</small><h2></h2><p>Play using the on-screen keys, computer keyboard, or a MIDI controller.</p></div>';top.querySelector('h2').textContent=track.instrument;const controls=document.createElement('div');controls.className='performance-top-actions';
        const sounds=document.createElement('select');sounds.id='pianoSound';sounds.setAttribute('aria-label','Piano sound');const current=document.createElement('option');current.value='';current.textContent=`Current · ${track.instrument}`;sounds.append(current);PIANO_PRESETS.forEach(p=>{const o=document.createElement('option');o.value=p.name;o.textContent=p.name;sounds.append(o);});sounds.addEventListener('change',()=>{if(sounds.value)pianoLoad(track,sounds.value);});
        controls.append(sounds,studioButton('Sound designer ↗',()=>{editorTab='instrument';renderEditor();}));top.append(controls);root.append(top);
        const tools=document.createElement('div');tools.className='performance-tools';
        const range=document.createElement('select');range.id='pianoRange';range.setAttribute('aria-label','Keyboard size');for(const count of [25,49,88]){const o=document.createElement('option');o.value=count;o.textContent=`${count} keys`;range.append(o);}range.value=pianoPerformance.range;range.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.range=Number(range.value);renderEditor();});
        const chord=document.createElement('select');chord.id='pianoChordMode';chord.setAttribute('aria-label','Performance chord mode');Object.entries({single:'Single notes',major:'Major triad',minor:'Minor triad',seventh:'Dominant 7',minor7:'Minor 7',sus2:'Sus 2',sus4:'Sus 4'}).forEach(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;chord.append(o);});chord.value=pianoPerformance.chord;chord.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.chord=chord.value;});
        const sustain=studioButton('◉ Sustain · Shift',()=>pianoPedal('button',!pianoPerformance.pedal.has('button')));sustain.id='pianoSustain';sustain.setAttribute('aria-pressed','false');
        const inversion=document.createElement('select');inversion.setAttribute('aria-label','Performance chord inversion');for(const [value,label] of [[0,'Root position'],[1,'1st inversion'],[2,'2nd inversion']]){const o=document.createElement('option');o.value=value;o.textContent=label;inversion.append(o);}inversion.value=pianoPerformance.inversion;inversion.addEventListener('change',()=>{releaseAllLiveNotes();pianoPerformance.inversion=Number(inversion.value);});
        const touch=document.createElement('label');touch.className='performance-touch';touch.textContent='Touch';const velocity=document.createElement('input');velocity.type='range';velocity.min=10;velocity.max=100;velocity.value=Math.round(pianoPerformance.velocity*100);velocity.setAttribute('aria-label','Computer keyboard velocity');velocity.addEventListener('input',()=>pianoPerformance.velocity=Number(velocity.value)/100);touch.append(velocity);
        const shift=delta=>{releaseAllLiveNotes();keyboardBasePitch=clamp(keyboardBasePitch+delta,24,84);renderEditor();};
        tools.append(range,studioButton('− Octave',()=>shift(-12)),studioButton('+ Octave',()=>shift(12)),chord,inversion,touch,sustain,studioButton('All notes off',releaseAllLiveNotes));root.append(tools);
        const strip=document.createElement('div');strip.className='performance-readout';strip.innerHTML='<span id="performanceNow" role="status"></span><span>TOP OF KEY = SOFT · BOTTOM = BRIGHT</span>';root.append(strip);
        const scroll=document.createElement('div');scroll.className='performance-scroll';const bed=document.createElement('div');bed.className='performance-bed';bed.setAttribute('aria-label','Playable piano keyboard');scroll.append(bed);root.append(scroll);
        const count=pianoPerformance.range,start=count===88?21:clamp(keyboardBasePitch-(count===49?12:0),0,127-count),whitePitches=[];
        for(let pitch=start;pitch<start+count;pitch++)if(![1,3,6,8,10].includes(pitch%12))whitePitches.push(pitch);
        bed.style.setProperty('--white-count',whitePitches.length);bed.style.minWidth=`${whitePitches.length*(count===88?34:42)}px`;
        const pointerSources=new Map();
        for(let pitch=start;pitch<start+count;pitch++){const black=[1,3,6,8,10].includes(pitch%12),key=document.createElement('button');key.type='button';key.className=`performance-key ${black?'black':'white'}`;key.dataset.pitch=pitch;key.setAttribute('aria-label',`Play ${pitchName(pitch)}`);key.setAttribute('aria-pressed','false');const wi=whitePitches.filter(p=>p<pitch).length;key.style.left=`${(black?wi-.31:wi)/whitePitches.length*100}%`;key.style.width=`${(black?.62:1)/whitePitches.length*100}%`;key.innerHTML='<span></span><small></small>';key.firstChild.textContent=black?pitchName(pitch).replace(/\d+/,''):pitchName(pitch);const code=Object.entries(LIVE_KEY_PITCHES).find(([,offset])=>keyboardBasePitch+offset===pitch)?.[0];key.lastChild.textContent=code?.replace('Key','').replace('Digit','')||'';if(proRoll.scale!=='off'&&proScales[proRoll.scale].includes((pitch-proRoll.root+120)%12))key.classList.add('scale-key');
          key.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const r=key.getBoundingClientRect(),velocity=clamp(.35+(e.clientY-r.top)/r.height*.6,.2,1),source=`performance:${e.pointerId}`;pointerSources.set(e.pointerId,source);key.setPointerCapture(e.pointerId);liveNoteDown(source,pitch,velocity);});
          const up=e=>{const source=pointerSources.get(e.pointerId);if(source){liveNoteUp(source);pointerSources.delete(e.pointerId);}};key.addEventListener('pointerup',up);key.addEventListener('pointercancel',up);key.addEventListener('lostpointercapture',up);
          key.addEventListener('keydown',e=>{if(e.code==='Space'||e.key==='Enter'){e.preventDefault();e.stopPropagation();if(!e.repeat)liveNoteDown(`performance:accessible:${pitch}`,pitch,pianoPerformance.velocity);}});key.addEventListener('keyup',e=>{if(e.code==='Space'||e.key==='Enter'){e.preventDefault();e.stopPropagation();liveNoteUp(`performance:accessible:${pitch}`);}});key.addEventListener('blur',()=>liveNoteUp(`performance:accessible:${pitch}`));bed.append(key);}
        const footer=document.createElement('div');footer.className='performance-footer';footer.innerHTML='<span>Computer keys Z–M & Q–U · hold Shift for pedal · Arm recording and start playback to record notes</span>';if(!selectedClipFor(track))footer.append(studioButton('+ Add recording clip',addClip));const midi=document.createElement('div');midi.className='performance-midi';const midiSelect=document.createElement('select');midiSelect.id='midiInputSelect';midiSelect.setAttribute('aria-label','Performance MIDI input');midiSelect.addEventListener('change',()=>{releaseAllLiveNotes();midiInputId=midiSelect.value;refreshMidiKeyboard();});const midiStatus=document.createElement('span');midiStatus.id='midiStatus';const midiButton=studioButton('Connect MIDI',connectMidiKeyboard);midiButton.id='midiConnectButton';midi.append(midiStatus,midiSelect,midiButton);footer.append(midi);root.append(footer);refreshMidiKeyboard();
        if(proSynth(track).engine==='piano'&&!track.sampleId){const params=document.createElement('div');params.className='piano-parameters';pianoSoundControls(params,track);root.append(params);}if(audio.context)pianoWarmPerformance(audio.context,track);pianoSyncPerformance();
      }
      const pianoInstrumentBase=proRenderInstrument;proRenderInstrument=function(track){if(proSynth(track).engine!=='piano'||track.type!=='synth'||track.sampleId){pianoInstrumentBase(track);return;}const root=document.createElement('div');root.className='instrument-editor piano-designer';root.innerHTML='<div class="instrument-eyebrow">SONORA / PIANO DESIGN</div><h2></h2><p></p>';root.querySelector('h2').textContent=track.instrument;root.querySelector('p').textContent=proSynth(track).pianoModel==='website-preview'?'Warm synthesized piano, matching the Sonora website preview. Shape its tone, attack and dynamics.':'Recorded grand piano with four smoothly blended velocity layers. Shape its attack, dynamics, body and stereo placement.';const actions=document.createElement('div');actions.className='instrument-actions';actions.append(studioButton('▷ Audition',()=>proAudition(track,true),'text-button pro-primary'),studioButton('Save patch',()=>proOpenPatch(track)),studioButton('Reset sound',()=>{const preset=PIANO_PRESETS.find(p=>p.name===track.instrument);if(preset)pianoLoad(track,preset.name);else notify('Load a factory piano to reset its controls.');}),studioButton('Play this piano →',()=>{editorTab='perform';renderEditor();}));root.append(actions);const params=document.createElement('div');params.className='piano-parameters';pianoSoundControls(params,track);root.append(params);editorBodyEl.append(root);};
      const pianoBaseEditor=renderEditor;renderEditor=function(){if(editorTab!=='perform'){pianoBaseEditor();return;}if(pianoInputEditing&&$('.performance')){pianoSyncPerformance();return;}editorBodyEl.replaceChildren();$('#noteToolbar').style.display='none';$('#noteLength').style.display='none';$('#clearPatternButton').style.display='none';$('#proRollControls').hidden=true;document.querySelectorAll('.editor-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='perform'));$('#editorTrackName').textContent=`${getTrack().name} · Performance`;pianoRenderPerformance(getTrack());studioRenderInspector();updateStatus();};
      const performTab=studioButton('Perform',()=>{releaseAllLiveNotes();editorTab='perform';renderEditor();audioReady().then(()=>pianoWarmPerformance(audio.context,getTrack())).catch(()=>{});},'editor-tab');performTab.dataset.tab='perform';$('.editor-tabs').insertBefore(performTab,$('.editor-tab[data-tab="instrument"]'));
      window.addEventListener('keydown',e=>{if(editorTab!=='perform'||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='ShiftLeft'||e.code==='ShiftRight'){pianoPedal(e.code,true);return;}if(Object.hasOwn(LIVE_KEY_PITCHES,e.code)){e.preventDefault();if(!e.repeat)liveNoteDown(`computer:${e.code}`,keyboardBasePitch+LIVE_KEY_PITCHES[e.code],pianoPerformance.velocity);}});
      window.addEventListener('keyup',e=>{if(e.code==='ShiftLeft'||e.code==='ShiftRight')pianoPedal(e.code,false);});
      document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAllLiveNotes();});
      const pianoTools=document.createElement('div');pianoTools.className='piano-compose-tools';pianoTools.id='pianoComposeTools';pianoTools.innerHTML='<span class="piano-tools-label">CHORD BUILDER</span><select id="pianoChordQuality" aria-label="Insert chord type"><option value="minor">Minor</option><option value="major">Major</option><option value="minor7">Minor 7</option><option value="seventh">Dominant 7</option><option value="sus2">Sus 2</option><option value="sus4">Sus 4</option></select><select id="pianoInversion" aria-label="Chord inversion"><option value="0">Root position</option><option value="1">1st inversion</option><option value="2">2nd inversion</option></select>';
      function pianoInsertChord(){const track=getTrack(),clip=selectedClipFor(track);if(!clip||track.type!=='synth')return;const chosen=selectedNoteList(),anchor=chosen[0],root=anchor?.pitch??60+proRoll.root,start=clamp(anchor?.start??pianoCursor,0,15.9375),duration=Math.min(anchor?.duration??(Number($('#noteLength').value)||1),16-start),before=JSON.stringify(project),notes=notesForClip(track,clip);selectedNotes.clear();pianoChordPitches(root,$('#pianoChordQuality').value,Number($('#pianoInversion').value)).forEach(pitch=>{let note=notes.find(n=>n.start===start&&n.pitch===pitch);if(!note){note={start,pitch,duration,velocity:anchor?.velocity??.78};notes.push(note);}selectedNotes.add(note);});audio.selectedNote=selectedNoteList()[0];commitNoteEdit(before);}
      function pianoArpeggiate(){const notes=selectedNoteList();if(notes.length<2){notify('Select two or more notes to arpeggiate');return;}const before=JSON.stringify(project),start=Math.min(...notes.map(n=>n.start)),step=Number($('#snapSelect').value)||.25;notes.sort((a,b)=>a.pitch-b.pitch).forEach((n,i)=>{n.start=Math.min(15.9375,start+i*step);n.duration=Math.min(step,16-n.start);});commitNoteEdit(before);}
      pianoTools.append(studioButton('+ Insert chord',pianoInsertChord),studioButton('Arpeggiate',pianoArpeggiate));
      const noteDetails=document.createElement('div');noteDetails.className='piano-note-details';noteDetails.id='pianoNoteDetails';noteDetails.innerHTML='<span id="pianoSelectionLabel">Select a note to fine-tune</span>';
      for(const [key,label,min,max,step] of [['pitch','Pitch',0,127,1],['start','Start · beats',0,15.95,.0625],['duration','Length · beats',.0625,16,.0625],['velocity','Velocity · %',1,100,1]]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.type='number';input.min=min;input.max=max;input.step=step;input.id=`pianoNote-${key}`;input.setAttribute('aria-label',`Selected note ${label}`);input.disabled=true;field.append(input);noteDetails.append(field);input.addEventListener('change',()=>{const notes=selectedNoteList();if(!notes.length||!Number.isFinite(input.valueAsNumber))return;const before=JSON.stringify(project),value=clamp(input.valueAsNumber,min,max);notes.forEach(n=>{n[key]=key==='velocity'?value/100:value;n.start=clamp(n.start,0,16-.0625);n.duration=clamp(n.duration,.0625,16-n.start);});commitNoteEdit(before);});}
      $('#noteToolbar').append(pianoTools,noteDetails);
      function pianoUpdateDetails(){const notes=selectedNoteList(),note=notes[0];$('#pianoSelectionLabel').textContent=notes.length===1?pitchName(note.pitch):notes.length?`${notes.length} notes selected`:'Select a note to fine-tune';for(const key of ['pitch','start','duration','velocity']){const input=$(`#pianoNote-${key}`);input.disabled=!note||(notes.length>1&&['pitch','start'].includes(key));if(document.activeElement!==input)input.value=note?Number((key==='velocity'?(note.velocity??.78)*100:note[key]).toFixed(3)):'';}}
      const pianoBaseControls=updateNoteControls;updateNoteControls=function(){pianoBaseControls();pianoUpdateDetails();};
      $('.studio-tag').textContent='STUDIO 4';studioRenderBrowser();
