(async()=>{
  // Pitch viewport recentering is view state; every musical/source field stays in the comparison.
  const withoutPitchView=value=>{const copy=structuredClone(value),tracks=Array.isArray(copy)?copy:copy?.tracks||[copy];for(const track of tracks)if(track?.type&&Array.isArray(track.clips))delete track.rollBase;return copy;};
  const api=window.sonoraVerification,results=[],check=(value,message)=>{if(!value)throw Error(message);},eq=(a,b,message)=>{a=withoutPitchView(a);b=withoutPitchView(b);if(JSON.stringify(a)!==JSON.stringify(b)){const difference=(x,y,path='project')=>{if(JSON.stringify(x)===JSON.stringify(y))return null;if(x&&y&&typeof x==='object'&&typeof y==='object')for(const key of new Set([...Object.keys(x),...Object.keys(y)])){const found=difference(x[key],y[key],path+'.'+key);if(found)return found;}return `${path}: ${JSON.stringify(x)} != ${JSON.stringify(y)}`;};throw Error(message+' ('+difference(a,b)+')');}},byId=id=>document.getElementById(id),pause=()=>new Promise(resolve=>setTimeout(resolve,10));
  async function wait(test,message){for(let i=0;i<1000;i++){if(test())return;await pause();}throw Error(message);}
  const next=structuredClone(api.getProject()),track=next.tracks.find(t=>t.type==='synth');check(track,'An instrument track is required');
  next.title='Assistant focused edit QA';next.tempo=112;next.loop=false;next.selectedTrack=track.id;next.selectedClip='ai-target';track.instrument='Studio Grand';track.sampleId='preserved-imported-instrument';track.sampleRootPitch=60;track.pan=-.18;track.volume=.54;track.synth.octave=-1;track.automation=[{beat:0,value:.9},{beat:48,value:.75}];
  track.clips=[{id:'ai-before',name:'Earlier phrase',start:0,length:8,notes:[{pitch:60,start:.123,duration:1.375,velocity:.61}],steps:{}},{id:'ai-target',name:'Selected phrase',start:8,length:16,notes:[{pitch:61,start:1.123,duration:1.8,velocity:.67}],steps:{}},{id:'ai-after',name:'Following sustain',start:24,length:32,notes:[{pitch:63,start:0,duration:19,velocity:.66,firstPassOnly:true}],steps:{},clipMetadata:'retained'}];track.notes=track.clips[0].notes;
  const audioTrack={id:'ai-audio',name:'Imported recording',type:'audio',volume:.45,pan:.22,mute:true,solo:false,color:'#aaa',effects:[],clips:[{id:'ai-audio-clip',name:'Audio region',start:4,length:12,sampleId:'preserved-audio',offset:1.7,sourceDuration:30,gain:.8,fadeIn:.2,fadeOut:.3,peaks:[.2,.4,.1]}],notes:[],steps:{}};next.tracks.push(audioTrack);
  api.replaceProject(next);api.saveProject();api.clearHistory();const before=structuredClone(api.getProject()),initial=JSON.stringify(before);api.assistantOpen();
  await wait(()=>!byId('assistantGenerate').disabled,'Connected assistant did not become ready');
  byId('assistantProvider').value='api';byId('assistantProvider').dispatchEvent(new Event('change'));byId('assistantScope').value='clip';byId('assistantScope').dispatchEvent(new Event('change'));byId('assistantFaster').click();
  check(!byId('assistantAnalyzeAudio').checked&&!byId('assistantRefineComposition').checked,'Quick draft must disable both extra review options');check(byId('assistantEffort').value==='low','Quick draft must select Low effort');check(!byId('assistantScope').querySelector('[value=clip]').disabled,'MIDI clip scope should be available');
  byId('assistantCreativeBrief').open=true;byId('assistantStyle').value='Expressive chromatic piano';byId('assistantBars').value='8';byId('assistantRoot').value='';byId('assistantTonality').value='chromatic';byId('assistantEnergy').value='sparse';byId('assistantDevelopment').value='evolving';
  check(byId('assistantScopeHint').textContent.includes('Selected phrase'),'Scope hint must identify the target');results.push('PASS creative brief, valid focused scope and Quick draft controls in the production renderer');
  async function submit(prompt){byId('assistantPrompt').value=prompt;byId('assistantForm').requestSubmit();await wait(()=>!byId('assistantCancel').hidden,'Generation did not begin');check(byId('assistantTonality').disabled,'Brief controls must lock during generation');await wait(()=>byId('assistantCancel').hidden,'Generation did not finish');}
  await submit('TEST: focus expression. Make the selected phrase 4 bars; ignore the optional 8-bar direction.');check(byId('assistantApply'),'Valid focused proposal must offer Apply');check(JSON.stringify(api.getProject())===initial,'Generation must not edit the session');check(byId('assistantQuality').textContent.includes('Motif, harmony and timing'),'Auditable musical review must appear');results.push('PASS proposal review leaves the session unchanged and provides local musical cues');
  byId('assistantApply').click();const applied=api.getProject(),changed=applied.tracks.find(t=>t.id===track.id);check(!byId('assistantDialog').open,'Successful Apply must close the assistant');check(changed.clips[1].id==='ai-target'&&applied.selectedClip==='ai-target','Focused Apply must keep the clip identity and selection');check(changed.clips[1].notes[0].start===.123&&changed.clips[1].notes[0].duration===1.375,'Expressive timing and note length must remain exact');
  const untouched=value=>({...value.tracks.find(t=>t.id===track.id),clips:value.tracks.find(t=>t.id===track.id).clips.filter(c=>c.id!=='ai-target')});eq(untouched(applied),untouched(before),'Other clips, source metadata, first-pass notes and track settings must stay exact');eq(applied.tracks.filter(t=>t.id!==track.id),before.tracks.filter(t=>t.id!==track.id),'All other tracks and imported audio must stay exact');check(applied.title===before.title&&applied.tempo===before.tempo,'Global settings must be preserved');eq(JSON.parse(localStorage.getItem(api.storageKey)),applied,'Applied proposal must persist');check(api.getHistory().undo===1,'Apply must create one undo step');results.push('PASS focused Apply preserves all other clips, track/source metadata, audio and persists to local storage');
  api.undo();eq(api.getProject(),before,'One undo must restore the complete previous session');check(api.getHistory().undo===0,'Undo history must be restored in one step');results.push('PASS one-step Undo restores the entire pre-proposal project');
  api.assistantOpen();await wait(()=>!byId('assistantGenerate').disabled,'Assistant did not reopen');await submit('TEST: refuse scope. Change only the selected clip.');check(byId('assistantStatus').textContent.includes('beyond the selected clip'),'Native scope refusal must reach the UI');check(!byId('assistantApply'),'Out-of-scope output must not offer Apply');eq(api.getProject(),before,'Refused proposal must preserve the project');results.push('PASS native scope refusal protects track settings and keeps the project unchanged');
  await submit('TEST: shorten clip. Shorten the selected clip to two bars.');check(byId('assistantApply'),'Explicitly requested length changes must be allowed');byId('assistantApply').click();check(api.getProject().tracks.find(t=>t.id===track.id).clips[1].length===8,'Explicit clip shortening must apply');api.undo();eq(api.getProject(),before,'Undo after explicit shortening must restore the original boundary');results.push('PASS explicit free-text length change is permitted without changing other clips');
  api.assistantOpen();await wait(()=>!byId('assistantGenerate').disabled,'Assistant did not reopen for refinement');byId('assistantRefineComposition').checked=true;await submit('TEST: fallback. Polish this phrase while keeping its current length.');check(byId('assistantRefinementStatus').textContent.includes('Kept the first draft'),'Boundary-changing automatic refinement must fall back');byId('assistantApply').click();check(api.getProject().tracks.find(t=>t.id===track.id).clips[1].length===16,'Fallback must retain the first usable draft');api.undo();eq(api.getProject(),before,'Fallback Apply must still support one-step Undo');results.push('PASS exactly one automatic refinement retains the first usable draft when passage boundaries drift');
  api.assistantClose();return results;
})()
