(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SonoraListening=api;})(typeof globalThis==='object'?globalThis:this,function(){
  'use strict';
  const pitchNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
  const round=(n,places=3)=>Number(n.toFixed(places)),db=n=>n>0?round(20*Math.log10(n),1):-120;
  function audibleTracks(project){const solo=project.tracks.some(t=>t.solo);return project.tracks.filter(t=>!t.mute&&(!solo||t.solo));}
  function range(project){const tracks=audibleTracks(project),clips=tracks.flatMap(t=>t.clips||[]);const first=clips.length?Math.min(...clips.map(c=>c.start)):0,last=clips.reduce((end,c)=>Math.max(end,c.start+c.length),first+4);const start=project.loopStart!=null?Math.max(0,project.loopStart):first,end=Math.min(project.loopEnd??last,last,start+28*project.tempo/60);return {start,end:Math.max(start+.25,end)};}
  function events(project,range){const result=[],spb=60/project.tempo;
    for(const track of audibleTracks(project))for(const clip of track.clips||[]){if(track.type==='audio')continue;const period=track.type==='drums'?4:16;const first=Math.max(0,Math.floor((range.start-clip.start-period)/period))*period;
      for(let offset=first;offset<clip.length&&clip.start+offset<range.end;offset+=period){if(track.type==='drums'){for(const [kind,steps] of Object.entries(clip.steps||track.steps||{}))for(const step of steps){let beat=clip.start+offset+step/4;const nominalBeat=beat;if(Math.round(beat*4)%2===1)beat+=(project.swing||0)*.25;if(beat>=range.start&&beat<Math.min(clip.start+clip.length,range.end))result.push({track,clip,kind,beat,nominalBeat,velocity:.8});}}
        else for(const note of clip.notes||track.notes||[]){if(note.firstPassOnly&&offset>0)continue;let beat=clip.start+offset+note.start;const nominalBeat=beat;if(beat>=clip.start+clip.length)continue;if(Math.round(beat*4)%2===1)beat+=(project.swing||0)*.25;const end=Math.min(beat+note.duration,clip.start+clip.length);if(beat<range.end&&end>range.start)result.push({track,clip,note,beat,nominalBeat,duration:(end-beat)*spb});}
      }
      if(result.length>4096)throw Error('This excerpt is too dense for local analysis. Choose a shorter loop range or disable Analyze music locally.');
    }return result.sort((a,b)=>a.beat-b.beat);
  }
  function arrangement(project,excerpt=range(project)){const expanded=events(project,excerpt),spb=60/project.tempo,pitches=Array(12).fill(0),bars=new Map(),tracks=new Map();let offGrid=0;
    for(const event of expanded){const beat=event.beat,bar=Math.floor(beat/4)+1;let row=bars.get(bar);if(!row){row={bar,notes:0,drumHits:0,pitchClasses:Array(12).fill(0),onsets:[]};bars.set(bar,row);}if(row.onsets.length<64)row.onsets.push(round(beat%4));
      if(event.kind)row.drumHits++;else{row.notes++;const pitch=event.note.pitch+(event.track.synth?.octave||0)*12,weight=Math.min(event.duration/spb,4)*(event.note.velocity??.75);pitches[((pitch%12)+12)%12]+=weight;row.pitchClasses[((pitch%12)+12)%12]+=weight;}
      const gridBeat=event.nominalBeat;const deviation=Math.abs(gridBeat*4-Math.round(gridBeat*4))/4*spb*1000;if(deviation>25)offGrid++;
      let track=tracks.get(event.track.id);if(!track){track={id:event.track.id,name:event.track.name,notes:0,drumHits:0};tracks.set(event.track.id,track);}track[event.kind?'drumHits':'notes']++;
    }
    const pc=values=>values.map((weight,index)=>({pitch:pitchNames[index],weight:round(weight)})).filter(x=>x.weight>0).sort((a,b)=>b.weight-a.weight);
    return {tempo:project.tempo,meter:'4/4',swing:project.swing||0,excerpt:{startBeat:round(excerpt.start),endBeat:round(excerpt.end)},audibleTracks:audibleTracks(project).map(t=>({id:t.id,name:t.name,type:t.type,instrument:t.instrument})),scheduledEvents:expanded.length,expressiveOffGridOnsets:offGrid,pitchClasses:pc(pitches),bars:[...bars.values()].map(b=>({...b,pitchClasses:pc(b.pitchClasses),onsets:[...new Set(b.onsets)].sort((a,b)=>a-b)})),trackActivity:[...tracks.values()],interpretation:'MIDI pitch content and scheduled rhythm, including pattern repeats and swing. Off-grid onsets can be intentional humanization, not errors.'};
  }
  // Magnitude spectrum only: useful mix measurements, not a transcription or a musical judgement.
  function fft(real,imag){const size=real.length;for(let i=1,j=0;i<size;i++){let bit=size>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[real[i],real[j]]=[real[j],real[i]];}}
    for(let length=2;length<=size;length<<=1){const angle=-2*Math.PI/length,cos=Math.cos(angle),sin=Math.sin(angle);for(let i=0;i<size;i+=length){let wr=1,wi=0;for(let j=0;j<length/2;j++){const a=i+j,b=a+length/2,tr=wr*real[b]-wi*imag[b],ti=wr*imag[b]+wi*real[b];real[b]=real[a]-tr;imag[b]=imag[a]-ti;real[a]+=tr;imag[a]+=ti;const next=wr*cos-wi*sin;wi=wr*sin+wi*cos;wr=next;}}}}
  function pcm(buffer,{tempo=120,startBeat=0,contentSeconds=buffer.length/buffer.sampleRate}={}){
    const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),rate=buffer.sampleRate,frames=buffer.length;if(!frames||!channels.length)throw Error('No rendered audio to analyze');
    let peak=0,energy=0,clipped=0,invalid=0,cross=0,left=0,right=0;const envelope=[],windowSize=Math.max(1,Math.round(rate*.01));
    for(let start=0;start<frames;start+=windowSize){let sum=0;const end=Math.min(frames,start+windowSize);for(let i=start;i<end;i++){for(const channel of channels){let v=channel[i];if(!Number.isFinite(v)){invalid++;v=0;}peak=Math.max(peak,Math.abs(v));energy+=v*v;sum+=v*v;if(Math.abs(v)>1)clipped++;}if(channels.length>=2){const a=Number.isFinite(channels[0][i])?channels[0][i]:0,b=Number.isFinite(channels[1][i])?channels[1][i]:0;cross+=a*b;left+=a*a;right+=b*b;}}envelope.push(Math.sqrt(sum/((end-start)*channels.length)));}
    const rms=Math.sqrt(energy/(frames*channels.length)),onsets=[];let last=-1;for(let i=2;i<envelope.length-1;i++){const time=i*windowSize/rate;if(time>contentSeconds)break;const rise=envelope[i]-envelope[i-1];if(rise>Math.max(.003,rms*.18)&&rise>envelope[i-1]-envelope[i-2]&&rise>=envelope[i+1]-envelope[i]&&time-last>.08){onsets.push(round(startBeat+time*tempo/60));last=time;}}
    const spectral=[0,0,0],chroma=Array(12).fill(0),size=4096;let weighted=0,totalPower=0;const hop=Math.max(size,Math.floor(rate/4));
    for(let start=0;start+size<=Math.min(frames,contentSeconds*rate);start+=hop){const real=new Float64Array(size),imag=new Float64Array(size);for(let i=0;i<size;i++){const v=channels.reduce((sum,c)=>sum+(Number.isFinite(c[start+i])?c[start+i]:0),0)/channels.length;real[i]=v*(.5-.5*Math.cos(2*Math.PI*i/(size-1)));}fft(real,imag);for(let i=1;i<size/2;i++){const hz=i*rate/size,power=real[i]*real[i]+imag[i]*imag[i];totalPower+=power;weighted+=hz*power;spectral[hz<250?0:hz<4000?1:2]+=power;if(hz>=65&&hz<=2100){const midi=69+12*Math.log2(hz/440),nearest=Math.round(midi);if(Math.abs(midi-nearest)<.25)chroma[((nearest%12)+12)%12]+=power;}}}
    const chromaTotal=chroma.reduce((a,b)=>a+b,0),warnings=[];if(peak>1)warnings.push('Rendered mix exceeds 0 dBFS. Lower levels before export.');if(rms<.0001)warnings.push('The analyzed excerpt is silent or nearly silent.');if(invalid)warnings.push('Invalid samples were detected in the audio engine.');const correlation=left&&right?cross/Math.sqrt(left*right):null;if(correlation!==null&&correlation<-.25)warnings.push('Strong stereo phase cancellation may weaken mono playback.');
    return {durationSeconds:round(frames/rate),analyzedMusicSeconds:round(contentSeconds),sampleRate:rate,peakDbfs:db(peak),rmsDbfs:db(rms),crestDb:peak&&rms?round(20*Math.log10(peak/rms),1):0,clippedSamplePercent:round(clipped/(frames*channels.length)*100,4),stereoCorrelation:correlation===null?null:round(correlation),detectedOnsets: onsets.slice(0,256),spectralCentroidHz:totalPower?Math.round(weighted/totalPower):0,bandEnergyPercent:spectral.map(n=>totalPower?round(n/totalPower*100,1):0),spectralPitchClasses:chroma.map((power,index)=>({pitch:pitchNames[index],percent:chromaTotal?round(power/chromaTotal*100,1):0})),warnings,interpretation:'Measured from the rendered mix. Spectral pitch classes include harmonics and drums; they are not a key detector. Detected onsets include instrument attack and effects; use MIDI timing as the exact schedule. This is local signal analysis, not direct model audio perception.'};
  }
  return {audibleTracks,range,events,arrangement,pcm};
});
