const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
for(const file of ['site/site.js','shared/assistant.js','desktop/main.cjs','desktop/engine.cjs','desktop/preload.cjs','studio/sonora-assistant.js','studio/sonora-pro.js','studio/sonora-studio.js','studio/sonora-piano.js','studio/sonora-design.js','studio/sonora-session.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});
const html=fs.readFileSync(path.join(root,'dist/studio/index.html'),'utf8');
new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
const attributeContext={};vm.createContext(attributeContext);vm.runInContext(html.match(/function htmlAttribute\(value\)\{[^\n]+/)[0],attributeContext);
if(attributeContext.htmlAttribute('" onfocus="alert(1)<>&\'')!=='&#34; onfocus=&#34;alert(1)&#60;&#62;&#38;&#39;')throw new Error('Track attribute escaping failed');
if(html.includes('aria-label="${track.name}'))throw new Error('Track names must not interpolate raw HTML attributes');
if(html.includes('sonoraVerification')||html.includes('verifyResults'))throw new Error('Local verification tools must not ship in production');
for(const file of ['index.html','site.css','site.js','download/index.html','download/download.css','assets/favicon.svg','assets/studio.jpg','assets/perform.jpg','assets/instrument.jpg','studio/index.html'])if(!fs.existsSync(path.join(root,'dist',file)))throw new Error(`Missing production file ${file}`);
console.log('All JavaScript parses; introduction, preview assets and studio are present.');
