'use strict';
const assert=require('node:assert/strict'),music=require('../shared/composition.js'),assistant=require('../shared/assistant.js');
const steps=()=>Object.fromEntries(assistant.lanes.map(l=>[l,[]]));
const note=(pitch,start,duration=1,velocity=.7)=>({pitch,start,duration,velocity});
const project={tempo:100,tracks:[{id:'bass',name:'Bass',type:'synth',instrument:'Deep Mono',synth:{octave:-1},clips:[{start:0,length:64,notes:[note(48,0),note(52,4),note(55,8),note(53,12)]}]},{id:'drums',name:'Drums',type:'drums',clips:[{start:0,length:64,steps:{...steps(),kick:[0,8],snare:[4,12]}}]}]};
const plan={summary:'Draft',title:null,tempo:null,tracks:[{action:'add',clips:[{notes:[note(60,0)],steps:steps()}]}]};
const quiet={composition:music.review(project),audio:{peakDbfs:-8},preview:'LOCAL AUDIO MUST NOT LEAVE DEVICE'};
async function run(){
  const snapshot=JSON.stringify(project),report=music.review(project);assert.equal(JSON.stringify(project),snapshot);assert.equal(report.scheduledNotes,16);assert.equal(report.scheduledDrumHits,64);assert.deepEqual(report.tracks[0].soundingPitchRange,[36,43]);assert.equal(report.coverage.endBeat,64);assert.equal(report.sections.length,4);assert(report.observations.some(o=>o.kind==='static-arrangement'));assert(report.observations.some(o=>o.kind==='repetition'));assert(report.sections.every(s=>s.notes===4&&s.drumHits===16));
  const varied=structuredClone(project);varied.tracks[0].clips=[{start:0,length:16,notes:[note(48,0,1,.6),note(52,4,1,.72)]},{start:16,length:16,notes:[note(50,0,1,.65),note(55,6,1,.8)]}];varied.tracks[1].clips[0].length=32;const v=music.review(varied);assert.equal(v.tracks[0].uniquePatterns,2);assert.equal(v.tracks[0].uniqueRhythms,2);assert(!v.observations.some(o=>o.kind==='static-arrangement'));
  const collisions=structuredClone(project);collisions.tracks[0].clips[0].notes=[note(60,0,2),note(60,0,2),note(60,1,2)];const c=music.review(collisions);assert.equal(c.duplicateNotes,4);assert.equal(c.samePitchOverlaps,12);assert.equal(c.tracks[0].maxPatternPolyphony,3);
  const firstOnly=structuredClone(project);firstOnly.tracks[0].clips[0].notes=[{...note(60,0),firstPassOnly:true}];assert.equal(music.review(firstOnly).scheduledNotes,1);
  const clipped=structuredClone(project);clipped.tracks[0].clips=[{start:0,length:64,notes:[note(60,0,1)]},{start:16,length:32,notes:[note(60,0,2)]}];assert.equal(music.review(clipped).duplicateNotes,2);clipped.tracks[0].clips[1].notes[0].firstPassOnly=true;assert.equal(music.review(clipped).duplicateNotes,1);
  const mute=structuredClone(project);mute.tracks[0].mute=true;assert.equal(music.review(mute).scheduledNotes,0);delete mute.tracks[0].mute;mute.tracks[0].solo=true;assert.equal(music.review(mute).scheduledDrumHits,0);
  const distant={tempo:100,tracks:[{id:'long',type:'synth',clips:[{start:1024,length:4096,notes:[note(60,0)]}]}]};const long=music.review(distant);assert.equal(long.sections.length,128);assert.equal(long.coverage.endBeat,5120);assert.equal(long.scheduledNotes,256);assert(long.sections.at(-1).notes>0);
  const empty=music.review({tempo:120,tracks:[]});assert.equal(empty.sections.length,0);assert.equal(empty.scheduledNotes,0);
  console.log('PASS whole-arrangement analytic repeats, drums, preset octave, variation, collisions, first-pass notes, mute/solo and bounded long-session coverage');
  const request={model:'gpt-6.1-sol',effort:'medium',scope:'add',prompt:'Make a theme',context:{selectedTrack:'original',tracks:[]}},refined={...plan,summary:'Refined'},calls=[];
  const result=await music.compose({request,generate:async r=>{calls.push(r);return calls.length===1?plan:refined;},evaluate:async()=>quiet});assert.equal(calls.length,2);assert.equal(result.proposal.summary,'Refined');assert.equal(calls[1].context.selectedTrack,'original');assert.equal(calls[1].model,request.model);assert.equal(calls[1].effort,request.effort);assert.equal(calls[1].context.previousDraft.proposal,plan);assert(calls[1].context.previousDraft.measurements.composition.coverage.allSections);assert(!JSON.stringify(calls[1]).includes('LOCAL AUDIO'));assert.equal(request.context.previousDraft,undefined);
  for(const options of [{refine:false},{request:{...request,context:{...request.context,previousDraft:{proposal:plan}}}},{generate:async()=>({...plan,tracks:[{action:'update',clips:null}]})}]){let count=0;await music.compose({request,generate:async()=>{count++;return plan;},evaluate:async()=>quiet,...options});if(!options.generate)assert.equal(count,1);}
  const failure=await music.compose({request,generate:async r=>{if(r.context.previousDraft)throw Error('provider offline');return plan;},evaluate:async()=>quiet});assert.equal(failure.proposal,plan);assert.equal(failure.refinement.status,'retained');assert(failure.refinement.message.includes('provider offline'));
  const guard=async quality=>music.compose({request,generate:async r=>r.context.previousDraft?refined:plan,evaluate:async p=>p===plan?quiet:quality});
  assert.equal((await guard({...quiet,composition:{...quiet.composition,duplicateNotes:1}})).proposal,plan);assert.equal((await guard({...quiet,audio:{peakDbfs:1}})).proposal,plan);assert.equal((await guard({...quiet,composition:{...quiet.composition,scheduledNotes:0,scheduledDrumHits:0}})).proposal,plan);
  const cancel=new AbortController();await assert.rejects(()=>music.compose({request,signal:cancel.signal,generate:async r=>{if(r.context.previousDraft){cancel.abort();throw Error('provider stopped');}return plan;},evaluate:async()=>quiet}),/cancelled/);
  const cancelled=new AbortController();cancelled.abort();let contacted=false;await assert.rejects(()=>music.compose({request,signal:cancelled.signal,generate:async()=>{contacted=true;return plan;},evaluate:async()=>quiet}),/cancelled/);assert.equal(contacted,false);
  console.log('PASS exactly one refinement, same model/effort/original scope, MIDI-only feedback, manual/fast/settings skip, provider fallback, regression guards and cancellation');
}
run().catch(error=>{console.error(error.stack);process.exitCode=1;});
