'use strict';
const assert=require('node:assert/strict'),listening=require('../shared/listening.js'),assistant=require('../shared/assistant.js');
const clip={id:'c',start:0,length:32,notes:[{pitch:60,start:0,duration:1,velocity:.8},{pitch:64,start:1.125,duration:1,velocity:.7}]};
const project={tempo:120,tracks:[{id:'p',name:'Piano',type:'synth',clips:[clip],volume:.5},{id:'d',name:'Drums',type:'drums',clips:[{start:0,length:32,steps:{kick:[0],hat:[1,3]}}]},{id:'muted',type:'synth',mute:true,clips:[{...clip,notes:[{pitch:61,start:0,duration:1,velocity:1}]}]}]};
const before=JSON.stringify(project),report=listening.arrangement(project,{start:0,end:32});assert.equal(report.scheduledEvents,28);assert.equal(report.expressiveOffGridOnsets,2);assert(!report.pitchClasses.some(p=>p.pitch==='C♯'));assert.equal(report.bars.find(b=>b.bar===5).notes,2);assert.equal(JSON.stringify(project),before);
const swung={...project,swing:.4,tracks:[project.tracks[1]]},events=listening.events(swung,{start:0,end:4});assert.equal(events.find(e=>e.kind==='hat').beat,.35);
const sustained={tempo:120,tracks:[{id:'held',name:'Sustained first pass',type:'synth',clips:[{start:0,length:64,notes:[{pitch:60,start:15,duration:32,velocity:.75,firstPassOnly:true}]}]}]},held=listening.events(sustained,{start:40,end:44});assert.equal(held.length,1);assert.equal(held[0].beat,15);assert.equal(held[0].duration,16);assert.equal(held[0].note.firstPassOnly,true);assert.equal(listening.events(sustained,{start:48,end:52}).length,0);
const laterDrums=listening.events(project,{start:24,end:28}).filter(e=>e.kind);assert.deepEqual(laterDrums.filter(e=>e.kind==='kick').map(e=>e.beat),[24]);assert.deepEqual(laterDrums.filter(e=>e.kind==='hat').map(e=>e.beat),[24.25,24.75]);
const solo={...project,tracks:project.tracks.map((t,i)=>({...t,solo:i===0}))};assert.equal(listening.audibleTracks(solo).length,1);
function buffer(channels,rate=44100){return {numberOfChannels:channels.length,sampleRate:rate,length:channels[0].length,getChannelData:i=>channels[i]};}
const rate=44100,sine=Float32Array.from({length:rate},(_,i)=>.5*Math.sin(2*Math.PI*440*i/rate));const pcm=listening.pcm(buffer([sine,sine]));assert(Math.abs(pcm.peakDbfs+6)<.1);assert(Math.abs(pcm.rmsDbfs+9)<.1);assert.equal(pcm.clippedSamplePercent,0);assert.equal(pcm.stereoCorrelation,1);assert(pcm.spectralCentroidHz>430&&pcm.spectralCentroidHz<450);assert.equal(pcm.spectralPitchClasses.reduce((a,b)=>a.percent>b.percent?a:b).pitch,'A');
const hot=Float32Array.from(sine,x=>x*4);assert(listening.pcm(buffer([hot,hot])).warnings.some(w=>w.includes('exceeds')));const inverse=Float32Array.from(sine,x=>-x);assert(listening.pcm(buffer([sine,inverse])).warnings.some(w=>w.includes('phase')));assert(listening.pcm(buffer([new Float32Array(rate)])).warnings.some(w=>w.includes('silent')));
const clicks=new Float32Array(rate*2);for(const start of [0,.5,1,1.5])for(let i=0;i<1000;i++)clicks[Math.floor(start*rate)+i]=.8*Math.exp(-i/200);assert(listening.pcm(buffer([clicks]),{tempo:120}).detectedOnsets.length>=3);
const context=assistant.context(project,{instruments:[],effects:[]});context.musicAnalysis={structure:report,audio:pcm};const prompt=assistant.prompt({model:'gpt-6.1-sol',effort:'low',scope:'arrange',prompt:'Fit the bass to the piano',context});assert(prompt.includes('spectralPitchClasses'));assert(prompt.includes('do not receive or hear raw audio'));assert(!prompt.includes('base64'));assert(assistant.models.some(m=>m.id==='gpt-6.1-sol'));
console.log('PASS repeated bar timing, late-excerpt drum repeats and first-pass sustain, swing, humanization, mute/solo, immutable snapshots, stereo RMS/peak, clipping, phase, spectral pitch, audio attacks and GPT-6.1 analysis context');
