'use strict';
// Explicit live evaluation only; never part of CI. Uses the user's existing Codex sign-in.
const {app,session}=require('electron'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve(__dirname,`../desktop-release/composition-live-profile-${Date.now()}`));
const main=require('./main.cjs'),generate=main.engine.generate.bind(main.engine),composition=require('../shared/composition.js'),replay=process.argv.includes('--replay');let calls=0,window;
const destination=path.resolve(__dirname,'../screenshots');fs.mkdirSync(destination,{recursive:true});
if(replay)main.engine.status=async()=>({connected:true});
main.engine.generate=async request=>{calls++;console.log(`${replay?'REPLAY':'LIVE'} pass ${calls}: ${request.model} / ${request.effort}`);if(replay)return JSON.parse(fs.readFileSync(path.join(destination,`composition-live-pass-${calls}.json`),'utf8')).plan;const plan=await generate(request);fs.writeFileSync(path.join(destination,`composition-live-pass-${calls}.json`),JSON.stringify({request,plan},null,2));return plan;};
const js=source=>window.webContents.executeJavaScript(source),wait=async(condition,tries=2400)=>{for(let i=0;i<tries;i++){if(await condition())return;await new Promise(r=>setTimeout(r,200));}throw Error('Live composition timed out');};
const timer=setTimeout(()=>{main.engine.cancel();console.error('Live test time limit reached');app.exit(1);},600000);
app.whenReady().then(async()=>{try{
  // Permit reading the local preview blob solely to save this test's WAV artifact.
  session.defaultSession.webRequest.onHeadersReceived((details,callback)=>callback({responseHeaders:{...details.responseHeaders,'Content-Security-Policy':["default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' blob:; object-src 'none'; frame-src 'none'; base-uri 'self'"]}}));
  await wait(()=>{window=main.getWindow();return window&&!window.webContents.isLoading();},100);window.webContents.setBackgroundThrottling(false);await js("document.querySelector('#assistantButton').click()");await wait(()=>js("document.querySelector('#assistantConnectionState').textContent==='Connected'"),100);
  await js("document.querySelector('#assistantModel').value='gpt-6.1-sol';document.querySelector('#assistantEffort').value='medium';document.querySelector('#assistantPrompt').value='Create a warm soulful 16-bar instrumental at 88 BPM in D minor. Four complementary parts: felt piano harmony, a memorable lead melody on Studio Grand, a warm bass and laid-back drums. Develop a short melodic motif, add an answering phrase, a quieter contrasting section, a drum fill and a purposeful ending. Keep it cohesive and expressive.';document.querySelector('#assistantForm').requestSubmit()");
  await wait(()=>js("document.querySelector('#assistantStatus').textContent.startsWith('Ready to review') || document.querySelector('#assistantStatus').classList.contains('assistant-error')"));
  const status=await js("document.querySelector('#assistantStatus').textContent");assert(status.startsWith('Ready to review'),status);assert.equal(calls,2);
  const text=await js("document.querySelector('#assistantQuality').textContent");assert(text.includes('One composition refinement completed'),text);assert(!text.includes('nearly silent'));
  await js("document.querySelector('#assistantQuality details').open=true;document.querySelector('#assistantQuality').scrollIntoView({block:'start'})");await window.webContents.capturePage();await new Promise(r=>setTimeout(r,500));fs.writeFileSync(path.join(destination,'sonora-live-music-review.png'),(await window.webContents.capturePage()).toPNG());
  const bytes=await js("(async()=>Array.from(new Uint8Array(await (await fetch(document.querySelector('#assistantQuality audio').src)).arrayBuffer())))()");fs.writeFileSync(path.join(destination,'sonora-live-composition.wav'),Buffer.from(bytes));
  await js("document.querySelector('#assistantApply').click()");const project=await js("JSON.parse(localStorage.getItem('sonora-daw-project-v1'))"),report=composition.review(project);fs.writeFileSync(path.join(destination,'composition-live-applied.json'),JSON.stringify({project,report,review:text},null,2));
  assert(report.coverage.endBeat>=64);assert.equal(report.duplicateNotes,0);assert(report.scheduledDrumHits>0);assert(report.tracks.filter(t=>t.scheduledNotes).length>=3);assert(report.tracks.some(t=>t.uniquePatterns>=3));
  console.log(JSON.stringify({result:'PASS real GPT-6.1 Sol draft → actual piano/mix analysis → refinement → Apply',bars:report.coverage.endBeat/4,notes:report.scheduledNotes,hits:report.scheduledDrumHits,tracks:report.tracks.map(t=>({name:t.name,patterns:t.uniquePatterns,register:t.soundingPitchRange})),observations:report.observations,review:text}));clearTimeout(timer);app.exit(0);
}catch(error){console.error(error.stack);main.engine.cancel();clearTimeout(timer);app.exit(1);}});
