'use strict';
// Explicit live release evaluation; uses the existing Codex sign-in and two requests.
const {app,session}=require('electron'),path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
app.setPath('userData',path.resolve(__dirname,`../desktop-release/upgrade-live-profile-${Date.now()}`));
const main=require('./main.cjs'),generate=main.engine.generate.bind(main.engine),composition=require('../shared/composition.js'),replay=process.argv.includes('--replay');let calls=0,window;
const destination=path.resolve(__dirname,'../screenshots');fs.mkdirSync(destination,{recursive:true});
if(replay)main.engine.status=async()=>({connected:true});
main.engine.generate=async request=>{calls++;console.log(`${replay?'REPLAY':'LIVE'} pass ${calls}: ${request.model} / ${request.effort}`);assert.equal(request.context.creativeBrief.bars,16);assert.equal(request.context.creativeBrief.root,2);assert.equal(request.context.creativeBrief.development,'evolving');if(replay)return JSON.parse(fs.readFileSync(path.join(destination,`upgrade-live-pass-${calls}.json`),'utf8')).plan;const plan=await generate(request);fs.writeFileSync(path.join(destination,`upgrade-live-pass-${calls}.json`),JSON.stringify({request,plan},null,2));return plan;};
const js=source=>window.webContents.executeJavaScript(source,true),wait=async(condition,tries=2400)=>{for(let i=0;i<tries;i++){if(await condition())return;await new Promise(r=>setTimeout(r,200));}throw Error('Live upgrade evaluation timed out');};
const timer=setTimeout(()=>{main.engine.cancel();console.error('Live evaluation time limit reached');app.exit(1);},600000);
app.whenReady().then(async()=>{try{
  await wait(()=>{window=main.getWindow();return window&&!window.webContents.isLoading();},100);window.webContents.setBackgroundThrottling(false);
  await js("document.querySelector('#assistantButton').click()");await wait(()=>js("document.querySelector('#assistantConnectionState').textContent==='Connected'"),100);
  await js("document.querySelector('#assistantModel').value='gpt-6.1-sol';document.querySelector('#assistantEffort').value='medium';document.querySelector('#assistantStyle').value='Warm modern chamber music';document.querySelector('#assistantRoot').value='2';document.querySelector('#assistantTonality').value='minor';document.querySelector('#assistantBars').value='16';document.querySelector('#assistantEnergy').value='balanced';document.querySelector('#assistantDevelopment').value='evolving';document.querySelector('#assistantPrompt').value='Compose a cohesive 16-bar modern chamber instrumental at 96 BPM in D minor, using exactly five recorded instruments: Concert Harp for harmony, Concert Flute for a memorable singable lead, Upright Bass for a grounded pulse, Cello Ensemble for an inner sustained voice, and Studio Marimba for sparse answering phrases. Give the lead a recognizable short motif with expressive velocities and an answering variation. Develop four 4-bar sections, introducing the cello later, leaving space for the flute to breathe, a quieter contrasting section and a purposeful ending. Keep registers within each recorded bank and avoid all five parts playing constantly. No drums. Remove the unused empty initial track if helpful.';document.querySelector('#assistantForm').requestSubmit()");
  await wait(()=>js("document.querySelector('#assistantStatus').textContent.startsWith('Ready to review') || document.querySelector('#assistantStatus').classList.contains('assistant-error')"));
  const status=await js("document.querySelector('#assistantStatus').textContent");assert(status.startsWith('Ready to review'),status);assert.equal(calls,2);
  const review=await js("document.querySelector('#assistantQuality').textContent");assert(!review.includes('nearly silent'),review);assert(await js("document.querySelector('#assistantQuality audio').src.startsWith('blob:')"),'Missing real recorded-instrument preview');
  await js("document.querySelector('#assistantQuality details').open=true;document.querySelector('#assistantQuality').scrollIntoView({block:'start'})");await window.webContents.capturePage();await new Promise(r=>setTimeout(r,500));fs.writeFileSync(path.join(destination,'sonora-upgrade-ai-review.png'),(await window.webContents.capturePage()).toPNG());
  await js("document.querySelector('#assistantApply').click()");const project=await js("JSON.parse(localStorage.getItem('sonora-daw-project-v1'))"),report=composition.review(project);fs.writeFileSync(path.join(destination,'upgrade-live-applied.json'),JSON.stringify({project,report,review},null,2));
  assert.equal(report.coverage.endBeat,64);assert.equal(report.duplicateNotes,0);assert.equal(report.scheduledDrumHits,0);
  const sounding=report.tracks.filter(t=>t.scheduledNotes);assert.equal(sounding.length,5);assert(sounding.some(t=>t.uniquePatterns>=3));assert(sounding.every(t=>['Concert Harp','Concert Flute','Upright Bass','Cello Ensemble','Studio Marimba'].includes(t.instrument)));
  await window.webContents.capturePage();await new Promise(r=>setTimeout(r,500));fs.writeFileSync(path.join(destination,'sonora-upgrade-arrangement.png'),(await window.webContents.capturePage()).toPNG());
  await js("document.querySelector('#exportWavButton').click();document.querySelector('#sessionRenderButton').click()");await wait(()=>js("document.querySelector('#sessionExportStatus').textContent.startsWith('Ready:') || (!document.querySelector('#sessionRenderButton').disabled && document.querySelector('#sessionExportStatus').textContent.length>0)"),600);
  const exportStatus=await js("document.querySelector('#sessionExportStatus').textContent");assert(exportStatus.startsWith('Ready:'),exportStatus);
  await wait(()=>js("document.querySelector('#sessionExportPreview').readyState>=1"),100);
  let downloadDone=false,downloadState;
  session.defaultSession.once('will-download',(_event,item)=>{item.setSavePath(path.join(destination,'sonora-upgrade-export.wav'));item.once('done',(_event,state)=>{downloadState=state;downloadDone=true;});});
  await js("document.querySelector('#sessionDownloadButton').click()");await wait(()=>downloadDone,100);assert.equal(downloadState,'completed');
  const wav=fs.readFileSync(path.join(destination,'sonora-upgrade-export.wav'));assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.readUInt16LE(34),24);let peak=0,energy=0,count=0;
  for(let offset=44;offset+2<wav.length;offset+=3){let sample=wav[offset]|wav[offset+1]<<8|wav[offset+2]<<16;if(sample&0x800000)sample-=0x1000000;const value=sample/8388608;peak=Math.max(peak,Math.abs(value));energy+=value*value;count++;}
  assert(peak>.01&&peak<.9);assert(Math.sqrt(energy/count)>.001);
  await window.webContents.capturePage();await new Promise(r=>setTimeout(r,500));fs.writeFileSync(path.join(destination,'sonora-upgrade-export.png'),(await window.webContents.capturePage()).toPNG());
  await js("document.querySelector('#sessionExportDialog').close();document.querySelector('#undoButton').click()");assert.equal(await js("document.querySelectorAll('#arrangementGrid .clip').length"),0);
  console.log(JSON.stringify({result:'PASS real GPT-6.1 Sol creative brief → five sampled instruments → local analysis → refinement → Apply → WAV preview/download → one-step Undo',bars:16,notes:report.scheduledNotes,tracks:sounding.map(t=>({name:t.name,instrument:t.instrument,patterns:t.uniquePatterns,register:t.soundingPitchRange})),observations:report.observations,review,exportStatus,wavBytes:wav.length,peakDbfs:20*Math.log10(peak),rmsDbfs:20*Math.log10(Math.sqrt(energy/count))}));clearTimeout(timer);app.exit(0);
}catch(error){console.error(error.stack);main.engine.cancel();clearTimeout(timer);app.exit(1);}});
